var dir_422b6987b3dc283e4177578842d4ed3a =
[
    [ "meta", "dir_cd34500f0b10ff4a656831be0bbe8a34.html", "dir_cd34500f0b10ff4a656831be0bbe8a34" ],
    [ "rw", "dir_ca3045924bdfac4e27a99290ef625164.html", "dir_ca3045924bdfac4e27a99290ef625164" ],
    [ "AnimBlendFrameData.h", "d1/d71/plugin___i_i_i_2game___i_i_i_2_anim_blend_frame_data_8h.html", "d1/d71/plugin___i_i_i_2game___i_i_i_2_anim_blend_frame_data_8h" ],
    [ "C2deffectsModelInfo.cpp", "dc/df0/_c2deffects_model_info_8cpp.html", null ],
    [ "C2deffectsModelInfo.h", "da/ddc/_c2deffects_model_info_8h.html", "da/ddc/_c2deffects_model_info_8h" ],
    [ "C3dMarker.cpp", "dc/da4/plugin___i_i_i_2game___i_i_i_2_c3d_marker_8cpp.html", "dc/da4/plugin___i_i_i_2game___i_i_i_2_c3d_marker_8cpp" ],
    [ "C3dMarker.h", "db/d8f/plugin___i_i_i_2game___i_i_i_2_c3d_marker_8h.html", "db/d8f/plugin___i_i_i_2game___i_i_i_2_c3d_marker_8h" ],
    [ "C3dMarkers.cpp", "da/d3b/plugin___i_i_i_2game___i_i_i_2_c3d_markers_8cpp.html", "da/d3b/plugin___i_i_i_2game___i_i_i_2_c3d_markers_8cpp" ],
    [ "C3dMarkers.h", "de/d16/plugin___i_i_i_2game___i_i_i_2_c3d_markers_8h.html", [
      [ "C3dMarkers", "d2/d54/class_c3d_markers.html", null ]
    ] ],
    [ "CAnimationStyleDescriptor.h", "da/d8d/plugin___i_i_i_2game___i_i_i_2_c_animation_style_descriptor_8h.html", "da/d8d/plugin___i_i_i_2game___i_i_i_2_c_animation_style_descriptor_8h" ],
    [ "CAnimBlendAssocGroup.h", "d1/d6f/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_assoc_group_8h.html", "d1/d6f/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_assoc_group_8h" ],
    [ "CAnimBlendAssociation.cpp", "da/d84/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_association_8cpp.html", null ],
    [ "CAnimBlendAssociation.h", "d3/df3/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_association_8h.html", "d3/df3/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_association_8h" ],
    [ "CAnimBlendClumpData.cpp", "dc/d7e/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_clump_data_8cpp.html", null ],
    [ "CAnimBlendClumpData.h", "d5/d42/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_clump_data_8h.html", "d5/d42/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_clump_data_8h" ],
    [ "CAnimBlendNode.cpp", "dd/d59/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_node_8cpp.html", null ],
    [ "CAnimBlendNode.h", "d5/d4d/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_node_8h.html", "d5/d4d/plugin___i_i_i_2game___i_i_i_2_c_anim_blend_node_8h" ],
    [ "CAnimBlock.h", "d4/d9e/plugin___i_i_i_2game___i_i_i_2_c_anim_block_8h.html", "d4/d9e/plugin___i_i_i_2game___i_i_i_2_c_anim_block_8h" ],
    [ "CAnimManager.cpp", "de/d04/plugin___i_i_i_2game___i_i_i_2_c_anim_manager_8cpp.html", null ],
    [ "CAnimManager.h", "d0/d53/plugin___i_i_i_2game___i_i_i_2_c_anim_manager_8h.html", [
      [ "CAnimManager", "db/d93/class_c_anim_manager.html", null ]
    ] ],
    [ "CAudioHydrant.cpp", "da/dc8/_c_audio_hydrant_8cpp.html", "da/dc8/_c_audio_hydrant_8cpp" ],
    [ "CAudioHydrant.h", "d5/d17/_c_audio_hydrant_8h.html", "d5/d17/_c_audio_hydrant_8h" ],
    [ "cAudioManager.cpp", "df/d3b/c_audio_manager_8cpp.html", "df/d3b/c_audio_manager_8cpp" ],
    [ "cAudioManager.h", "d7/d42/c_audio_manager_8h.html", "d7/d42/c_audio_manager_8h" ],
    [ "CAutomobile.cpp", "dc/d7a/plugin___i_i_i_2game___i_i_i_2_c_automobile_8cpp.html", null ],
    [ "CAutomobile.h", "de/d93/plugin___i_i_i_2game___i_i_i_2_c_automobile_8h.html", "de/d93/plugin___i_i_i_2game___i_i_i_2_c_automobile_8h" ],
    [ "CAutoPilot.cpp", "d9/dbd/_c_auto_pilot_8cpp.html", null ],
    [ "CAutoPilot.h", "d1/d88/plugin___i_i_i_2game___i_i_i_2_c_auto_pilot_8h.html", "d1/d88/plugin___i_i_i_2game___i_i_i_2_c_auto_pilot_8h" ],
    [ "CBaseModelInfo.cpp", "d9/d1e/plugin___i_i_i_2game___i_i_i_2_c_base_model_info_8cpp.html", null ],
    [ "CBaseModelInfo.h", "db/dcc/plugin___i_i_i_2game___i_i_i_2_c_base_model_info_8h.html", "db/dcc/plugin___i_i_i_2game___i_i_i_2_c_base_model_info_8h" ],
    [ "CBoat.cpp", "df/d68/plugin___i_i_i_2game___i_i_i_2_c_boat_8cpp.html", "df/d68/plugin___i_i_i_2game___i_i_i_2_c_boat_8cpp" ],
    [ "CBoat.h", "d0/dcb/plugin___i_i_i_2game___i_i_i_2_c_boat_8h.html", "d0/dcb/plugin___i_i_i_2game___i_i_i_2_c_boat_8h" ],
    [ "CBox.cpp", "dc/dfa/plugin___i_i_i_2game___i_i_i_2_c_box_8cpp.html", null ],
    [ "CBox.h", "da/d32/plugin___i_i_i_2game___i_i_i_2_c_box_8h.html", "da/d32/plugin___i_i_i_2game___i_i_i_2_c_box_8h" ],
    [ "CBridge.cpp", "de/dd7/_c_bridge_8cpp.html", "de/dd7/_c_bridge_8cpp" ],
    [ "CBridge.h", "d6/dfa/_c_bridge_8h.html", [
      [ "CBridge", "d7/dcf/class_c_bridge.html", null ]
    ] ],
    [ "CBrightLight.cpp", "d7/de2/_c_bright_light_8cpp.html", "d7/de2/_c_bright_light_8cpp" ],
    [ "CBrightLight.h", "d1/da4/_c_bright_light_8h.html", "d1/da4/_c_bright_light_8h" ],
    [ "CBrightLights.cpp", "db/d83/plugin___i_i_i_2game___i_i_i_2_c_bright_lights_8cpp.html", "db/d83/plugin___i_i_i_2game___i_i_i_2_c_bright_lights_8cpp" ],
    [ "CBrightLights.h", "dd/dc7/plugin___i_i_i_2game___i_i_i_2_c_bright_lights_8h.html", "dd/dc7/plugin___i_i_i_2game___i_i_i_2_c_bright_lights_8h" ],
    [ "CBuilding.cpp", "d9/df7/plugin___i_i_i_2game___i_i_i_2_c_building_8cpp.html", null ],
    [ "CBuilding.h", "db/d71/plugin___i_i_i_2game___i_i_i_2_c_building_8h.html", "db/d71/plugin___i_i_i_2game___i_i_i_2_c_building_8h" ],
    [ "CBulletInfo.cpp", "db/dc7/plugin___i_i_i_2game___i_i_i_2_c_bullet_info_8cpp.html", "db/dc7/plugin___i_i_i_2game___i_i_i_2_c_bullet_info_8cpp" ],
    [ "CBulletInfo.h", "d0/d36/plugin___i_i_i_2game___i_i_i_2_c_bullet_info_8h.html", "d0/d36/plugin___i_i_i_2game___i_i_i_2_c_bullet_info_8h" ],
    [ "CBulletTrace.cpp", "de/d7f/plugin___i_i_i_2game___i_i_i_2_c_bullet_trace_8cpp.html", "de/d7f/plugin___i_i_i_2game___i_i_i_2_c_bullet_trace_8cpp" ],
    [ "CBulletTrace.h", "d5/d4e/plugin___i_i_i_2game___i_i_i_2_c_bullet_trace_8h.html", "d5/d4e/plugin___i_i_i_2game___i_i_i_2_c_bullet_trace_8h" ],
    [ "CBulletTraces.cpp", "d3/daf/plugin___i_i_i_2game___i_i_i_2_c_bullet_traces_8cpp.html", "d3/daf/plugin___i_i_i_2game___i_i_i_2_c_bullet_traces_8cpp" ],
    [ "CBulletTraces.h", "d7/d4a/plugin___i_i_i_2game___i_i_i_2_c_bullet_traces_8h.html", [
      [ "CBulletTraces", "d1/d5d/class_c_bullet_traces.html", null ]
    ] ],
    [ "CCam.cpp", "dc/d3d/_c_cam_8cpp.html", null ],
    [ "CCam.h", "db/d5f/plugin___i_i_i_2game___i_i_i_2_c_cam_8h.html", "db/d5f/plugin___i_i_i_2game___i_i_i_2_c_cam_8h" ],
    [ "CCamera.cpp", "d3/d66/plugin___i_i_i_2game___i_i_i_2_c_camera_8cpp.html", "d3/d66/plugin___i_i_i_2game___i_i_i_2_c_camera_8cpp" ],
    [ "CCamera.h", "d0/d66/plugin___i_i_i_2game___i_i_i_2_c_camera_8h.html", "d0/d66/plugin___i_i_i_2game___i_i_i_2_c_camera_8h" ],
    [ "CCarAI.cpp", "d3/d56/plugin___i_i_i_2game___i_i_i_2_c_car_a_i_8cpp.html", "d3/d56/plugin___i_i_i_2game___i_i_i_2_c_car_a_i_8cpp" ],
    [ "CCarAI.h", "d0/d39/plugin___i_i_i_2game___i_i_i_2_c_car_a_i_8h.html", [
      [ "CCarAI", "df/dc9/class_c_car_a_i.html", null ]
    ] ],
    [ "CCarCtrl.cpp", "d0/d1b/plugin___i_i_i_2game___i_i_i_2_c_car_ctrl_8cpp.html", null ],
    [ "CCarCtrl.h", "de/d8d/plugin___i_i_i_2game___i_i_i_2_c_car_ctrl_8h.html", [
      [ "CCarCtrl", "d3/d05/class_c_car_ctrl.html", null ]
    ] ],
    [ "CCarGenerator.cpp", "d7/def/plugin___i_i_i_2game___i_i_i_2_c_car_generator_8cpp.html", null ],
    [ "CCarGenerator.h", "d3/deb/plugin___i_i_i_2game___i_i_i_2_c_car_generator_8h.html", "d3/deb/plugin___i_i_i_2game___i_i_i_2_c_car_generator_8h" ],
    [ "CCheat.cpp", "d3/dce/plugin___i_i_i_2game___i_i_i_2_c_cheat_8cpp.html", "d3/dce/plugin___i_i_i_2game___i_i_i_2_c_cheat_8cpp" ],
    [ "CCheat.h", "d5/dc1/plugin___i_i_i_2game___i_i_i_2_c_cheat_8h.html", "d5/dc1/plugin___i_i_i_2game___i_i_i_2_c_cheat_8h" ],
    [ "CCivilianPed.cpp", "da/de0/plugin___i_i_i_2game___i_i_i_2_c_civilian_ped_8cpp.html", null ],
    [ "CCivilianPed.h", "d4/d87/plugin___i_i_i_2game___i_i_i_2_c_civilian_ped_8h.html", "d4/d87/plugin___i_i_i_2game___i_i_i_2_c_civilian_ped_8h" ],
    [ "CClock.cpp", "d0/d9c/plugin___i_i_i_2game___i_i_i_2_c_clock_8cpp.html", "d0/d9c/plugin___i_i_i_2game___i_i_i_2_c_clock_8cpp" ],
    [ "CClock.h", "d5/d1f/plugin___i_i_i_2game___i_i_i_2_c_clock_8h.html", [
      [ "CClock", "d6/d3e/class_c_clock.html", null ]
    ] ],
    [ "CClouds.cpp", "d4/d79/plugin___i_i_i_2game___i_i_i_2_c_clouds_8cpp.html", "d4/d79/plugin___i_i_i_2game___i_i_i_2_c_clouds_8cpp" ],
    [ "CClouds.h", "d5/df3/plugin___i_i_i_2game___i_i_i_2_c_clouds_8h.html", "d5/df3/plugin___i_i_i_2game___i_i_i_2_c_clouds_8h" ],
    [ "CClumpModelInfo.cpp", "d1/dad/plugin___i_i_i_2game___i_i_i_2_c_clump_model_info_8cpp.html", null ],
    [ "CClumpModelInfo.h", "d2/da2/plugin___i_i_i_2game___i_i_i_2_c_clump_model_info_8h.html", "d2/da2/plugin___i_i_i_2game___i_i_i_2_c_clump_model_info_8h" ],
    [ "CColBox.cpp", "de/d4a/plugin___i_i_i_2game___i_i_i_2_c_col_box_8cpp.html", "de/d4a/plugin___i_i_i_2game___i_i_i_2_c_col_box_8cpp" ],
    [ "CColBox.h", "d4/de9/plugin___i_i_i_2game___i_i_i_2_c_col_box_8h.html", "d4/de9/plugin___i_i_i_2game___i_i_i_2_c_col_box_8h" ],
    [ "CColLine.cpp", "d9/df4/plugin___i_i_i_2game___i_i_i_2_c_col_line_8cpp.html", "d9/df4/plugin___i_i_i_2game___i_i_i_2_c_col_line_8cpp" ],
    [ "CColLine.h", "d7/d5a/plugin___i_i_i_2game___i_i_i_2_c_col_line_8h.html", "d7/d5a/plugin___i_i_i_2game___i_i_i_2_c_col_line_8h" ],
    [ "CCollision.cpp", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_collision_8cpp.html", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_collision_8cpp" ],
    [ "CCollision.h", "d1/de4/plugin___i_i_i_2game___i_i_i_2_c_collision_8h.html", "d1/de4/plugin___i_i_i_2game___i_i_i_2_c_collision_8h" ],
    [ "CColModel.cpp", "d0/d0a/plugin___i_i_i_2game___i_i_i_2_c_col_model_8cpp.html", null ],
    [ "CColModel.h", "db/dd3/plugin___i_i_i_2game___i_i_i_2_c_col_model_8h.html", "db/dd3/plugin___i_i_i_2game___i_i_i_2_c_col_model_8h" ],
    [ "CColPoint.h", "d5/d51/plugin___i_i_i_2game___i_i_i_2_c_col_point_8h.html", "d5/d51/plugin___i_i_i_2game___i_i_i_2_c_col_point_8h" ],
    [ "CColSphere.cpp", "d2/d24/plugin___i_i_i_2game___i_i_i_2_c_col_sphere_8cpp.html", "d2/d24/plugin___i_i_i_2game___i_i_i_2_c_col_sphere_8cpp" ],
    [ "CColSphere.h", "da/d5f/plugin___i_i_i_2game___i_i_i_2_c_col_sphere_8h.html", "da/d5f/plugin___i_i_i_2game___i_i_i_2_c_col_sphere_8h" ],
    [ "CColTriangle.cpp", "d0/dca/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_8cpp.html", "d0/dca/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_8cpp" ],
    [ "CColTriangle.h", "d0/da3/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_8h.html", "d0/da3/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_8h" ],
    [ "CColTrianglePlane.cpp", "da/d6e/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_plane_8cpp.html", "da/d6e/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_plane_8cpp" ],
    [ "CColTrianglePlane.h", "d3/da2/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_plane_8h.html", "d3/da2/plugin___i_i_i_2game___i_i_i_2_c_col_triangle_plane_8h" ],
    [ "CControllerState.cpp", "d0/d16/plugin___i_i_i_2game___i_i_i_2_c_controller_state_8cpp.html", null ],
    [ "CControllerState.h", "da/d6d/plugin___i_i_i_2game___i_i_i_2_c_controller_state_8h.html", "da/d6d/plugin___i_i_i_2game___i_i_i_2_c_controller_state_8h" ],
    [ "CCopPed.cpp", "d0/da7/plugin___i_i_i_2game___i_i_i_2_c_cop_ped_8cpp.html", null ],
    [ "CCopPed.h", "df/d48/plugin___i_i_i_2game___i_i_i_2_c_cop_ped_8h.html", "df/d48/plugin___i_i_i_2game___i_i_i_2_c_cop_ped_8h" ],
    [ "CCoronas.cpp", "d4/dad/plugin___i_i_i_2game___i_i_i_2_c_coronas_8cpp.html", "d4/dad/plugin___i_i_i_2game___i_i_i_2_c_coronas_8cpp" ],
    [ "CCoronas.h", "dc/d08/plugin___i_i_i_2game___i_i_i_2_c_coronas_8h.html", "dc/d08/plugin___i_i_i_2game___i_i_i_2_c_coronas_8h" ],
    [ "CCurrentVehicle.cpp", "dd/d24/_c_current_vehicle_8cpp.html", null ],
    [ "CCurrentVehicle.h", "d3/d0f/plugin___i_i_i_2game___i_i_i_2_c_current_vehicle_8h.html", "d3/d0f/plugin___i_i_i_2game___i_i_i_2_c_current_vehicle_8h" ],
    [ "CCutsceneHead.cpp", "dc/ddd/_c_cutscene_head_8cpp.html", null ],
    [ "CCutsceneHead.h", "d3/deb/_c_cutscene_head_8h.html", "d3/deb/_c_cutscene_head_8h" ],
    [ "CCutsceneMgr.cpp", "d1/d0e/plugin___i_i_i_2game___i_i_i_2_c_cutscene_mgr_8cpp.html", "d1/d0e/plugin___i_i_i_2game___i_i_i_2_c_cutscene_mgr_8cpp" ],
    [ "CCutsceneMgr.h", "d6/dc9/plugin___i_i_i_2game___i_i_i_2_c_cutscene_mgr_8h.html", "d6/dc9/plugin___i_i_i_2game___i_i_i_2_c_cutscene_mgr_8h" ],
    [ "CCutsceneObject.cpp", "d6/d39/plugin___i_i_i_2game___i_i_i_2_c_cutscene_object_8cpp.html", null ],
    [ "CCutsceneObject.h", "d0/d5e/plugin___i_i_i_2game___i_i_i_2_c_cutscene_object_8h.html", "d0/d5e/plugin___i_i_i_2game___i_i_i_2_c_cutscene_object_8h" ],
    [ "CDamageManager.cpp", "d1/d9f/plugin___i_i_i_2game___i_i_i_2_c_damage_manager_8cpp.html", null ],
    [ "CDamageManager.h", "d6/d75/plugin___i_i_i_2game___i_i_i_2_c_damage_manager_8h.html", "d6/d75/plugin___i_i_i_2game___i_i_i_2_c_damage_manager_8h" ],
    [ "CDirectory.cpp", "d6/de6/plugin___i_i_i_2game___i_i_i_2_c_directory_8cpp.html", null ],
    [ "CDirectory.h", "de/d01/plugin___i_i_i_2game___i_i_i_2_c_directory_8h.html", "de/d01/plugin___i_i_i_2game___i_i_i_2_c_directory_8h" ],
    [ "CDoor.cpp", "d6/da4/plugin___i_i_i_2game___i_i_i_2_c_door_8cpp.html", null ],
    [ "CDoor.h", "d5/d97/plugin___i_i_i_2game___i_i_i_2_c_door_8h.html", "d5/d97/plugin___i_i_i_2game___i_i_i_2_c_door_8h" ],
    [ "CDraw.cpp", "d6/d3f/plugin___i_i_i_2game___i_i_i_2_c_draw_8cpp.html", "d6/d3f/plugin___i_i_i_2game___i_i_i_2_c_draw_8cpp" ],
    [ "CDraw.h", "dc/d7a/plugin___i_i_i_2game___i_i_i_2_c_draw_8h.html", [
      [ "CDraw", "d8/d22/class_c_draw.html", null ]
    ] ],
    [ "CDummy.cpp", "d8/d81/plugin___i_i_i_2game___i_i_i_2_c_dummy_8cpp.html", null ],
    [ "CDummy.h", "d9/d13/plugin___i_i_i_2game___i_i_i_2_c_dummy_8h.html", "d9/d13/plugin___i_i_i_2game___i_i_i_2_c_dummy_8h" ],
    [ "CDummyObject.cpp", "de/d07/plugin___i_i_i_2game___i_i_i_2_c_dummy_object_8cpp.html", null ],
    [ "CDummyObject.h", "d4/de4/plugin___i_i_i_2game___i_i_i_2_c_dummy_object_8h.html", "d4/de4/plugin___i_i_i_2game___i_i_i_2_c_dummy_object_8h" ],
    [ "CEmergencyPed.cpp", "d2/d51/plugin___i_i_i_2game___i_i_i_2_c_emergency_ped_8cpp.html", null ],
    [ "CEmergencyPed.h", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_emergency_ped_8h.html", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_emergency_ped_8h" ],
    [ "CEntity.cpp", "dc/d56/plugin___i_i_i_2game___i_i_i_2_c_entity_8cpp.html", null ],
    [ "CEntity.h", "dc/d1e/plugin___i_i_i_2game___i_i_i_2_c_entity_8h.html", "dc/d1e/plugin___i_i_i_2game___i_i_i_2_c_entity_8h" ],
    [ "CEntryInfoList.cpp", "d8/d10/plugin___i_i_i_2game___i_i_i_2_c_entry_info_list_8cpp.html", null ],
    [ "CEntryInfoList.h", "de/df9/plugin___i_i_i_2game___i_i_i_2_c_entry_info_list_8h.html", "de/df9/plugin___i_i_i_2game___i_i_i_2_c_entry_info_list_8h" ],
    [ "CEventList.cpp", "df/dbd/_c_event_list_8cpp.html", "df/dbd/_c_event_list_8cpp" ],
    [ "CEventList.h", "d8/dac/_c_event_list_8h.html", "d8/dac/_c_event_list_8h" ],
    [ "CExplosion.cpp", "da/d72/plugin___i_i_i_2game___i_i_i_2_c_explosion_8cpp.html", "da/d72/plugin___i_i_i_2game___i_i_i_2_c_explosion_8cpp" ],
    [ "CExplosion.h", "de/d66/plugin___i_i_i_2game___i_i_i_2_c_explosion_8h.html", "de/d66/plugin___i_i_i_2game___i_i_i_2_c_explosion_8h" ],
    [ "CFileLoader.cpp", "df/dfd/plugin___i_i_i_2game___i_i_i_2_c_file_loader_8cpp.html", "df/dfd/plugin___i_i_i_2game___i_i_i_2_c_file_loader_8cpp" ],
    [ "CFileLoader.h", "da/dfe/plugin___i_i_i_2game___i_i_i_2_c_file_loader_8h.html", "da/dfe/plugin___i_i_i_2game___i_i_i_2_c_file_loader_8h" ],
    [ "CFileMgr.cpp", "dc/df3/plugin___i_i_i_2game___i_i_i_2_c_file_mgr_8cpp.html", null ],
    [ "CFileMgr.h", "d0/d98/plugin___i_i_i_2game___i_i_i_2_c_file_mgr_8h.html", "d0/d98/plugin___i_i_i_2game___i_i_i_2_c_file_mgr_8h" ],
    [ "CFire.cpp", "d5/d3d/plugin___i_i_i_2game___i_i_i_2_c_fire_8cpp.html", null ],
    [ "CFire.h", "d3/da7/plugin___i_i_i_2game___i_i_i_2_c_fire_8h.html", "d3/da7/plugin___i_i_i_2game___i_i_i_2_c_fire_8h" ],
    [ "CFireManager.cpp", "d6/d94/plugin___i_i_i_2game___i_i_i_2_c_fire_manager_8cpp.html", "d6/d94/plugin___i_i_i_2game___i_i_i_2_c_fire_manager_8cpp" ],
    [ "CFireManager.h", "d3/d6d/plugin___i_i_i_2game___i_i_i_2_c_fire_manager_8h.html", "d3/d6d/plugin___i_i_i_2game___i_i_i_2_c_fire_manager_8h" ],
    [ "CFont.cpp", "d6/df1/plugin___i_i_i_2game___i_i_i_2_c_font_8cpp.html", "d6/df1/plugin___i_i_i_2game___i_i_i_2_c_font_8cpp" ],
    [ "CFont.h", "d5/d28/plugin___i_i_i_2game___i_i_i_2_c_font_8h.html", "d5/d28/plugin___i_i_i_2game___i_i_i_2_c_font_8h" ],
    [ "CFontDetails.cpp", "d8/dcf/plugin___i_i_i_2game___i_i_i_2_c_font_details_8cpp.html", null ],
    [ "CFontDetails.h", "dd/d01/plugin___i_i_i_2game___i_i_i_2_c_font_details_8h.html", "dd/d01/plugin___i_i_i_2game___i_i_i_2_c_font_details_8h" ],
    [ "CGame.cpp", "d0/dee/plugin___i_i_i_2game___i_i_i_2_c_game_8cpp.html", "d0/dee/plugin___i_i_i_2game___i_i_i_2_c_game_8cpp" ],
    [ "CGame.h", "d8/d85/plugin___i_i_i_2game___i_i_i_2_c_game_8h.html", "d8/d85/plugin___i_i_i_2game___i_i_i_2_c_game_8h" ],
    [ "CGameLogic.cpp", "d7/d8d/plugin___i_i_i_2game___i_i_i_2_c_game_logic_8cpp.html", null ],
    [ "CGameLogic.h", "d7/d71/plugin___i_i_i_2game___i_i_i_2_c_game_logic_8h.html", [
      [ "CGameLogic", "d6/db2/class_c_game_logic.html", null ]
    ] ],
    [ "CGangInfo.cpp", "df/dde/plugin___i_i_i_2game___i_i_i_2_c_gang_info_8cpp.html", null ],
    [ "CGangInfo.h", "d1/d53/plugin___i_i_i_2game___i_i_i_2_c_gang_info_8h.html", "d1/d53/plugin___i_i_i_2game___i_i_i_2_c_gang_info_8h" ],
    [ "CGangs.cpp", "d8/d32/plugin___i_i_i_2game___i_i_i_2_c_gangs_8cpp.html", null ],
    [ "CGangs.h", "db/d1e/plugin___i_i_i_2game___i_i_i_2_c_gangs_8h.html", [
      [ "CGangs", "de/d13/class_c_gangs.html", "de/d13/class_c_gangs" ]
    ] ],
    [ "CGarage.cpp", "dd/ddd/_c_garage_8cpp.html", "dd/ddd/_c_garage_8cpp" ],
    [ "CGarage.h", "d0/db0/plugin___i_i_i_2game___i_i_i_2_c_garage_8h.html", "d0/db0/plugin___i_i_i_2game___i_i_i_2_c_garage_8h" ],
    [ "CGarages.cpp", "d9/d61/plugin___i_i_i_2game___i_i_i_2_c_garages_8cpp.html", "d9/d61/plugin___i_i_i_2game___i_i_i_2_c_garages_8cpp" ],
    [ "CGarages.h", "da/d86/plugin___i_i_i_2game___i_i_i_2_c_garages_8h.html", "da/d86/plugin___i_i_i_2game___i_i_i_2_c_garages_8h" ],
    [ "CGeneral.cpp", "d0/d08/plugin___i_i_i_2game___i_i_i_2_c_general_8cpp.html", "d0/d08/plugin___i_i_i_2game___i_i_i_2_c_general_8cpp" ],
    [ "CGeneral.h", "d6/d0c/plugin___i_i_i_2game___i_i_i_2_c_general_8h.html", [
      [ "CGeneral", "db/d2a/class_c_general.html", null ]
    ] ],
    [ "CHeli.cpp", "dd/dad/plugin___i_i_i_2game___i_i_i_2_c_heli_8cpp.html", "dd/dad/plugin___i_i_i_2game___i_i_i_2_c_heli_8cpp" ],
    [ "CHeli.h", "dd/dea/plugin___i_i_i_2game___i_i_i_2_c_heli_8h.html", "dd/dea/plugin___i_i_i_2game___i_i_i_2_c_heli_8h" ],
    [ "CHud.cpp", "d9/d79/plugin___i_i_i_2game___i_i_i_2_c_hud_8cpp.html", "d9/d79/plugin___i_i_i_2game___i_i_i_2_c_hud_8cpp" ],
    [ "CHud.h", "d3/d49/plugin___i_i_i_2game___i_i_i_2_c_hud_8h.html", "d3/d49/plugin___i_i_i_2game___i_i_i_2_c_hud_8h" ],
    [ "CIniFile.cpp", "d8/dbd/plugin___i_i_i_2game___i_i_i_2_c_ini_file_8cpp.html", null ],
    [ "CIniFile.h", "da/d86/plugin___i_i_i_2game___i_i_i_2_c_ini_file_8h.html", [
      [ "CIniFile", "d4/d65/class_c_ini_file.html", null ]
    ] ],
    [ "CInstance.cpp", "d6/dab/_c_instance_8cpp.html", null ],
    [ "CInstance.h", "dd/d8b/_c_instance_8h.html", "dd/d8b/_c_instance_8h" ],
    [ "CKeyboardState.cpp", "de/d8e/plugin___i_i_i_2game___i_i_i_2_c_keyboard_state_8cpp.html", null ],
    [ "CKeyboardState.h", "de/d52/plugin___i_i_i_2game___i_i_i_2_c_keyboard_state_8h.html", "de/d52/plugin___i_i_i_2game___i_i_i_2_c_keyboard_state_8h" ],
    [ "CLines.cpp", "da/deb/_c_lines_8cpp.html", "da/deb/_c_lines_8cpp" ],
    [ "CLines.h", "d9/d1b/_c_lines_8h.html", [
      [ "CLines", "d3/d44/class_c_lines.html", null ]
    ] ],
    [ "CLink.h", "d9/d5c/plugin___i_i_i_2game___i_i_i_2_c_link_8h.html", "d9/d5c/plugin___i_i_i_2game___i_i_i_2_c_link_8h" ],
    [ "CLinkList.h", "d3/da9/plugin___i_i_i_2game___i_i_i_2_c_link_list_8h.html", "d3/da9/plugin___i_i_i_2game___i_i_i_2_c_link_list_8h" ],
    [ "CMatrix.cpp", "d0/d9b/plugin___i_i_i_2game___i_i_i_2_c_matrix_8cpp.html", "d0/d9b/plugin___i_i_i_2game___i_i_i_2_c_matrix_8cpp" ],
    [ "CMatrix.h", "d8/d9b/plugin___i_i_i_2game___i_i_i_2_c_matrix_8h.html", "d8/d9b/plugin___i_i_i_2game___i_i_i_2_c_matrix_8h" ],
    [ "CMenuManager.cpp", "d9/d65/plugin___i_i_i_2game___i_i_i_2_c_menu_manager_8cpp.html", "d9/d65/plugin___i_i_i_2game___i_i_i_2_c_menu_manager_8cpp" ],
    [ "CMenuManager.h", "d2/d03/plugin___i_i_i_2game___i_i_i_2_c_menu_manager_8h.html", "d2/d03/plugin___i_i_i_2game___i_i_i_2_c_menu_manager_8h" ],
    [ "CMessages.cpp", "d2/d74/plugin___i_i_i_2game___i_i_i_2_c_messages_8cpp.html", null ],
    [ "CMessages.h", "d0/df2/plugin___i_i_i_2game___i_i_i_2_c_messages_8h.html", "d0/df2/plugin___i_i_i_2game___i_i_i_2_c_messages_8h" ],
    [ "CMloModelInfo.cpp", "de/d5c/_c_mlo_model_info_8cpp.html", null ],
    [ "CMloModelInfo.h", "d5/d83/_c_mlo_model_info_8h.html", "d5/d83/_c_mlo_model_info_8h" ],
    [ "CModelInfo.cpp", "df/d72/plugin___i_i_i_2game___i_i_i_2_c_model_info_8cpp.html", null ],
    [ "CModelInfo.h", "df/dfd/plugin___i_i_i_2game___i_i_i_2_c_model_info_8h.html", [
      [ "CModelInfo", "dd/df3/class_c_model_info.html", null ]
    ] ],
    [ "CMotionBlurStreaks.cpp", "d4/d72/plugin___i_i_i_2game___i_i_i_2_c_motion_blur_streaks_8cpp.html", "d4/d72/plugin___i_i_i_2game___i_i_i_2_c_motion_blur_streaks_8cpp" ],
    [ "CMotionBlurStreaks.h", "d1/d63/plugin___i_i_i_2game___i_i_i_2_c_motion_blur_streaks_8h.html", [
      [ "CMotionBlurStreaks", "d4/d5e/class_c_motion_blur_streaks.html", null ]
    ] ],
    [ "CMouseControllerState.cpp", "d4/ddf/_c_mouse_controller_state_8cpp.html", null ],
    [ "CMouseControllerState.h", "d7/df0/plugin___i_i_i_2game___i_i_i_2_c_mouse_controller_state_8h.html", "d7/df0/plugin___i_i_i_2game___i_i_i_2_c_mouse_controller_state_8h" ],
    [ "CMovie.cpp", "df/d1e/plugin___i_i_i_2game___i_i_i_2_c_movie_8cpp.html", null ],
    [ "CMovie.h", "d9/d2a/plugin___i_i_i_2game___i_i_i_2_c_movie_8h.html", "d9/d2a/plugin___i_i_i_2game___i_i_i_2_c_movie_8h" ],
    [ "cMusicManager.cpp", "d0/d89/c_music_manager_8cpp.html", "d0/d89/c_music_manager_8cpp" ],
    [ "cMusicManager.h", "df/d53/c_music_manager_8h.html", "df/d53/c_music_manager_8h" ],
    [ "CNodeAddress.h", "d2/da4/plugin___i_i_i_2game___i_i_i_2_c_node_address_8h.html", "d2/da4/plugin___i_i_i_2game___i_i_i_2_c_node_address_8h" ],
    [ "CObject.cpp", "dd/d74/plugin___i_i_i_2game___i_i_i_2_c_object_8cpp.html", null ],
    [ "CObject.h", "d0/da2/plugin___i_i_i_2game___i_i_i_2_c_object_8h.html", "d0/da2/plugin___i_i_i_2game___i_i_i_2_c_object_8h" ],
    [ "CObjectData.cpp", "d0/d52/_c_object_data_8cpp.html", null ],
    [ "CObjectData.h", "de/dc3/_c_object_data_8h.html", "de/dc3/_c_object_data_8h" ],
    [ "common.cpp", "d9/d52/plugin___i_i_i_2game___i_i_i_2common_8cpp.html", "d9/d52/plugin___i_i_i_2game___i_i_i_2common_8cpp" ],
    [ "common.h", "d9/d72/plugin___i_i_i_2game___i_i_i_2common_8h.html", "d9/d72/plugin___i_i_i_2game___i_i_i_2common_8h" ],
    [ "COnscreenTimer.cpp", "d7/deb/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_8cpp.html", "d7/deb/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_8cpp" ],
    [ "COnscreenTimer.h", "d3/d85/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_8h.html", "d3/d85/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_8h" ],
    [ "COnscreenTimerEntry.cpp", "d3/d98/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_entry_8cpp.html", "d3/d98/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_entry_8cpp" ],
    [ "COnscreenTimerEntry.h", "d9/d7a/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_entry_8h.html", "d9/d7a/plugin___i_i_i_2game___i_i_i_2_c_onscreen_timer_entry_8h" ],
    [ "CPad.cpp", "d3/d21/plugin___i_i_i_2game___i_i_i_2_c_pad_8cpp.html", null ],
    [ "CPad.h", "dd/d25/plugin___i_i_i_2game___i_i_i_2_c_pad_8h.html", "dd/d25/plugin___i_i_i_2game___i_i_i_2_c_pad_8h" ],
    [ "CPager.cpp", "db/dfc/plugin___i_i_i_2game___i_i_i_2_c_pager_8cpp.html", null ],
    [ "CPager.h", "db/da7/plugin___i_i_i_2game___i_i_i_2_c_pager_8h.html", "db/da7/plugin___i_i_i_2game___i_i_i_2_c_pager_8h" ],
    [ "CParticle.cpp", "d1/ddd/plugin___i_i_i_2game___i_i_i_2_c_particle_8cpp.html", null ],
    [ "CParticle.h", "d7/d14/plugin___i_i_i_2game___i_i_i_2_c_particle_8h.html", [
      [ "CParticle", "da/dfa/class_c_particle.html", "da/dfa/class_c_particle" ]
    ] ],
    [ "cParticleSystemMgr.cpp", "df/dbe/plugin___i_i_i_2game___i_i_i_2c_particle_system_mgr_8cpp.html", "df/dbe/plugin___i_i_i_2game___i_i_i_2c_particle_system_mgr_8cpp" ],
    [ "cParticleSystemMgr.h", "de/db4/plugin___i_i_i_2game___i_i_i_2c_particle_system_mgr_8h.html", "de/db4/plugin___i_i_i_2game___i_i_i_2c_particle_system_mgr_8h" ],
    [ "CPathFind.cpp", "d0/d84/plugin___i_i_i_2game___i_i_i_2_c_path_find_8cpp.html", "d0/d84/plugin___i_i_i_2game___i_i_i_2_c_path_find_8cpp" ],
    [ "CPathFind.h", "dd/de1/plugin___i_i_i_2game___i_i_i_2_c_path_find_8h.html", "dd/de1/plugin___i_i_i_2game___i_i_i_2_c_path_find_8h" ],
    [ "CPathNode.cpp", "d3/de1/plugin___i_i_i_2game___i_i_i_2_c_path_node_8cpp.html", null ],
    [ "CPathNode.h", "d9/d4b/plugin___i_i_i_2game___i_i_i_2_c_path_node_8h.html", "d9/d4b/plugin___i_i_i_2game___i_i_i_2_c_path_node_8h" ],
    [ "CPathSplines.h", "d0/d83/_c_path_splines_8h.html", "d0/d83/_c_path_splines_8h" ],
    [ "CPed.cpp", "d7/d05/plugin___i_i_i_2game___i_i_i_2_c_ped_8cpp.html", "d7/d05/plugin___i_i_i_2game___i_i_i_2_c_ped_8cpp" ],
    [ "CPed.h", "d7/d6e/plugin___i_i_i_2game___i_i_i_2_c_ped_8h.html", "d7/d6e/plugin___i_i_i_2game___i_i_i_2_c_ped_8h" ],
    [ "CPedIK.cpp", "df/d21/plugin___i_i_i_2game___i_i_i_2_c_ped_i_k_8cpp.html", null ],
    [ "CPedIK.h", "d6/d4e/plugin___i_i_i_2game___i_i_i_2_c_ped_i_k_8h.html", "d6/d4e/plugin___i_i_i_2game___i_i_i_2_c_ped_i_k_8h" ],
    [ "CPedModelInfo.cpp", "da/d67/plugin___i_i_i_2game___i_i_i_2_c_ped_model_info_8cpp.html", null ],
    [ "CPedModelInfo.h", "dd/d91/plugin___i_i_i_2game___i_i_i_2_c_ped_model_info_8h.html", "dd/d91/plugin___i_i_i_2game___i_i_i_2_c_ped_model_info_8h" ],
    [ "CPedPlacement.cpp", "db/d22/plugin___i_i_i_2game___i_i_i_2_c_ped_placement_8cpp.html", null ],
    [ "CPedPlacement.h", "d2/dda/plugin___i_i_i_2game___i_i_i_2_c_ped_placement_8h.html", [
      [ "CPedPlacement", "de/d1d/class_c_ped_placement.html", null ]
    ] ],
    [ "CPedStats.cpp", "db/d35/plugin___i_i_i_2game___i_i_i_2_c_ped_stats_8cpp.html", null ],
    [ "CPedStats.h", "d1/d10/plugin___i_i_i_2game___i_i_i_2_c_ped_stats_8h.html", "d1/d10/plugin___i_i_i_2game___i_i_i_2_c_ped_stats_8h" ],
    [ "CPedType.cpp", "d6/d07/plugin___i_i_i_2game___i_i_i_2_c_ped_type_8cpp.html", null ],
    [ "CPedType.h", "d7/d47/plugin___i_i_i_2game___i_i_i_2_c_ped_type_8h.html", "d7/d47/plugin___i_i_i_2game___i_i_i_2_c_ped_type_8h" ],
    [ "CPhone.cpp", "d0/dea/plugin___i_i_i_2game___i_i_i_2_c_phone_8cpp.html", "d0/dea/plugin___i_i_i_2game___i_i_i_2_c_phone_8cpp" ],
    [ "CPhone.h", "d8/d61/plugin___i_i_i_2game___i_i_i_2_c_phone_8h.html", "d8/d61/plugin___i_i_i_2game___i_i_i_2_c_phone_8h" ],
    [ "CPhoneInfo.cpp", "d7/d67/plugin___i_i_i_2game___i_i_i_2_c_phone_info_8cpp.html", "d7/d67/plugin___i_i_i_2game___i_i_i_2_c_phone_info_8cpp" ],
    [ "CPhoneInfo.h", "dd/de9/plugin___i_i_i_2game___i_i_i_2_c_phone_info_8h.html", "dd/de9/plugin___i_i_i_2game___i_i_i_2_c_phone_info_8h" ],
    [ "CPhysical.cpp", "d8/dd7/plugin___i_i_i_2game___i_i_i_2_c_physical_8cpp.html", null ],
    [ "CPhysical.h", "d8/d6d/plugin___i_i_i_2game___i_i_i_2_c_physical_8h.html", "d8/d6d/plugin___i_i_i_2game___i_i_i_2_c_physical_8h" ],
    [ "CPlaceable.cpp", "db/d87/plugin___i_i_i_2game___i_i_i_2_c_placeable_8cpp.html", null ],
    [ "CPlaceable.h", "d4/d5d/plugin___i_i_i_2game___i_i_i_2_c_placeable_8h.html", "d4/d5d/plugin___i_i_i_2game___i_i_i_2_c_placeable_8h" ],
    [ "CPlaceName.cpp", "d6/d2a/_c_place_name_8cpp.html", null ],
    [ "CPlaceName.h", "d7/db4/_c_place_name_8h.html", "d7/db4/_c_place_name_8h" ],
    [ "CPlane.cpp", "db/d09/plugin___i_i_i_2game___i_i_i_2_c_plane_8cpp.html", "db/d09/plugin___i_i_i_2game___i_i_i_2_c_plane_8cpp" ],
    [ "CPlane.h", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_plane_8h.html", "d6/d89/plugin___i_i_i_2game___i_i_i_2_c_plane_8h" ],
    [ "CPlayerInfo.cpp", "d5/dad/plugin___i_i_i_2game___i_i_i_2_c_player_info_8cpp.html", null ],
    [ "CPlayerInfo.h", "de/de6/plugin___i_i_i_2game___i_i_i_2_c_player_info_8h.html", "de/de6/plugin___i_i_i_2game___i_i_i_2_c_player_info_8h" ],
    [ "CPlayerPed.cpp", "d6/d7a/plugin___i_i_i_2game___i_i_i_2_c_player_ped_8cpp.html", null ],
    [ "CPlayerPed.h", "d6/d8a/plugin___i_i_i_2game___i_i_i_2_c_player_ped_8h.html", "d6/d8a/plugin___i_i_i_2game___i_i_i_2_c_player_ped_8h" ],
    [ "CPlayerSkin.cpp", "df/d50/plugin___i_i_i_2game___i_i_i_2_c_player_skin_8cpp.html", null ],
    [ "CPlayerSkin.h", "dc/db7/plugin___i_i_i_2game___i_i_i_2_c_player_skin_8h.html", [
      [ "CPlayerSkinData", "dd/d3b/class_c_player_skin_data.html", "dd/d3b/class_c_player_skin_data" ],
      [ "CPlayerSkin", "d9/d90/class_c_player_skin.html", null ]
    ] ],
    [ "CPointLights.cpp", "d5/d9b/plugin___i_i_i_2game___i_i_i_2_c_point_lights_8cpp.html", "d5/d9b/plugin___i_i_i_2game___i_i_i_2_c_point_lights_8cpp" ],
    [ "CPointLights.h", "d3/d41/plugin___i_i_i_2game___i_i_i_2_c_point_lights_8h.html", "d3/d41/plugin___i_i_i_2game___i_i_i_2_c_point_lights_8h" ],
    [ "CPool.h", "dd/d0f/plugin___i_i_i_2game___i_i_i_2_c_pool_8h.html", "dd/d0f/plugin___i_i_i_2game___i_i_i_2_c_pool_8h" ],
    [ "CPools.cpp", "d4/d7e/plugin___i_i_i_2game___i_i_i_2_c_pools_8cpp.html", null ],
    [ "CPools.h", "df/dce/plugin___i_i_i_2game___i_i_i_2_c_pools_8h.html", [
      [ "CPools", "d6/db0/class_c_pools.html", null ]
    ] ],
    [ "CPopulation.cpp", "d6/d95/plugin___i_i_i_2game___i_i_i_2_c_population_8cpp.html", "d6/d95/plugin___i_i_i_2game___i_i_i_2_c_population_8cpp" ],
    [ "CPopulation.h", "d5/d96/plugin___i_i_i_2game___i_i_i_2_c_population_8h.html", [
      [ "CPopulation", "d8/d4f/class_c_population.html", null ]
    ] ],
    [ "CProjectile.cpp", "d9/da0/plugin___i_i_i_2game___i_i_i_2_c_projectile_8cpp.html", null ],
    [ "CProjectile.h", "df/db2/plugin___i_i_i_2game___i_i_i_2_c_projectile_8h.html", "df/db2/plugin___i_i_i_2game___i_i_i_2_c_projectile_8h" ],
    [ "CProjectileInfo.cpp", "dc/de8/plugin___i_i_i_2game___i_i_i_2_c_projectile_info_8cpp.html", "dc/de8/plugin___i_i_i_2game___i_i_i_2_c_projectile_info_8cpp" ],
    [ "CProjectileInfo.h", "d2/df8/plugin___i_i_i_2game___i_i_i_2_c_projectile_info_8h.html", "d2/df8/plugin___i_i_i_2game___i_i_i_2_c_projectile_info_8h" ],
    [ "CPtrList.cpp", "db/d2f/plugin___i_i_i_2game___i_i_i_2_c_ptr_list_8cpp.html", null ],
    [ "CPtrList.h", "d5/dd2/plugin___i_i_i_2game___i_i_i_2_c_ptr_list_8h.html", "d5/dd2/plugin___i_i_i_2game___i_i_i_2_c_ptr_list_8h" ],
    [ "CQuaternion.cpp", "de/df7/plugin___i_i_i_2game___i_i_i_2_c_quaternion_8cpp.html", null ],
    [ "CQuaternion.h", "d3/d6f/plugin___i_i_i_2game___i_i_i_2_c_quaternion_8h.html", "d3/d6f/plugin___i_i_i_2game___i_i_i_2_c_quaternion_8h" ],
    [ "CQueuedMode.h", "de/d91/plugin___i_i_i_2game___i_i_i_2_c_queued_mode_8h.html", "de/d91/plugin___i_i_i_2game___i_i_i_2_c_queued_mode_8h" ],
    [ "CRect.h", "dd/d44/plugin___i_i_i_2game___i_i_i_2_c_rect_8h.html", "dd/d44/plugin___i_i_i_2game___i_i_i_2_c_rect_8h" ],
    [ "CReference.h", "de/db1/plugin___i_i_i_2game___i_i_i_2_c_reference_8h.html", "de/db1/plugin___i_i_i_2game___i_i_i_2_c_reference_8h" ],
    [ "CReferences.cpp", "d9/d8e/plugin___i_i_i_2game___i_i_i_2_c_references_8cpp.html", null ],
    [ "CReferences.h", "d7/d59/plugin___i_i_i_2game___i_i_i_2_c_references_8h.html", "d7/d59/plugin___i_i_i_2game___i_i_i_2_c_references_8h" ],
    [ "CRegisteredCorona.cpp", "d8/db8/plugin___i_i_i_2game___i_i_i_2_c_registered_corona_8cpp.html", null ],
    [ "CRegisteredCorona.h", "d2/d82/plugin___i_i_i_2game___i_i_i_2_c_registered_corona_8h.html", "d2/d82/plugin___i_i_i_2game___i_i_i_2_c_registered_corona_8h" ],
    [ "CRegisteredMotionBlurStreak.cpp", "da/dd6/plugin___i_i_i_2game___i_i_i_2_c_registered_motion_blur_streak_8cpp.html", "da/dd6/plugin___i_i_i_2game___i_i_i_2_c_registered_motion_blur_streak_8cpp" ],
    [ "CRegisteredMotionBlurStreak.h", "d9/dd3/plugin___i_i_i_2game___i_i_i_2_c_registered_motion_blur_streak_8h.html", "d9/dd3/plugin___i_i_i_2game___i_i_i_2_c_registered_motion_blur_streak_8h" ],
    [ "CRemote.cpp", "da/df0/_c_remote_8cpp.html", "da/df0/_c_remote_8cpp" ],
    [ "CRemote.h", "d9/d2b/_c_remote_8h.html", [
      [ "CRemote", "d7/d24/class_c_remote.html", null ]
    ] ],
    [ "CReplay.cpp", "db/d0e/plugin___i_i_i_2game___i_i_i_2_c_replay_8cpp.html", null ],
    [ "CReplay.h", "d5/db7/plugin___i_i_i_2game___i_i_i_2_c_replay_8h.html", [
      [ "CReplay", "d8/d2c/class_c_replay.html", null ]
    ] ],
    [ "CRestart.cpp", "da/d1b/plugin___i_i_i_2game___i_i_i_2_c_restart_8cpp.html", null ],
    [ "CRestart.h", "dc/db1/plugin___i_i_i_2game___i_i_i_2_c_restart_8h.html", [
      [ "CRestart", "d1/dc1/class_c_restart.html", null ]
    ] ],
    [ "CRunningScript.cpp", "d4/dca/plugin___i_i_i_2game___i_i_i_2_c_running_script_8cpp.html", null ],
    [ "CRunningScript.h", "de/d52/plugin___i_i_i_2game___i_i_i_2_c_running_script_8h.html", "de/d52/plugin___i_i_i_2game___i_i_i_2_c_running_script_8h" ],
    [ "CScene.cpp", "df/dc3/plugin___i_i_i_2game___i_i_i_2_c_scene_8cpp.html", "df/dc3/plugin___i_i_i_2game___i_i_i_2_c_scene_8cpp" ],
    [ "CScene.h", "d5/d35/plugin___i_i_i_2game___i_i_i_2_c_scene_8h.html", "d5/d35/plugin___i_i_i_2game___i_i_i_2_c_scene_8h" ],
    [ "CSceneEdit.cpp", "d2/dea/plugin___i_i_i_2game___i_i_i_2_c_scene_edit_8cpp.html", "d2/dea/plugin___i_i_i_2game___i_i_i_2_c_scene_edit_8cpp" ],
    [ "CSceneEdit.h", "d5/d34/plugin___i_i_i_2game___i_i_i_2_c_scene_edit_8h.html", "d5/d34/plugin___i_i_i_2game___i_i_i_2_c_scene_edit_8h" ],
    [ "CSector.h", "df/d2d/plugin___i_i_i_2game___i_i_i_2_c_sector_8h.html", "df/d2d/plugin___i_i_i_2game___i_i_i_2_c_sector_8h" ],
    [ "CShadows.cpp", "d6/db3/plugin___i_i_i_2game___i_i_i_2_c_shadows_8cpp.html", "d6/db3/plugin___i_i_i_2game___i_i_i_2_c_shadows_8cpp" ],
    [ "CShadows.h", "d6/d74/plugin___i_i_i_2game___i_i_i_2_c_shadows_8h.html", "d6/d74/plugin___i_i_i_2game___i_i_i_2_c_shadows_8h" ],
    [ "CShinyTexts.cpp", "de/d1e/plugin___i_i_i_2game___i_i_i_2_c_shiny_texts_8cpp.html", "de/d1e/plugin___i_i_i_2game___i_i_i_2_c_shiny_texts_8cpp" ],
    [ "CShinyTexts.h", "dd/d45/plugin___i_i_i_2game___i_i_i_2_c_shiny_texts_8h.html", "dd/d45/plugin___i_i_i_2game___i_i_i_2_c_shiny_texts_8h" ],
    [ "CShotInfo.cpp", "d5/df0/plugin___i_i_i_2game___i_i_i_2_c_shot_info_8cpp.html", "d5/df0/plugin___i_i_i_2game___i_i_i_2_c_shot_info_8cpp" ],
    [ "CShotInfo.h", "d4/d97/plugin___i_i_i_2game___i_i_i_2_c_shot_info_8h.html", "d4/d97/plugin___i_i_i_2game___i_i_i_2_c_shot_info_8h" ],
    [ "CSimpleModelInfo.cpp", "de/daf/plugin___i_i_i_2game___i_i_i_2_c_simple_model_info_8cpp.html", null ],
    [ "CSimpleModelInfo.h", "de/d67/plugin___i_i_i_2game___i_i_i_2_c_simple_model_info_8h.html", "de/d67/plugin___i_i_i_2game___i_i_i_2_c_simple_model_info_8h" ],
    [ "CSpecialParticleStuff.cpp", "de/d23/_c_special_particle_stuff_8cpp.html", null ],
    [ "CSpecialParticleStuff.h", "dd/d5e/_c_special_particle_stuff_8h.html", [
      [ "CSpecialParticleStuff", "d9/da8/class_c_special_particle_stuff.html", null ]
    ] ],
    [ "CSphere.cpp", "d8/d78/plugin___i_i_i_2game___i_i_i_2_c_sphere_8cpp.html", null ],
    [ "CSphere.h", "dd/da4/plugin___i_i_i_2game___i_i_i_2_c_sphere_8h.html", "dd/da4/plugin___i_i_i_2game___i_i_i_2_c_sphere_8h" ],
    [ "CSprite.cpp", "d8/d5c/plugin___i_i_i_2game___i_i_i_2_c_sprite_8cpp.html", null ],
    [ "CSprite.h", "d0/d49/plugin___i_i_i_2game___i_i_i_2_c_sprite_8h.html", [
      [ "CSprite", "d3/d0f/class_c_sprite.html", null ]
    ] ],
    [ "CSprite2d.cpp", "d9/d12/plugin___i_i_i_2game___i_i_i_2_c_sprite2d_8cpp.html", null ],
    [ "CSprite2d.h", "db/d4d/plugin___i_i_i_2game___i_i_i_2_c_sprite2d_8h.html", "db/d4d/plugin___i_i_i_2game___i_i_i_2_c_sprite2d_8h" ],
    [ "CStats.cpp", "d6/dae/plugin___i_i_i_2game___i_i_i_2_c_stats_8cpp.html", null ],
    [ "CStats.h", "d0/d6c/plugin___i_i_i_2game___i_i_i_2_c_stats_8h.html", [
      [ "CStats", "df/dd0/class_c_stats.html", null ]
    ] ],
    [ "CStoredCar.cpp", "df/dd2/_c_stored_car_8cpp.html", null ],
    [ "CStoredCar.h", "de/d12/_c_stored_car_8h.html", "de/d12/_c_stored_car_8h" ],
    [ "CStoredCollPoly.h", "d0/d85/plugin___i_i_i_2game___i_i_i_2_c_stored_coll_poly_8h.html", "d0/d85/plugin___i_i_i_2game___i_i_i_2_c_stored_coll_poly_8h" ],
    [ "CStreaming.cpp", "dc/d57/plugin___i_i_i_2game___i_i_i_2_c_streaming_8cpp.html", "dc/d57/plugin___i_i_i_2game___i_i_i_2_c_streaming_8cpp" ],
    [ "CStreaming.h", "d1/d25/plugin___i_i_i_2game___i_i_i_2_c_streaming_8h.html", "d1/d25/plugin___i_i_i_2game___i_i_i_2_c_streaming_8h" ],
    [ "CStreamingInfo.cpp", "d3/d66/plugin___i_i_i_2game___i_i_i_2_c_streaming_info_8cpp.html", null ],
    [ "CStreamingInfo.h", "d3/d2d/plugin___i_i_i_2game___i_i_i_2_c_streaming_info_8h.html", "d3/d2d/plugin___i_i_i_2game___i_i_i_2_c_streaming_info_8h" ],
    [ "CTheCarGenerators.cpp", "dc/dd1/plugin___i_i_i_2game___i_i_i_2_c_the_car_generators_8cpp.html", null ],
    [ "CTheCarGenerators.h", "dc/d45/plugin___i_i_i_2game___i_i_i_2_c_the_car_generators_8h.html", "dc/d45/plugin___i_i_i_2game___i_i_i_2_c_the_car_generators_8h" ],
    [ "CTheScripts.cpp", "d1/d8c/plugin___i_i_i_2game___i_i_i_2_c_the_scripts_8cpp.html", "d1/d8c/plugin___i_i_i_2game___i_i_i_2_c_the_scripts_8cpp" ],
    [ "CTheScripts.h", "de/d3a/plugin___i_i_i_2game___i_i_i_2_c_the_scripts_8h.html", "de/d3a/plugin___i_i_i_2game___i_i_i_2_c_the_scripts_8h" ],
    [ "CTimeCycle.cpp", "d7/dae/plugin___i_i_i_2game___i_i_i_2_c_time_cycle_8cpp.html", null ],
    [ "CTimeCycle.h", "db/d34/plugin___i_i_i_2game___i_i_i_2_c_time_cycle_8h.html", [
      [ "CTimeCycle", "dd/d04/class_c_time_cycle.html", null ]
    ] ],
    [ "CTimeModelInfo.cpp", "de/d7a/plugin___i_i_i_2game___i_i_i_2_c_time_model_info_8cpp.html", null ],
    [ "CTimeModelInfo.h", "d5/d66/plugin___i_i_i_2game___i_i_i_2_c_time_model_info_8h.html", "d5/d66/plugin___i_i_i_2game___i_i_i_2_c_time_model_info_8h" ],
    [ "CTimer.cpp", "d9/d33/plugin___i_i_i_2game___i_i_i_2_c_timer_8cpp.html", "d9/d33/plugin___i_i_i_2game___i_i_i_2_c_timer_8cpp" ],
    [ "CTimer.h", "d5/ddc/plugin___i_i_i_2game___i_i_i_2_c_timer_8h.html", "d5/ddc/plugin___i_i_i_2game___i_i_i_2_c_timer_8h" ],
    [ "CTrafficLights.cpp", "df/d01/plugin___i_i_i_2game___i_i_i_2_c_traffic_lights_8cpp.html", null ],
    [ "CTrafficLights.h", "d0/dcc/plugin___i_i_i_2game___i_i_i_2_c_traffic_lights_8h.html", [
      [ "CTrafficLights", "de/d36/class_c_traffic_lights.html", null ]
    ] ],
    [ "CTrain.cpp", "d7/dfa/plugin___i_i_i_2game___i_i_i_2_c_train_8cpp.html", "d7/dfa/plugin___i_i_i_2game___i_i_i_2_c_train_8cpp" ],
    [ "CTrain.h", "d3/dd3/plugin___i_i_i_2game___i_i_i_2_c_train_8h.html", "d3/dd3/plugin___i_i_i_2game___i_i_i_2_c_train_8h" ],
    [ "CTrainCamNode.h", "d0/d27/_c_train_cam_node_8h.html", "d0/d27/_c_train_cam_node_8h" ],
    [ "CTrainDoor.cpp", "de/d9b/_c_train_door_8cpp.html", null ],
    [ "CTrainDoor.h", "d2/d5f/_c_train_door_8h.html", "d2/d5f/_c_train_door_8h" ],
    [ "CTrainNode.cpp", "d4/d9b/plugin___i_i_i_2game___i_i_i_2_c_train_node_8cpp.html", null ],
    [ "CTrainNode.h", "da/dd5/plugin___i_i_i_2game___i_i_i_2_c_train_node_8h.html", [
      [ "CTrainNode", "d3/d34/class_c_train_node.html", "d3/d34/class_c_train_node" ]
    ] ],
    [ "cTransmission.cpp", "d7/d74/plugin___i_i_i_2game___i_i_i_2c_transmission_8cpp.html", null ],
    [ "cTransmission.h", "da/d60/plugin___i_i_i_2game___i_i_i_2c_transmission_8h.html", "da/d60/plugin___i_i_i_2game___i_i_i_2c_transmission_8h" ],
    [ "CTreadable.cpp", "d5/d43/plugin___i_i_i_2game___i_i_i_2_c_treadable_8cpp.html", null ],
    [ "CTreadable.h", "d8/d33/plugin___i_i_i_2game___i_i_i_2_c_treadable_8h.html", "d8/d33/plugin___i_i_i_2game___i_i_i_2_c_treadable_8h" ],
    [ "CTxdStore.cpp", "d3/d35/plugin___i_i_i_2game___i_i_i_2_c_txd_store_8cpp.html", "d3/d35/plugin___i_i_i_2game___i_i_i_2_c_txd_store_8cpp" ],
    [ "CTxdStore.h", "dd/d6d/plugin___i_i_i_2game___i_i_i_2_c_txd_store_8h.html", "dd/d6d/plugin___i_i_i_2game___i_i_i_2_c_txd_store_8h" ],
    [ "CUserDisplay.cpp", "de/dec/plugin___i_i_i_2game___i_i_i_2_c_user_display_8cpp.html", null ],
    [ "CUserDisplay.h", "d0/d44/plugin___i_i_i_2game___i_i_i_2_c_user_display_8h.html", [
      [ "CUserDisplay", "dc/da0/class_c_user_display.html", null ]
    ] ],
    [ "CVector.cpp", "de/d11/plugin___i_i_i_2game___i_i_i_2_c_vector_8cpp.html", null ],
    [ "CVector.h", "dd/d97/plugin___i_i_i_2game___i_i_i_2_c_vector_8h.html", "dd/d97/plugin___i_i_i_2game___i_i_i_2_c_vector_8h" ],
    [ "CVector2D.h", "da/ddd/plugin___i_i_i_2game___i_i_i_2_c_vector2_d_8h.html", [
      [ "CVector2D", "d8/db1/class_c_vector2_d.html", "d8/db1/class_c_vector2_d" ]
    ] ],
    [ "CVehicle.cpp", "db/d46/plugin___i_i_i_2game___i_i_i_2_c_vehicle_8cpp.html", "db/d46/plugin___i_i_i_2game___i_i_i_2_c_vehicle_8cpp" ],
    [ "CVehicle.h", "d6/d25/plugin___i_i_i_2game___i_i_i_2_c_vehicle_8h.html", "d6/d25/plugin___i_i_i_2game___i_i_i_2_c_vehicle_8h" ],
    [ "CVehicleModelInfo.cpp", "d0/db8/plugin___i_i_i_2game___i_i_i_2_c_vehicle_model_info_8cpp.html", "d0/db8/plugin___i_i_i_2game___i_i_i_2_c_vehicle_model_info_8cpp" ],
    [ "CVehicleModelInfo.h", "d0/d40/plugin___i_i_i_2game___i_i_i_2_c_vehicle_model_info_8h.html", "d0/d40/plugin___i_i_i_2game___i_i_i_2_c_vehicle_model_info_8h" ],
    [ "CWanted.cpp", "d0/d5f/plugin___i_i_i_2game___i_i_i_2_c_wanted_8cpp.html", null ],
    [ "CWanted.h", "da/d77/plugin___i_i_i_2game___i_i_i_2_c_wanted_8h.html", "da/d77/plugin___i_i_i_2game___i_i_i_2_c_wanted_8h" ],
    [ "CWaterCannons.cpp", "d2/d65/plugin___i_i_i_2game___i_i_i_2_c_water_cannons_8cpp.html", "d2/d65/plugin___i_i_i_2game___i_i_i_2_c_water_cannons_8cpp" ],
    [ "CWaterCannons.h", "d5/d93/plugin___i_i_i_2game___i_i_i_2_c_water_cannons_8h.html", "d5/d93/plugin___i_i_i_2game___i_i_i_2_c_water_cannons_8h" ],
    [ "CWeapon.cpp", "da/dfa/plugin___i_i_i_2game___i_i_i_2_c_weapon_8cpp.html", "da/dfa/plugin___i_i_i_2game___i_i_i_2_c_weapon_8cpp" ],
    [ "CWeapon.h", "d4/d37/plugin___i_i_i_2game___i_i_i_2_c_weapon_8h.html", "d4/d37/plugin___i_i_i_2game___i_i_i_2_c_weapon_8h" ],
    [ "CWeaponEffects.cpp", "d3/d84/plugin___i_i_i_2game___i_i_i_2_c_weapon_effects_8cpp.html", "d3/d84/plugin___i_i_i_2game___i_i_i_2_c_weapon_effects_8cpp" ],
    [ "CWeaponEffects.h", "d6/d6b/plugin___i_i_i_2game___i_i_i_2_c_weapon_effects_8h.html", "d6/d6b/plugin___i_i_i_2game___i_i_i_2_c_weapon_effects_8h" ],
    [ "CWeaponInfo.cpp", "d0/d78/plugin___i_i_i_2game___i_i_i_2_c_weapon_info_8cpp.html", "d0/d78/plugin___i_i_i_2game___i_i_i_2_c_weapon_info_8cpp" ],
    [ "CWeaponInfo.h", "de/dc4/plugin___i_i_i_2game___i_i_i_2_c_weapon_info_8h.html", "de/dc4/plugin___i_i_i_2game___i_i_i_2_c_weapon_info_8h" ],
    [ "CWeather.cpp", "df/df3/plugin___i_i_i_2game___i_i_i_2_c_weather_8cpp.html", "df/df3/plugin___i_i_i_2game___i_i_i_2_c_weather_8cpp" ],
    [ "CWeather.h", "dd/d70/plugin___i_i_i_2game___i_i_i_2_c_weather_8h.html", "dd/d70/plugin___i_i_i_2game___i_i_i_2_c_weather_8h" ],
    [ "CWheel.h", "d5/d28/plugin___i_i_i_2game___i_i_i_2_c_wheel_8h.html", "d5/d28/plugin___i_i_i_2game___i_i_i_2_c_wheel_8h" ],
    [ "CWorld.cpp", "d4/d5b/plugin___i_i_i_2game___i_i_i_2_c_world_8cpp.html", null ],
    [ "CWorld.h", "d5/d06/plugin___i_i_i_2game___i_i_i_2_c_world_8h.html", [
      [ "CWorld", "d0/da9/class_c_world.html", null ]
    ] ],
    [ "CXtraCompsModelInfo.cpp", "db/def/_c_xtra_comps_model_info_8cpp.html", null ],
    [ "CXtraCompsModelInfo.h", "de/d40/_c_xtra_comps_model_info_8h.html", "de/d40/_c_xtra_comps_model_info_8h" ],
    [ "CZone.cpp", "d9/d54/plugin___i_i_i_2game___i_i_i_2_c_zone_8cpp.html", null ],
    [ "CZone.h", "d1/d47/plugin___i_i_i_2game___i_i_i_2_c_zone_8h.html", "d1/d47/plugin___i_i_i_2game___i_i_i_2_c_zone_8h" ],
    [ "CZoneInfo.h", "df/d72/plugin___i_i_i_2game___i_i_i_2_c_zone_info_8h.html", "df/d72/plugin___i_i_i_2game___i_i_i_2_c_zone_info_8h" ],
    [ "eAnimations.h", "dd/de3/plugin___i_i_i_2game___i_i_i_2e_animations_8h.html", "dd/de3/plugin___i_i_i_2game___i_i_i_2e_animations_8h" ],
    [ "eBodyParts.h", "d4/dfa/e_body_parts_8h.html", "d4/dfa/e_body_parts_8h" ],
    [ "eBridgeState.h", "da/d23/e_bridge_state_8h.html", "da/d23/e_bridge_state_8h" ],
    [ "eCarMission.h", "df/da2/plugin___i_i_i_2game___i_i_i_2e_car_mission_8h.html", "df/da2/plugin___i_i_i_2game___i_i_i_2e_car_mission_8h" ],
    [ "eCopType.h", "d4/d72/plugin___i_i_i_2game___i_i_i_2e_cop_type_8h.html", "d4/d72/plugin___i_i_i_2game___i_i_i_2e_cop_type_8h" ],
    [ "eCoronaType.h", "d9/d1e/plugin___i_i_i_2game___i_i_i_2e_corona_type_8h.html", "d9/d1e/plugin___i_i_i_2game___i_i_i_2e_corona_type_8h" ],
    [ "eCrimeType.h", "d0/d08/plugin___i_i_i_2game___i_i_i_2e_crime_type_8h.html", "d0/d08/plugin___i_i_i_2game___i_i_i_2e_crime_type_8h" ],
    [ "eEntityStatus.h", "d8/d23/plugin___i_i_i_2game___i_i_i_2e_entity_status_8h.html", "d8/d23/plugin___i_i_i_2game___i_i_i_2e_entity_status_8h" ],
    [ "eEventEntity.h", "d5/d84/e_event_entity_8h.html", "d5/d84/e_event_entity_8h" ],
    [ "eEventStatus.h", "de/d39/e_event_status_8h.html", "de/d39/e_event_status_8h" ],
    [ "eEventType.h", "d0/d2b/plugin___i_i_i_2game___i_i_i_2e_event_type_8h.html", "d0/d2b/plugin___i_i_i_2game___i_i_i_2e_event_type_8h" ],
    [ "eExplosionType.h", "d2/d6f/plugin___i_i_i_2game___i_i_i_2e_explosion_type_8h.html", "d2/d6f/plugin___i_i_i_2game___i_i_i_2e_explosion_type_8h" ],
    [ "eFormation.h", "d0/d2c/plugin___i_i_i_2game___i_i_i_2e_formation_8h.html", "d0/d2c/plugin___i_i_i_2game___i_i_i_2e_formation_8h" ],
    [ "eGangType.h", "d8/d31/plugin___i_i_i_2game___i_i_i_2e_gang_type_8h.html", "d8/d31/plugin___i_i_i_2game___i_i_i_2e_gang_type_8h" ],
    [ "eGarageID.h", "dc/d40/e_garage_i_d_8h.html", "dc/d40/e_garage_i_d_8h" ],
    [ "eGarageState.h", "d0/d19/e_garage_state_8h.html", "d0/d19/e_garage_state_8h" ],
    [ "eGarageType.h", "dc/ddd/e_garage_type_8h.html", "dc/ddd/e_garage_type_8h" ],
    [ "eHandlingIndex.h", "d0/d9e/e_handling_index_8h.html", "d0/d9e/e_handling_index_8h" ],
    [ "eLevelName.h", "d1/d96/plugin___i_i_i_2game___i_i_i_2e_level_name_8h.html", "d1/d96/plugin___i_i_i_2game___i_i_i_2e_level_name_8h" ],
    [ "eObjective.h", "de/da7/plugin___i_i_i_2game___i_i_i_2e_objective_8h.html", "de/da7/plugin___i_i_i_2game___i_i_i_2e_objective_8h" ],
    [ "eParticleObjectType.h", "d9/da6/plugin___i_i_i_2game___i_i_i_2e_particle_object_type_8h.html", "d9/da6/plugin___i_i_i_2game___i_i_i_2e_particle_object_type_8h" ],
    [ "ePedModel.h", "d2/dc9/plugin___i_i_i_2game___i_i_i_2e_ped_model_8h.html", "d2/dc9/plugin___i_i_i_2game___i_i_i_2e_ped_model_8h" ],
    [ "ePedPieceTypes.h", "db/d6b/plugin___i_i_i_2game___i_i_i_2e_ped_piece_types_8h.html", "db/d6b/plugin___i_i_i_2game___i_i_i_2e_ped_piece_types_8h" ],
    [ "ePedStates.h", "da/d9a/plugin___i_i_i_2game___i_i_i_2e_ped_states_8h.html", "da/d9a/plugin___i_i_i_2game___i_i_i_2e_ped_states_8h" ],
    [ "ePedStats.h", "db/d98/plugin___i_i_i_2game___i_i_i_2e_ped_stats_8h.html", "db/d98/plugin___i_i_i_2game___i_i_i_2e_ped_stats_8h" ],
    [ "ePedType.h", "d8/d4d/plugin___i_i_i_2game___i_i_i_2e_ped_type_8h.html", "d8/d4d/plugin___i_i_i_2game___i_i_i_2e_ped_type_8h" ],
    [ "ePhoneState.h", "d1/dad/plugin___i_i_i_2game___i_i_i_2e_phone_state_8h.html", "d1/dad/plugin___i_i_i_2game___i_i_i_2e_phone_state_8h" ],
    [ "ePickupType.h", "dd/da5/plugin___i_i_i_2game___i_i_i_2e_pickup_type_8h.html", "dd/da5/plugin___i_i_i_2game___i_i_i_2e_pickup_type_8h" ],
    [ "eRadioStations.h", "d4/d37/plugin___i_i_i_2game___i_i_i_2e_radio_stations_8h.html", "d4/d37/plugin___i_i_i_2game___i_i_i_2e_radio_stations_8h" ],
    [ "eSceneCommands.h", "da/d1a/plugin___i_i_i_2game___i_i_i_2e_scene_commands_8h.html", "da/d1a/plugin___i_i_i_2game___i_i_i_2e_scene_commands_8h" ],
    [ "eScriptCommands.h", "dd/d5f/plugin___i_i_i_2game___i_i_i_2e_script_commands_8h.html", "dd/d5f/plugin___i_i_i_2game___i_i_i_2e_script_commands_8h" ],
    [ "eVehicleHandlingModelFlags.h", "d6/dd4/plugin___i_i_i_2game___i_i_i_2e_vehicle_handling_model_flags_8h.html", "d6/dd4/plugin___i_i_i_2game___i_i_i_2e_vehicle_handling_model_flags_8h" ],
    [ "eVehicleIndex.h", "d6/dd0/e_vehicle_index_8h.html", "d6/dd0/e_vehicle_index_8h" ],
    [ "eVehicleModel.h", "d7/d83/plugin___i_i_i_2game___i_i_i_2e_vehicle_model_8h.html", "d7/d83/plugin___i_i_i_2game___i_i_i_2e_vehicle_model_8h" ],
    [ "eWaitState.h", "dc/dd1/plugin___i_i_i_2game___i_i_i_2e_wait_state_8h.html", "dc/dd1/plugin___i_i_i_2game___i_i_i_2e_wait_state_8h" ],
    [ "eWeaponFire.h", "d1/d8c/plugin___i_i_i_2game___i_i_i_2e_weapon_fire_8h.html", "d1/d8c/plugin___i_i_i_2game___i_i_i_2e_weapon_fire_8h" ],
    [ "eWeaponModel.h", "d0/d3e/plugin___i_i_i_2game___i_i_i_2e_weapon_model_8h.html", "d0/d3e/plugin___i_i_i_2game___i_i_i_2e_weapon_model_8h" ],
    [ "eWeaponType.h", "da/d99/plugin___i_i_i_2game___i_i_i_2e_weapon_type_8h.html", "da/d99/plugin___i_i_i_2game___i_i_i_2e_weapon_type_8h" ],
    [ "eWeather.h", "d3/de2/plugin___i_i_i_2game___i_i_i_2e_weather_8h.html", "d3/de2/plugin___i_i_i_2game___i_i_i_2e_weather_8h" ],
    [ "eWheelModel.h", "d9/df6/e_wheel_model_8h.html", "d9/df6/e_wheel_model_8h" ],
    [ "LimbOrientation.h", "d1/d38/_limb_orientation_8h.html", "d1/d38/_limb_orientation_8h" ],
    [ "NodeName.cpp", "d3/d35/plugin___i_i_i_2game___i_i_i_2_node_name_8cpp.html", "d3/d35/plugin___i_i_i_2game___i_i_i_2_node_name_8cpp" ],
    [ "NodeName.h", "da/d73/plugin___i_i_i_2game___i_i_i_2_node_name_8h.html", "da/d73/plugin___i_i_i_2game___i_i_i_2_node_name_8h" ],
    [ "RenderBuffer.cpp", "d3/d0c/_render_buffer_8cpp.html", null ],
    [ "RenderBuffer.h", "da/d45/_render_buffer_8h.html", [
      [ "RenderBuffer", "dd/d51/class_render_buffer.html", null ]
    ] ],
    [ "RenderWare.cpp", "dd/d9a/plugin___i_i_i_2game___i_i_i_2_render_ware_8cpp.html", "dd/d9a/plugin___i_i_i_2game___i_i_i_2_render_ware_8cpp" ],
    [ "RenderWare.h", "d6/d9e/plugin___i_i_i_2game___i_i_i_2_render_ware_8h.html", "d6/d9e/plugin___i_i_i_2game___i_i_i_2_render_ware_8h" ],
    [ "RwObjectNameIdAssocation.h", "d8/dcb/plugin___i_i_i_2game___i_i_i_2_rw_object_name_id_assocation_8h.html", "d8/dcb/plugin___i_i_i_2game___i_i_i_2_rw_object_name_id_assocation_8h" ],
    [ "tColSurface.h", "d2/d22/t_col_surface_8h.html", "d2/d22/t_col_surface_8h" ],
    [ "tHandlingData.h", "dd/d4b/plugin___i_i_i_2game___i_i_i_2t_handling_data_8h.html", "dd/d4b/plugin___i_i_i_2game___i_i_i_2t_handling_data_8h" ],
    [ "tParticleSystemData.h", "d5/dc1/plugin___i_i_i_2game___i_i_i_2t_particle_system_data_8h.html", "d5/dc1/plugin___i_i_i_2game___i_i_i_2t_particle_system_data_8h" ],
    [ "tParticleType.h", "df/dda/plugin___i_i_i_2game___i_i_i_2t_particle_type_8h.html", "df/dda/plugin___i_i_i_2game___i_i_i_2t_particle_type_8h" ],
    [ "tTransmissionGear.h", "d9/d42/plugin___i_i_i_2game___i_i_i_2t_transmission_gear_8h.html", "d9/d42/plugin___i_i_i_2game___i_i_i_2t_transmission_gear_8h" ],
    [ "TxdDef.h", "d5/d4d/plugin___i_i_i_2game___i_i_i_2_txd_def_8h.html", "d5/d4d/plugin___i_i_i_2game___i_i_i_2_txd_def_8h" ]
];