var dir_e8c5de59e545fc1cd0ff64dd36905a12 =
[
    [ "meta", "dir_9cd1371cdf4e9f9419f107f40fe7d71c.html", "dir_9cd1371cdf4e9f9419f107f40fe7d71c" ],
    [ "rw", "dir_33fff2435d836303d9ff0788316b9af5.html", "dir_33fff2435d836303d9ff0788316b9af5" ],
    [ "AnimAssociationData.h", "dc/d5b/plugin__sa_2game__sa_2_anim_association_data_8h.html", "dc/d5b/plugin__sa_2game__sa_2_anim_association_data_8h" ],
    [ "AnimationId.h", "d9/d1b/_animation_id_8h.html", "d9/d1b/_animation_id_8h" ],
    [ "AnimBlendFrameData.h", "de/d42/plugin__sa_2game__sa_2_anim_blend_frame_data_8h.html", "de/d42/plugin__sa_2game__sa_2_anim_blend_frame_data_8h" ],
    [ "C2dEffect.h", "db/d01/_c2d_effect_8h.html", "db/d01/_c2d_effect_8h" ],
    [ "C3dMarker.cpp", "d5/dbe/plugin__sa_2game__sa_2_c3d_marker_8cpp.html", null ],
    [ "C3dMarker.h", "df/d94/plugin__sa_2game__sa_2_c3d_marker_8h.html", "df/d94/plugin__sa_2game__sa_2_c3d_marker_8h" ],
    [ "C3dMarkers.cpp", "d4/dcd/plugin__sa_2game__sa_2_c3d_markers_8cpp.html", "d4/dcd/plugin__sa_2game__sa_2_c3d_markers_8cpp" ],
    [ "C3dMarkers.h", "d2/d39/plugin__sa_2game__sa_2_c3d_markers_8h.html", "d2/d39/plugin__sa_2game__sa_2_c3d_markers_8h" ],
    [ "CAEAudioEntity.cpp", "d8/d00/_c_a_e_audio_entity_8cpp.html", null ],
    [ "CAEAudioEntity.h", "de/d2e/_c_a_e_audio_entity_8h.html", "de/d2e/_c_a_e_audio_entity_8h" ],
    [ "CAEExplosionAudioEntity.h", "d4/d05/_c_a_e_explosion_audio_entity_8h.html", "d4/d05/_c_a_e_explosion_audio_entity_8h" ],
    [ "CAEFireAudioEntity.h", "db/d58/_c_a_e_fire_audio_entity_8h.html", "db/d58/_c_a_e_fire_audio_entity_8h" ],
    [ "CAEPedAudioEntity.h", "df/d54/_c_a_e_ped_audio_entity_8h.html", "df/d54/_c_a_e_ped_audio_entity_8h" ],
    [ "CAEPedSpeechAudioEntity.h", "d9/d5a/_c_a_e_ped_speech_audio_entity_8h.html", "d9/d5a/_c_a_e_ped_speech_audio_entity_8h" ],
    [ "CAEPoliceScannerAudioEntity.h", "d1/d85/_c_a_e_police_scanner_audio_entity_8h.html", "d1/d85/_c_a_e_police_scanner_audio_entity_8h" ],
    [ "CAERadioTrackManager.cpp", "da/d1f/_c_a_e_radio_track_manager_8cpp.html", "da/d1f/_c_a_e_radio_track_manager_8cpp" ],
    [ "CAERadioTrackManager.h", "d3/dc6/_c_a_e_radio_track_manager_8h.html", "d3/dc6/_c_a_e_radio_track_manager_8h" ],
    [ "CAESound.cpp", "d6/d23/_c_a_e_sound_8cpp.html", null ],
    [ "CAESound.h", "d1/d5d/_c_a_e_sound_8h.html", "d1/d5d/_c_a_e_sound_8h" ],
    [ "CAETwinLoopSoundEntity.h", "d0/dda/_c_a_e_twin_loop_sound_entity_8h.html", "d0/dda/_c_a_e_twin_loop_sound_entity_8h" ],
    [ "CAEVehicleAudioEntity.cpp", "d4/d1e/_c_a_e_vehicle_audio_entity_8cpp.html", "d4/d1e/_c_a_e_vehicle_audio_entity_8cpp" ],
    [ "CAEVehicleAudioEntity.h", "d3/d0e/_c_a_e_vehicle_audio_entity_8h.html", "d3/d0e/_c_a_e_vehicle_audio_entity_8h" ],
    [ "CAEWeaponAudioEntity.cpp", "dc/dd1/_c_a_e_weapon_audio_entity_8cpp.html", null ],
    [ "CAEWeaponAudioEntity.h", "d1/db4/_c_a_e_weapon_audio_entity_8h.html", "d1/db4/_c_a_e_weapon_audio_entity_8h" ],
    [ "CAEWeatherAudioEntity.cpp", "da/d77/_c_a_e_weather_audio_entity_8cpp.html", null ],
    [ "CAEWeatherAudioEntity.h", "d7/d45/_c_a_e_weather_audio_entity_8h.html", "d7/d45/_c_a_e_weather_audio_entity_8h" ],
    [ "CAnimatedBuilding.cpp", "d1/db3/_c_animated_building_8cpp.html", null ],
    [ "CAnimatedBuilding.h", "d9/df3/_c_animated_building_8h.html", "d9/df3/_c_animated_building_8h" ],
    [ "CAnimationStyleDescriptor.h", "db/d07/plugin__sa_2game__sa_2_c_animation_style_descriptor_8h.html", "db/d07/plugin__sa_2game__sa_2_c_animation_style_descriptor_8h" ],
    [ "CAnimBlendAssocGroup.cpp", "d4/dab/_c_anim_blend_assoc_group_8cpp.html", null ],
    [ "CAnimBlendAssocGroup.h", "d7/d8a/plugin__sa_2game__sa_2_c_anim_blend_assoc_group_8h.html", "d7/d8a/plugin__sa_2game__sa_2_c_anim_blend_assoc_group_8h" ],
    [ "CAnimBlendAssociation.cpp", "d8/d1f/plugin__sa_2game__sa_2_c_anim_blend_association_8cpp.html", "d8/d1f/plugin__sa_2game__sa_2_c_anim_blend_association_8cpp" ],
    [ "CAnimBlendAssociation.h", "df/d76/plugin__sa_2game__sa_2_c_anim_blend_association_8h.html", "df/d76/plugin__sa_2game__sa_2_c_anim_blend_association_8h" ],
    [ "CAnimBlendClumpData.cpp", "d4/dad/plugin__sa_2game__sa_2_c_anim_blend_clump_data_8cpp.html", "d4/dad/plugin__sa_2game__sa_2_c_anim_blend_clump_data_8cpp" ],
    [ "CAnimBlendClumpData.h", "dc/dc6/plugin__sa_2game__sa_2_c_anim_blend_clump_data_8h.html", "dc/dc6/plugin__sa_2game__sa_2_c_anim_blend_clump_data_8h" ],
    [ "CAnimBlendHierarchy.cpp", "dd/d37/_c_anim_blend_hierarchy_8cpp.html", null ],
    [ "CAnimBlendHierarchy.h", "df/d67/_c_anim_blend_hierarchy_8h.html", "df/d67/_c_anim_blend_hierarchy_8h" ],
    [ "CAnimBlendNode.cpp", "d0/d9b/plugin__sa_2game__sa_2_c_anim_blend_node_8cpp.html", null ],
    [ "CAnimBlendNode.h", "d0/da5/plugin__sa_2game__sa_2_c_anim_blend_node_8h.html", "d0/da5/plugin__sa_2game__sa_2_c_anim_blend_node_8h" ],
    [ "CAnimBlendSequence.cpp", "d3/ddc/_c_anim_blend_sequence_8cpp.html", null ],
    [ "CAnimBlendSequence.h", "d3/daf/_c_anim_blend_sequence_8h.html", "d3/daf/_c_anim_blend_sequence_8h" ],
    [ "CAnimBlendStaticAssociation.cpp", "d0/d8c/_c_anim_blend_static_association_8cpp.html", "d0/d8c/_c_anim_blend_static_association_8cpp" ],
    [ "CAnimBlendStaticAssociation.h", "dd/dde/_c_anim_blend_static_association_8h.html", "dd/dde/_c_anim_blend_static_association_8h" ],
    [ "CAnimBlock.h", "df/d8d/plugin__sa_2game__sa_2_c_anim_block_8h.html", "df/d8d/plugin__sa_2game__sa_2_c_anim_block_8h" ],
    [ "CAnimManager.cpp", "dc/dff/plugin__sa_2game__sa_2_c_anim_manager_8cpp.html", null ],
    [ "CAnimManager.h", "d0/da2/plugin__sa_2game__sa_2_c_anim_manager_8h.html", [
      [ "CAnimManager", "db/d93/class_c_anim_manager.html", null ]
    ] ],
    [ "CAtomicModelInfo.cpp", "db/db1/_c_atomic_model_info_8cpp.html", null ],
    [ "CAtomicModelInfo.h", "dc/da7/_c_atomic_model_info_8h.html", "dc/da7/_c_atomic_model_info_8h" ],
    [ "CAttractorScanner.h", "de/d56/_c_attractor_scanner_8h.html", "de/d56/_c_attractor_scanner_8h" ],
    [ "CAutomobile.cpp", "de/d79/plugin__sa_2game__sa_2_c_automobile_8cpp.html", "de/d79/plugin__sa_2game__sa_2_c_automobile_8cpp" ],
    [ "CAutomobile.h", "da/d99/plugin__sa_2game__sa_2_c_automobile_8h.html", "da/d99/plugin__sa_2game__sa_2_c_automobile_8h" ],
    [ "CAutoPilot.h", "d3/d51/plugin__sa_2game__sa_2_c_auto_pilot_8h.html", "d3/d51/plugin__sa_2game__sa_2_c_auto_pilot_8h" ],
    [ "CBaseModelInfo.cpp", "d5/d3a/plugin__sa_2game__sa_2_c_base_model_info_8cpp.html", null ],
    [ "CBaseModelInfo.h", "dd/de5/plugin__sa_2game__sa_2_c_base_model_info_8h.html", "dd/de5/plugin__sa_2game__sa_2_c_base_model_info_8h" ],
    [ "CBike.cpp", "db/dac/plugin__sa_2game__sa_2_c_bike_8cpp.html", null ],
    [ "CBike.h", "da/dc4/plugin__sa_2game__sa_2_c_bike_8h.html", "da/dc4/plugin__sa_2game__sa_2_c_bike_8h" ],
    [ "CBirds.cpp", "d4/ded/_c_birds_8cpp.html", "d4/ded/_c_birds_8cpp" ],
    [ "CBirds.h", "d5/d8e/_c_birds_8h.html", "d5/d8e/_c_birds_8h" ],
    [ "CBmx.cpp", "d4/d8e/_c_bmx_8cpp.html", null ],
    [ "CBmx.h", "df/d77/_c_bmx_8h.html", "df/d77/_c_bmx_8h" ],
    [ "CBoat.cpp", "d7/d98/plugin__sa_2game__sa_2_c_boat_8cpp.html", "d7/d98/plugin__sa_2game__sa_2_c_boat_8cpp" ],
    [ "CBoat.h", "d0/dfb/plugin__sa_2game__sa_2_c_boat_8h.html", "d0/dfb/plugin__sa_2game__sa_2_c_boat_8h" ],
    [ "CBouncingPanel.cpp", "da/d79/_c_bouncing_panel_8cpp.html", null ],
    [ "CBouncingPanel.h", "d6/d3a/_c_bouncing_panel_8h.html", "d6/d3a/_c_bouncing_panel_8h" ],
    [ "CBoundingBox.cpp", "d7/d5f/_c_bounding_box_8cpp.html", null ],
    [ "CBoundingBox.h", "d3/d89/_c_bounding_box_8h.html", "d3/d89/_c_bounding_box_8h" ],
    [ "CBox.cpp", "d1/d5c/plugin__sa_2game__sa_2_c_box_8cpp.html", null ],
    [ "CBox.h", "da/d51/plugin__sa_2game__sa_2_c_box_8h.html", "da/d51/plugin__sa_2game__sa_2_c_box_8h" ],
    [ "CBrightLights.cpp", "db/d59/plugin__sa_2game__sa_2_c_bright_lights_8cpp.html", "db/d59/plugin__sa_2game__sa_2_c_bright_lights_8cpp" ],
    [ "CBrightLights.h", "d8/d04/plugin__sa_2game__sa_2_c_bright_lights_8h.html", "d8/d04/plugin__sa_2game__sa_2_c_bright_lights_8h" ],
    [ "CBuilding.cpp", "d9/d58/plugin__sa_2game__sa_2_c_building_8cpp.html", null ],
    [ "CBuilding.h", "d4/d88/plugin__sa_2game__sa_2_c_building_8h.html", "d4/d88/plugin__sa_2game__sa_2_c_building_8h" ],
    [ "CBulletInfo.cpp", "dc/d9f/plugin__sa_2game__sa_2_c_bullet_info_8cpp.html", "dc/d9f/plugin__sa_2game__sa_2_c_bullet_info_8cpp" ],
    [ "CBulletInfo.h", "de/d90/plugin__sa_2game__sa_2_c_bullet_info_8h.html", "de/d90/plugin__sa_2game__sa_2_c_bullet_info_8h" ],
    [ "CBulletTrace.cpp", "df/dfc/plugin__sa_2game__sa_2_c_bullet_trace_8cpp.html", null ],
    [ "CBulletTrace.h", "d2/dc6/plugin__sa_2game__sa_2_c_bullet_trace_8h.html", "d2/dc6/plugin__sa_2game__sa_2_c_bullet_trace_8h" ],
    [ "CBulletTraces.cpp", "dc/d81/plugin__sa_2game__sa_2_c_bullet_traces_8cpp.html", "dc/d81/plugin__sa_2game__sa_2_c_bullet_traces_8cpp" ],
    [ "CBulletTraces.h", "d5/d71/plugin__sa_2game__sa_2_c_bullet_traces_8h.html", "d5/d71/plugin__sa_2game__sa_2_c_bullet_traces_8h" ],
    [ "CCam.h", "d6/de6/plugin__sa_2game__sa_2_c_cam_8h.html", "d6/de6/plugin__sa_2game__sa_2_c_cam_8h" ],
    [ "CCamera.cpp", "da/dc3/plugin__sa_2game__sa_2_c_camera_8cpp.html", "da/dc3/plugin__sa_2game__sa_2_c_camera_8cpp" ],
    [ "CCamera.h", "db/d41/plugin__sa_2game__sa_2_c_camera_8h.html", "db/d41/plugin__sa_2game__sa_2_c_camera_8h" ],
    [ "CCamPathSplines.h", "d1/d95/_c_cam_path_splines_8h.html", "d1/d95/_c_cam_path_splines_8h" ],
    [ "CCarAI.cpp", "d4/db5/plugin__sa_2game__sa_2_c_car_a_i_8cpp.html", null ],
    [ "CCarAI.h", "d7/d1c/plugin__sa_2game__sa_2_c_car_a_i_8h.html", [
      [ "CCarAI", "df/dc9/class_c_car_a_i.html", null ]
    ] ],
    [ "CCarCtrl.cpp", "dc/d12/plugin__sa_2game__sa_2_c_car_ctrl_8cpp.html", null ],
    [ "CCarCtrl.h", "d5/dab/plugin__sa_2game__sa_2_c_car_ctrl_8h.html", [
      [ "CCarCtrl", "d3/d05/class_c_car_ctrl.html", null ]
    ] ],
    [ "CCarEnterExit.cpp", "d3/d05/_c_car_enter_exit_8cpp.html", "d3/d05/_c_car_enter_exit_8cpp" ],
    [ "CCarEnterExit.h", "dd/d45/_c_car_enter_exit_8h.html", [
      [ "CCarEnterExit", "df/da9/class_c_car_enter_exit.html", null ]
    ] ],
    [ "CCarGenerator.cpp", "d5/d2e/plugin__sa_2game__sa_2_c_car_generator_8cpp.html", "d5/d2e/plugin__sa_2game__sa_2_c_car_generator_8cpp" ],
    [ "CCarGenerator.h", "d4/d9e/plugin__sa_2game__sa_2_c_car_generator_8h.html", "d4/d9e/plugin__sa_2game__sa_2_c_car_generator_8h" ],
    [ "CCarPathLink.cpp", "db/d1a/_c_car_path_link_8cpp.html", "db/d1a/_c_car_path_link_8cpp" ],
    [ "CCarPathLink.h", "d4/dc4/_c_car_path_link_8h.html", "d4/dc4/_c_car_path_link_8h" ],
    [ "CCarPathLinkAddress.h", "d4/dd0/_c_car_path_link_address_8h.html", "d4/dd0/_c_car_path_link_address_8h" ],
    [ "CCheat.cpp", "d6/df8/plugin__sa_2game__sa_2_c_cheat_8cpp.html", "d6/df8/plugin__sa_2game__sa_2_c_cheat_8cpp" ],
    [ "CCheat.h", "d1/d35/plugin__sa_2game__sa_2_c_cheat_8h.html", [
      [ "CCheat", "d1/d35/class_c_cheat.html", null ]
    ] ],
    [ "CCheckpoint.cpp", "dc/dd8/_c_checkpoint_8cpp.html", null ],
    [ "CCheckpoint.h", "d5/df3/_c_checkpoint_8h.html", "d5/df3/_c_checkpoint_8h" ],
    [ "CCheckpoints.cpp", "db/d82/_c_checkpoints_8cpp.html", "db/d82/_c_checkpoints_8cpp" ],
    [ "CCheckpoints.h", "de/df2/_c_checkpoints_8h.html", "de/df2/_c_checkpoints_8h" ],
    [ "CCivilianPed.cpp", "dd/dc9/plugin__sa_2game__sa_2_c_civilian_ped_8cpp.html", null ],
    [ "CCivilianPed.h", "d0/d83/plugin__sa_2game__sa_2_c_civilian_ped_8h.html", "d0/d83/plugin__sa_2game__sa_2_c_civilian_ped_8h" ],
    [ "CClock.cpp", "db/d86/plugin__sa_2game__sa_2_c_clock_8cpp.html", "db/d86/plugin__sa_2game__sa_2_c_clock_8cpp" ],
    [ "CClock.h", "dd/da0/plugin__sa_2game__sa_2_c_clock_8h.html", [
      [ "CClock", "d6/d3e/class_c_clock.html", null ]
    ] ],
    [ "CClothes.cpp", "d9/df7/_c_clothes_8cpp.html", null ],
    [ "CClothes.h", "d5/d67/_c_clothes_8h.html", [
      [ "CClothes", "de/db2/class_c_clothes.html", null ]
    ] ],
    [ "CClothesBuilder.cpp", "d0/ddd/_c_clothes_builder_8cpp.html", null ],
    [ "CClothesBuilder.h", "d2/d4d/_c_clothes_builder_8h.html", [
      [ "CClothesBuilder", "d5/ddb/class_c_clothes_builder.html", "d5/ddb/class_c_clothes_builder" ]
    ] ],
    [ "CClouds.cpp", "db/d8d/plugin__sa_2game__sa_2_c_clouds_8cpp.html", "db/d8d/plugin__sa_2game__sa_2_c_clouds_8cpp" ],
    [ "CClouds.h", "d6/df4/plugin__sa_2game__sa_2_c_clouds_8h.html", "d6/df4/plugin__sa_2game__sa_2_c_clouds_8h" ],
    [ "CClumpModelInfo.cpp", "df/dcb/plugin__sa_2game__sa_2_c_clump_model_info_8cpp.html", null ],
    [ "CClumpModelInfo.h", "d8/de0/plugin__sa_2game__sa_2_c_clump_model_info_8h.html", "d8/de0/plugin__sa_2game__sa_2_c_clump_model_info_8h" ],
    [ "CColBox.cpp", "d9/d69/plugin__sa_2game__sa_2_c_col_box_8cpp.html", null ],
    [ "CColBox.h", "dd/d81/plugin__sa_2game__sa_2_c_col_box_8h.html", "dd/d81/plugin__sa_2game__sa_2_c_col_box_8h" ],
    [ "CColDisk.cpp", "de/d0c/_c_col_disk_8cpp.html", null ],
    [ "CColDisk.h", "d2/da3/_c_col_disk_8h.html", "d2/da3/_c_col_disk_8h" ],
    [ "CColLine.cpp", "d5/d6e/plugin__sa_2game__sa_2_c_col_line_8cpp.html", null ],
    [ "CColLine.h", "d0/d33/plugin__sa_2game__sa_2_c_col_line_8h.html", "d0/d33/plugin__sa_2game__sa_2_c_col_line_8h" ],
    [ "CCollision.cpp", "d6/d27/plugin__sa_2game__sa_2_c_collision_8cpp.html", "d6/d27/plugin__sa_2game__sa_2_c_collision_8cpp" ],
    [ "CCollision.h", "dd/daa/plugin__sa_2game__sa_2_c_collision_8h.html", "dd/daa/plugin__sa_2game__sa_2_c_collision_8h" ],
    [ "CCollisionData.cpp", "d9/da0/_c_collision_data_8cpp.html", null ],
    [ "CCollisionData.h", "d1/dc2/_c_collision_data_8h.html", "d1/dc2/_c_collision_data_8h" ],
    [ "CColModel.cpp", "d6/d16/plugin__sa_2game__sa_2_c_col_model_8cpp.html", null ],
    [ "CColModel.h", "da/d3d/plugin__sa_2game__sa_2_c_col_model_8h.html", "da/d3d/plugin__sa_2game__sa_2_c_col_model_8h" ],
    [ "CColourSet.cpp", "d2/d63/_c_colour_set_8cpp.html", null ],
    [ "CColourSet.h", "d6/df7/_c_colour_set_8h.html", "d6/df7/_c_colour_set_8h" ],
    [ "CColPoint.cpp", "d6/df9/plugin__sa_2game__sa_2_c_col_point_8cpp.html", null ],
    [ "CColPoint.h", "d4/d1b/plugin__sa_2game__sa_2_c_col_point_8h.html", "d4/d1b/plugin__sa_2game__sa_2_c_col_point_8h" ],
    [ "CColSphere.cpp", "d4/ded/plugin__sa_2game__sa_2_c_col_sphere_8cpp.html", null ],
    [ "CColSphere.h", "dc/d2a/plugin__sa_2game__sa_2_c_col_sphere_8h.html", "dc/d2a/plugin__sa_2game__sa_2_c_col_sphere_8h" ],
    [ "CColTriangle.cpp", "dd/d02/plugin__sa_2game__sa_2_c_col_triangle_8cpp.html", null ],
    [ "CColTriangle.h", "d2/df9/plugin__sa_2game__sa_2_c_col_triangle_8h.html", "d2/df9/plugin__sa_2game__sa_2_c_col_triangle_8h" ],
    [ "CColTrianglePlane.cpp", "dc/d76/plugin__sa_2game__sa_2_c_col_triangle_plane_8cpp.html", null ],
    [ "CColTrianglePlane.h", "da/de8/plugin__sa_2game__sa_2_c_col_triangle_plane_8h.html", "da/de8/plugin__sa_2game__sa_2_c_col_triangle_plane_8h" ],
    [ "CControllerConfigManager.cpp", "d2/d34/_c_controller_config_manager_8cpp.html", "d2/d34/_c_controller_config_manager_8cpp" ],
    [ "CControllerConfigManager.h", "d9/d53/_c_controller_config_manager_8h.html", "d9/d53/_c_controller_config_manager_8h" ],
    [ "CCopPed.cpp", "d7/d37/plugin__sa_2game__sa_2_c_cop_ped_8cpp.html", null ],
    [ "CCopPed.h", "d4/dab/plugin__sa_2game__sa_2_c_cop_ped_8h.html", "d4/dab/plugin__sa_2game__sa_2_c_cop_ped_8h" ],
    [ "CCoronas.cpp", "de/dd7/plugin__sa_2game__sa_2_c_coronas_8cpp.html", "de/dd7/plugin__sa_2game__sa_2_c_coronas_8cpp" ],
    [ "CCoronas.h", "df/d3a/plugin__sa_2game__sa_2_c_coronas_8h.html", "df/d3a/plugin__sa_2game__sa_2_c_coronas_8h" ],
    [ "CCover.cpp", "d5/df2/_c_cover_8cpp.html", "d5/df2/_c_cover_8cpp" ],
    [ "CCover.h", "dd/dc4/_c_cover_8h.html", [
      [ "CCover", "dc/d2d/class_c_cover.html", null ]
    ] ],
    [ "CCoverPoint.cpp", "d3/d33/_c_cover_point_8cpp.html", "d3/d33/_c_cover_point_8cpp" ],
    [ "CCoverPoint.h", "de/d0e/_c_cover_point_8h.html", "de/d0e/_c_cover_point_8h" ],
    [ "CCredits.cpp", "dd/dfc/_c_credits_8cpp.html", null ],
    [ "CCredits.h", "d8/dfb/_c_credits_8h.html", [
      [ "CCredits", "d2/d38/class_c_credits.html", null ]
    ] ],
    [ "CCreepingFire.cpp", "d7/d61/_c_creeping_fire_8cpp.html", null ],
    [ "CCreepingFire.h", "d4/d76/_c_creeping_fire_8h.html", [
      [ "CCreepingFire", "d0/dcf/class_c_creeping_fire.html", null ]
    ] ],
    [ "CCrimeBeingQd.h", "dd/d7a/_c_crime_being_qd_8h.html", "dd/d7a/_c_crime_being_qd_8h" ],
    [ "CCustomCarEnvMapPipeline.cpp", "dd/d28/_c_custom_car_env_map_pipeline_8cpp.html", null ],
    [ "CCustomCarEnvMapPipeline.h", "d0/d55/_c_custom_car_env_map_pipeline_8h.html", "d0/d55/_c_custom_car_env_map_pipeline_8h" ],
    [ "CCustomCarPlateMgr.cpp", "d9/de8/_c_custom_car_plate_mgr_8cpp.html", "d9/de8/_c_custom_car_plate_mgr_8cpp" ],
    [ "CCustomCarPlateMgr.h", "df/d49/_c_custom_car_plate_mgr_8h.html", "df/d49/_c_custom_car_plate_mgr_8h" ],
    [ "CCutsceneMgr.cpp", "d6/d5d/plugin__sa_2game__sa_2_c_cutscene_mgr_8cpp.html", "d6/d5d/plugin__sa_2game__sa_2_c_cutscene_mgr_8cpp" ],
    [ "CCutsceneMgr.h", "da/d82/plugin__sa_2game__sa_2_c_cutscene_mgr_8h.html", "da/d82/plugin__sa_2game__sa_2_c_cutscene_mgr_8h" ],
    [ "CCutsceneObject.cpp", "da/db3/plugin__sa_2game__sa_2_c_cutscene_object_8cpp.html", null ],
    [ "CCutsceneObject.h", "d9/d0e/plugin__sa_2game__sa_2_c_cutscene_object_8h.html", "d9/d0e/plugin__sa_2game__sa_2_c_cutscene_object_8h" ],
    [ "CDamageManager.cpp", "d2/dd9/plugin__sa_2game__sa_2_c_damage_manager_8cpp.html", null ],
    [ "CDamageManager.h", "db/d6f/plugin__sa_2game__sa_2_c_damage_manager_8h.html", "db/d6f/plugin__sa_2game__sa_2_c_damage_manager_8h" ],
    [ "CDarkel.cpp", "df/d8a/plugin__sa_2game__sa_2_c_darkel_8cpp.html", null ],
    [ "CDarkel.h", "d7/d64/plugin__sa_2game__sa_2_c_darkel_8h.html", [
      [ "CDarkel", "d3/dcc/class_c_darkel.html", null ]
    ] ],
    [ "CDate.cpp", "d0/db2/_c_date_8cpp.html", "d0/db2/_c_date_8cpp" ],
    [ "CDate.h", "d9/d29/_c_date_8h.html", "d9/d29/_c_date_8h" ],
    [ "CDecision.cpp", "d0/d40/_c_decision_8cpp.html", null ],
    [ "CDecision.h", "d8/dbb/_c_decision_8h.html", "d8/dbb/_c_decision_8h" ],
    [ "CDecisionMaker.h", "d9/d55/_c_decision_maker_8h.html", "d9/d55/_c_decision_maker_8h" ],
    [ "CDecisionSimple.cpp", "d8/dd9/_c_decision_simple_8cpp.html", null ],
    [ "CDecisionSimple.h", "db/d0b/_c_decision_simple_8h.html", "db/d0b/_c_decision_simple_8h" ],
    [ "CDirectory.cpp", "dc/dd3/plugin__sa_2game__sa_2_c_directory_8cpp.html", null ],
    [ "CDirectory.h", "d9/df2/plugin__sa_2game__sa_2_c_directory_8h.html", "d9/df2/plugin__sa_2game__sa_2_c_directory_8h" ],
    [ "CDoor.cpp", "da/d92/plugin__sa_2game__sa_2_c_door_8cpp.html", null ],
    [ "CDoor.h", "d9/dc0/plugin__sa_2game__sa_2_c_door_8h.html", "d9/dc0/plugin__sa_2game__sa_2_c_door_8h" ],
    [ "CDraw.cpp", "dc/d43/plugin__sa_2game__sa_2_c_draw_8cpp.html", null ],
    [ "CDraw.h", "d5/d9c/plugin__sa_2game__sa_2_c_draw_8h.html", [
      [ "CDraw", "d8/d22/class_c_draw.html", null ]
    ] ],
    [ "CDummy.cpp", "d9/d1b/plugin__sa_2game__sa_2_c_dummy_8cpp.html", null ],
    [ "CDummy.h", "d4/d1c/plugin__sa_2game__sa_2_c_dummy_8h.html", "d4/d1c/plugin__sa_2game__sa_2_c_dummy_8h" ],
    [ "CDummyObject.cpp", "dd/d20/plugin__sa_2game__sa_2_c_dummy_object_8cpp.html", null ],
    [ "CDummyObject.h", "d0/d3c/plugin__sa_2game__sa_2_c_dummy_object_8h.html", "d0/d3c/plugin__sa_2game__sa_2_c_dummy_object_8h" ],
    [ "CDummyPed.cpp", "df/dc8/_c_dummy_ped_8cpp.html", null ],
    [ "CDummyPed.h", "d2/d65/_c_dummy_ped_8h.html", "d2/d65/_c_dummy_ped_8h" ],
    [ "CEmergencyPed.cpp", "dc/d25/plugin__sa_2game__sa_2_c_emergency_ped_8cpp.html", null ],
    [ "CEmergencyPed.h", "d7/d28/plugin__sa_2game__sa_2_c_emergency_ped_8h.html", "d7/d28/plugin__sa_2game__sa_2_c_emergency_ped_8h" ],
    [ "CEntity.cpp", "d0/dcd/plugin__sa_2game__sa_2_c_entity_8cpp.html", "d0/dcd/plugin__sa_2game__sa_2_c_entity_8cpp" ],
    [ "CEntity.h", "da/d93/plugin__sa_2game__sa_2_c_entity_8h.html", "da/d93/plugin__sa_2game__sa_2_c_entity_8h" ],
    [ "CEntityScanner.h", "d6/d59/_c_entity_scanner_8h.html", "d6/d59/_c_entity_scanner_8h" ],
    [ "CEntryExit.cpp", "d0/d61/_c_entry_exit_8cpp.html", "d0/d61/_c_entry_exit_8cpp" ],
    [ "CEntryExit.h", "df/d87/_c_entry_exit_8h.html", "df/d87/_c_entry_exit_8h" ],
    [ "CEntryExitManager.cpp", "dc/dc0/_c_entry_exit_manager_8cpp.html", "dc/dc0/_c_entry_exit_manager_8cpp" ],
    [ "CEntryExitManager.h", "dc/d45/_c_entry_exit_manager_8h.html", [
      [ "CEntryExitManager", "db/d56/class_c_entry_exit_manager.html", null ]
    ] ],
    [ "CEventGroup.h", "dd/d55/_c_event_group_8h.html", "dd/d55/_c_event_group_8h" ],
    [ "CEventHandler.h", "d0/d96/_c_event_handler_8h.html", "d0/d96/_c_event_handler_8h" ],
    [ "CEventScanner.h", "de/d93/_c_event_scanner_8h.html", "de/d93/_c_event_scanner_8h" ],
    [ "CExplosion.cpp", "d7/d6f/plugin__sa_2game__sa_2_c_explosion_8cpp.html", "d7/d6f/plugin__sa_2game__sa_2_c_explosion_8cpp" ],
    [ "CExplosion.h", "d8/dde/plugin__sa_2game__sa_2_c_explosion_8h.html", "d8/dde/plugin__sa_2game__sa_2_c_explosion_8h" ],
    [ "CFileCarGenerator.h", "d6/d03/_c_file_car_generator_8h.html", "d6/d03/_c_file_car_generator_8h" ],
    [ "CFileLoader.cpp", "d8/dcb/plugin__sa_2game__sa_2_c_file_loader_8cpp.html", "d8/dcb/plugin__sa_2game__sa_2_c_file_loader_8cpp" ],
    [ "CFileLoader.h", "da/da9/plugin__sa_2game__sa_2_c_file_loader_8h.html", "da/da9/plugin__sa_2game__sa_2_c_file_loader_8h" ],
    [ "CFileMgr.cpp", "d9/d50/plugin__sa_2game__sa_2_c_file_mgr_8cpp.html", null ],
    [ "CFileMgr.h", "d4/d75/plugin__sa_2game__sa_2_c_file_mgr_8h.html", "d4/d75/plugin__sa_2game__sa_2_c_file_mgr_8h" ],
    [ "CFileObjectInstance.h", "d1/d48/_c_file_object_instance_8h.html", "d1/d48/_c_file_object_instance_8h" ],
    [ "CFire.cpp", "da/d14/plugin__sa_2game__sa_2_c_fire_8cpp.html", null ],
    [ "CFire.h", "d0/de6/plugin__sa_2game__sa_2_c_fire_8h.html", "d0/de6/plugin__sa_2game__sa_2_c_fire_8h" ],
    [ "CFireManager.cpp", "d6/db8/plugin__sa_2game__sa_2_c_fire_manager_8cpp.html", "d6/db8/plugin__sa_2game__sa_2_c_fire_manager_8cpp" ],
    [ "CFireManager.h", "d3/d80/plugin__sa_2game__sa_2_c_fire_manager_8h.html", "d3/d80/plugin__sa_2game__sa_2_c_fire_manager_8h" ],
    [ "CFont.cpp", "d2/d70/plugin__sa_2game__sa_2_c_font_8cpp.html", "d2/d70/plugin__sa_2game__sa_2_c_font_8cpp" ],
    [ "CFont.h", "dd/dda/plugin__sa_2game__sa_2_c_font_8h.html", "dd/dda/plugin__sa_2game__sa_2_c_font_8h" ],
    [ "CForbiddenArea.h", "d0/d90/_c_forbidden_area_8h.html", "d0/d90/_c_forbidden_area_8h" ],
    [ "CFormation.cpp", "da/d36/_c_formation_8cpp.html", "da/d36/_c_formation_8cpp" ],
    [ "CFormation.h", "d5/dd1/_c_formation_8h.html", [
      [ "CFormation", "d6/d81/class_c_formation.html", null ]
    ] ],
    [ "CGame.cpp", "d1/ded/plugin__sa_2game__sa_2_c_game_8cpp.html", "d1/ded/plugin__sa_2game__sa_2_c_game_8cpp" ],
    [ "CGame.h", "d9/df8/plugin__sa_2game__sa_2_c_game_8h.html", "d9/df8/plugin__sa_2game__sa_2_c_game_8h" ],
    [ "CGameLogic.cpp", "dc/df3/plugin__sa_2game__sa_2_c_game_logic_8cpp.html", null ],
    [ "CGameLogic.h", "df/d75/plugin__sa_2game__sa_2_c_game_logic_8h.html", [
      [ "CGameLogic", "d6/db2/class_c_game_logic.html", null ]
    ] ],
    [ "CGamma.cpp", "db/d00/_c_gamma_8cpp.html", "db/d00/_c_gamma_8cpp" ],
    [ "CGamma.h", "d4/d15/_c_gamma_8h.html", "d4/d15/_c_gamma_8h" ],
    [ "CGangInfo.cpp", "df/dc7/plugin__sa_2game__sa_2_c_gang_info_8cpp.html", "df/dc7/plugin__sa_2game__sa_2_c_gang_info_8cpp" ],
    [ "CGangInfo.h", "d2/d2c/plugin__sa_2game__sa_2_c_gang_info_8h.html", "d2/d2c/plugin__sa_2game__sa_2_c_gang_info_8h" ],
    [ "CGangs.cpp", "d0/d80/plugin__sa_2game__sa_2_c_gangs_8cpp.html", "d0/d80/plugin__sa_2game__sa_2_c_gangs_8cpp" ],
    [ "CGangs.h", "d7/dd8/plugin__sa_2game__sa_2_c_gangs_8h.html", [
      [ "CGangs", "de/d13/class_c_gangs.html", "de/d13/class_c_gangs" ]
    ] ],
    [ "CGangWars.cpp", "d9/da6/_c_gang_wars_8cpp.html", "d9/da6/_c_gang_wars_8cpp" ],
    [ "CGangWars.h", "d0/d20/_c_gang_wars_8h.html", "d0/d20/_c_gang_wars_8h" ],
    [ "CGangWarsSaveStructure.cpp", "d3/da8/_c_gang_wars_save_structure_8cpp.html", "d3/da8/_c_gang_wars_save_structure_8cpp" ],
    [ "CGangWarsSaveStructure.h", "d3/de0/_c_gang_wars_save_structure_8h.html", "d3/de0/_c_gang_wars_save_structure_8h" ],
    [ "CGarages.cpp", "d9/db8/plugin__sa_2game__sa_2_c_garages_8cpp.html", null ],
    [ "CGarages.h", "de/da7/plugin__sa_2game__sa_2_c_garages_8h.html", [
      [ "CGarages", "d6/d1c/class_c_garages.html", null ]
    ] ],
    [ "CGeneral.cpp", "d7/d5b/plugin__sa_2game__sa_2_c_general_8cpp.html", null ],
    [ "CGeneral.h", "d4/ddd/plugin__sa_2game__sa_2_c_general_8h.html", [
      [ "CGeneral", "db/d2a/class_c_general.html", null ]
    ] ],
    [ "CGenericGameStorage.cpp", "d2/d5d/_c_generic_game_storage_8cpp.html", "d2/d5d/_c_generic_game_storage_8cpp" ],
    [ "CGenericGameStorage.h", "da/dfb/_c_generic_game_storage_8h.html", "da/dfb/_c_generic_game_storage_8h" ],
    [ "CGridRef.cpp", "d6/deb/_c_grid_ref_8cpp.html", "d6/deb/_c_grid_ref_8cpp" ],
    [ "CGridRef.h", "d3/de1/_c_grid_ref_8h.html", "d3/de1/_c_grid_ref_8h" ],
    [ "cHandlingDataMgr.cpp", "d8/df4/plugin__sa_2game__sa_2c_handling_data_mgr_8cpp.html", "d8/df4/plugin__sa_2game__sa_2c_handling_data_mgr_8cpp" ],
    [ "cHandlingDataMgr.h", "df/d47/plugin__sa_2game__sa_2c_handling_data_mgr_8h.html", "df/d47/plugin__sa_2game__sa_2c_handling_data_mgr_8h" ],
    [ "CHandObject.cpp", "dd/dfa/_c_hand_object_8cpp.html", null ],
    [ "CHandObject.h", "d9/d2a/_c_hand_object_8h.html", "d9/d2a/_c_hand_object_8h" ],
    [ "CHeli.cpp", "d5/d68/plugin__sa_2game__sa_2_c_heli_8cpp.html", null ],
    [ "CHeli.h", "d2/dfd/plugin__sa_2game__sa_2_c_heli_8h.html", "d2/dfd/plugin__sa_2game__sa_2_c_heli_8h" ],
    [ "CHud.cpp", "da/dc3/plugin__sa_2game__sa_2_c_hud_8cpp.html", "da/dc3/plugin__sa_2game__sa_2_c_hud_8cpp" ],
    [ "CHud.h", "dd/de2/plugin__sa_2game__sa_2_c_hud_8h.html", "dd/de2/plugin__sa_2game__sa_2_c_hud_8h" ],
    [ "CHudColours.cpp", "d3/dff/_c_hud_colours_8cpp.html", "d3/dff/_c_hud_colours_8cpp" ],
    [ "CHudColours.h", "de/d40/_c_hud_colours_8h.html", "de/d40/_c_hud_colours_8h" ],
    [ "CIniFile.cpp", "dc/dfa/plugin__sa_2game__sa_2_c_ini_file_8cpp.html", null ],
    [ "CIniFile.h", "d3/d74/plugin__sa_2game__sa_2_c_ini_file_8h.html", [
      [ "CIniFile", "d4/d65/class_c_ini_file.html", null ]
    ] ],
    [ "CIplStore.cpp", "d6/d05/_c_ipl_store_8cpp.html", "d6/d05/_c_ipl_store_8cpp" ],
    [ "CIplStore.h", "d8/d0d/_c_ipl_store_8h.html", "d8/d0d/_c_ipl_store_8h" ],
    [ "CKeyGen.cpp", "d7/dbf/_c_key_gen_8cpp.html", null ],
    [ "CKeyGen.h", "d3/d42/_c_key_gen_8h.html", [
      [ "CKeyGen", "da/d1b/class_c_key_gen.html", null ]
    ] ],
    [ "CLink.h", "df/d9e/plugin__sa_2game__sa_2_c_link_8h.html", "df/d9e/plugin__sa_2game__sa_2_c_link_8h" ],
    [ "CLinkList.h", "d4/d45/plugin__sa_2game__sa_2_c_link_list_8h.html", "d4/d45/plugin__sa_2game__sa_2_c_link_list_8h" ],
    [ "CLoadedCarGroup.cpp", "d9/de2/_c_loaded_car_group_8cpp.html", null ],
    [ "CLoadedCarGroup.h", "d7/d33/_c_loaded_car_group_8h.html", "d7/d33/_c_loaded_car_group_8h" ],
    [ "CLoadingScreen.cpp", "d4/d6d/_c_loading_screen_8cpp.html", null ],
    [ "CLoadingScreen.h", "d7/d29/_c_loading_screen_8h.html", [
      [ "CLoadingScreen", "da/d0c/class_c_loading_screen.html", null ]
    ] ],
    [ "CLocalisation.cpp", "d5/d08/_c_localisation_8cpp.html", null ],
    [ "CLocalisation.h", "db/d0a/_c_localisation_8h.html", [
      [ "CLocalisation", "d2/d2e/class_c_localisation.html", null ]
    ] ],
    [ "CMatrix.cpp", "df/dac/plugin__sa_2game__sa_2_c_matrix_8cpp.html", "df/dac/plugin__sa_2game__sa_2_c_matrix_8cpp" ],
    [ "CMatrix.h", "df/d5a/plugin__sa_2game__sa_2_c_matrix_8h.html", "df/d5a/plugin__sa_2game__sa_2_c_matrix_8h" ],
    [ "CMatrixLink.cpp", "d7/d9a/_c_matrix_link_8cpp.html", "d7/d9a/_c_matrix_link_8cpp" ],
    [ "CMatrixLink.h", "d4/d8a/_c_matrix_link_8h.html", "d4/d8a/_c_matrix_link_8h" ],
    [ "CMenuManager.cpp", "da/d4f/plugin__sa_2game__sa_2_c_menu_manager_8cpp.html", "da/d4f/plugin__sa_2game__sa_2_c_menu_manager_8cpp" ],
    [ "CMenuManager.h", "d2/d05/plugin__sa_2game__sa_2_c_menu_manager_8h.html", "d2/d05/plugin__sa_2game__sa_2_c_menu_manager_8h" ],
    [ "CMenuSystem.cpp", "df/d96/_c_menu_system_8cpp.html", "df/d96/_c_menu_system_8cpp" ],
    [ "CMenuSystem.h", "d5/d55/_c_menu_system_8h.html", "d5/d55/_c_menu_system_8h" ],
    [ "CMessages.cpp", "d5/d7a/plugin__sa_2game__sa_2_c_messages_8cpp.html", "d5/d7a/plugin__sa_2game__sa_2_c_messages_8cpp" ],
    [ "CMessages.h", "d3/d0c/plugin__sa_2game__sa_2_c_messages_8h.html", "d3/d0c/plugin__sa_2game__sa_2_c_messages_8h" ],
    [ "CMirrors.cpp", "d3/df6/_c_mirrors_8cpp.html", "d3/df6/_c_mirrors_8cpp" ],
    [ "CMirrors.h", "d1/d04/_c_mirrors_8h.html", "d1/d04/_c_mirrors_8h" ],
    [ "CMissionCleanup.cpp", "d1/df8/_c_mission_cleanup_8cpp.html", null ],
    [ "CMissionCleanup.h", "dd/d7d/_c_mission_cleanup_8h.html", "dd/d7d/_c_mission_cleanup_8h" ],
    [ "CModelInfo.cpp", "da/d44/plugin__sa_2game__sa_2_c_model_info_8cpp.html", null ],
    [ "CModelInfo.h", "d5/d5d/plugin__sa_2game__sa_2_c_model_info_8h.html", [
      [ "CModelInfo", "dd/df3/class_c_model_info.html", null ]
    ] ],
    [ "CModelInfoAccelerator.cpp", "d7/d44/_c_model_info_accelerator_8cpp.html", null ],
    [ "CModelInfoAccelerator.h", "d4/d04/_c_model_info_accelerator_8h.html", "d4/d04/_c_model_info_accelerator_8h" ],
    [ "CMonsterTruck.cpp", "da/d78/_c_monster_truck_8cpp.html", "da/d78/_c_monster_truck_8cpp" ],
    [ "CMonsterTruck.h", "d9/dfd/_c_monster_truck_8h.html", "d9/dfd/_c_monster_truck_8h" ],
    [ "CMotionBlurStreaks.cpp", "de/de0/plugin__sa_2game__sa_2_c_motion_blur_streaks_8cpp.html", "de/de0/plugin__sa_2game__sa_2_c_motion_blur_streaks_8cpp" ],
    [ "CMotionBlurStreaks.h", "da/d19/plugin__sa_2game__sa_2_c_motion_blur_streaks_8h.html", "da/d19/plugin__sa_2game__sa_2_c_motion_blur_streaks_8h" ],
    [ "CNodeAddress.h", "d3/dde/plugin__sa_2game__sa_2_c_node_address_8h.html", "d3/dde/plugin__sa_2game__sa_2_c_node_address_8h" ],
    [ "CObject.cpp", "d2/db1/plugin__sa_2game__sa_2_c_object_8cpp.html", "d2/db1/plugin__sa_2game__sa_2_c_object_8cpp" ],
    [ "CObject.h", "d0/da1/plugin__sa_2game__sa_2_c_object_8h.html", "d0/da1/plugin__sa_2game__sa_2_c_object_8h" ],
    [ "CObjectInfo.h", "d3/d5c/_c_object_info_8h.html", "d3/d5c/_c_object_info_8h" ],
    [ "COctTree.cpp", "d4/d8e/_c_oct_tree_8cpp.html", "d4/d8e/_c_oct_tree_8cpp" ],
    [ "COctTree.h", "d8/d64/_c_oct_tree_8h.html", "d8/d64/_c_oct_tree_8h" ],
    [ "COctTreeBase.cpp", "da/d0d/_c_oct_tree_base_8cpp.html", null ],
    [ "COctTreeBase.h", "d8/d58/_c_oct_tree_base_8h.html", "d8/d58/_c_oct_tree_base_8h" ],
    [ "common.cpp", "d7/da7/plugin__sa_2game__sa_2common_8cpp.html", "d7/da7/plugin__sa_2game__sa_2common_8cpp" ],
    [ "common.h", "da/dc3/plugin__sa_2game__sa_2common_8h.html", "da/dc3/plugin__sa_2game__sa_2common_8h" ],
    [ "COnscreenCounterEntry.cpp", "dc/d91/_c_onscreen_counter_entry_8cpp.html", "dc/d91/_c_onscreen_counter_entry_8cpp" ],
    [ "COnscreenCounterEntry.h", "d1/d53/_c_onscreen_counter_entry_8h.html", "d1/d53/_c_onscreen_counter_entry_8h" ],
    [ "COnscreenTimer.cpp", "d0/d57/plugin__sa_2game__sa_2_c_onscreen_timer_8cpp.html", "d0/d57/plugin__sa_2game__sa_2_c_onscreen_timer_8cpp" ],
    [ "COnscreenTimer.h", "d7/d9e/plugin__sa_2game__sa_2_c_onscreen_timer_8h.html", "d7/d9e/plugin__sa_2game__sa_2_c_onscreen_timer_8h" ],
    [ "COnscreenTimerEntry.cpp", "d7/d4d/plugin__sa_2game__sa_2_c_onscreen_timer_entry_8cpp.html", "d7/d4d/plugin__sa_2game__sa_2_c_onscreen_timer_entry_8cpp" ],
    [ "COnscreenTimerEntry.h", "df/d73/plugin__sa_2game__sa_2_c_onscreen_timer_entry_8h.html", "df/d73/plugin__sa_2game__sa_2_c_onscreen_timer_entry_8h" ],
    [ "CPad.cpp", "d0/d4d/plugin__sa_2game__sa_2_c_pad_8cpp.html", null ],
    [ "CPad.h", "d3/d1a/plugin__sa_2game__sa_2_c_pad_8h.html", "d3/d1a/plugin__sa_2game__sa_2_c_pad_8h" ],
    [ "CPathFind.cpp", "d9/d29/plugin__sa_2game__sa_2_c_path_find_8cpp.html", "d9/d29/plugin__sa_2game__sa_2_c_path_find_8cpp" ],
    [ "CPathFind.h", "d7/de0/plugin__sa_2game__sa_2_c_path_find_8h.html", "d7/de0/plugin__sa_2game__sa_2_c_path_find_8h" ],
    [ "CPathIntersectionInfo.h", "d1/d4a/_c_path_intersection_info_8h.html", "d1/d4a/_c_path_intersection_info_8h" ],
    [ "CPathNode.cpp", "d8/def/plugin__sa_2game__sa_2_c_path_node_8cpp.html", "d8/def/plugin__sa_2game__sa_2_c_path_node_8cpp" ],
    [ "CPathNode.h", "d7/d3f/plugin__sa_2game__sa_2_c_path_node_8h.html", "d7/d3f/plugin__sa_2game__sa_2_c_path_node_8h" ],
    [ "CPed.cpp", "dd/d0e/plugin__sa_2game__sa_2_c_ped_8cpp.html", "dd/d0e/plugin__sa_2game__sa_2_c_ped_8cpp" ],
    [ "CPed.h", "da/d09/plugin__sa_2game__sa_2_c_ped_8h.html", "da/d09/plugin__sa_2game__sa_2_c_ped_8h" ],
    [ "CPedAcquaintance.h", "db/ddc/_c_ped_acquaintance_8h.html", "db/ddc/_c_ped_acquaintance_8h" ],
    [ "CPedClothesDesc.cpp", "de/dc4/_c_ped_clothes_desc_8cpp.html", null ],
    [ "CPedClothesDesc.h", "d1/dd2/_c_ped_clothes_desc_8h.html", "d1/dd2/_c_ped_clothes_desc_8h" ],
    [ "CPedGroup.cpp", "df/d37/_c_ped_group_8cpp.html", "df/d37/_c_ped_group_8cpp" ],
    [ "CPedGroup.h", "d7/da5/_c_ped_group_8h.html", "d7/da5/_c_ped_group_8h" ],
    [ "CPedGroupIntelligence.cpp", "d4/dc4/_c_ped_group_intelligence_8cpp.html", "d4/dc4/_c_ped_group_intelligence_8cpp" ],
    [ "CPedGroupIntelligence.h", "d3/d31/_c_ped_group_intelligence_8h.html", "d3/d31/_c_ped_group_intelligence_8h" ],
    [ "CPedGroupMembership.cpp", "de/d9c/_c_ped_group_membership_8cpp.html", "de/d9c/_c_ped_group_membership_8cpp" ],
    [ "CPedGroupMembership.h", "d5/d46/_c_ped_group_membership_8h.html", "d5/d46/_c_ped_group_membership_8h" ],
    [ "CPedGroupPlacer.cpp", "de/dcd/_c_ped_group_placer_8cpp.html", "de/dcd/_c_ped_group_placer_8cpp" ],
    [ "CPedGroupPlacer.h", "d8/df7/_c_ped_group_placer_8h.html", "d8/df7/_c_ped_group_placer_8h" ],
    [ "CPedGroups.cpp", "d5/d88/_c_ped_groups_8cpp.html", "d5/d88/_c_ped_groups_8cpp" ],
    [ "CPedGroups.h", "d0/dc1/_c_ped_groups_8h.html", [
      [ "CPedGroups", "df/dba/class_c_ped_groups.html", null ]
    ] ],
    [ "CPedIK.cpp", "d6/d4d/plugin__sa_2game__sa_2_c_ped_i_k_8cpp.html", null ],
    [ "CPedIK.h", "d0/d30/plugin__sa_2game__sa_2_c_ped_i_k_8h.html", "d0/d30/plugin__sa_2game__sa_2_c_ped_i_k_8h" ],
    [ "CPedIntelligence.cpp", "d1/d57/_c_ped_intelligence_8cpp.html", null ],
    [ "CPedIntelligence.h", "dc/dcf/_c_ped_intelligence_8h.html", "dc/dcf/_c_ped_intelligence_8h" ],
    [ "CPedList.cpp", "dd/d5a/_c_ped_list_8cpp.html", "dd/d5a/_c_ped_list_8cpp" ],
    [ "CPedList.h", "df/df0/_c_ped_list_8h.html", "df/df0/_c_ped_list_8h" ],
    [ "CPedModelInfo.cpp", "d7/dd9/plugin__sa_2game__sa_2_c_ped_model_info_8cpp.html", null ],
    [ "CPedModelInfo.h", "d8/d33/plugin__sa_2game__sa_2_c_ped_model_info_8h.html", "d8/d33/plugin__sa_2game__sa_2_c_ped_model_info_8h" ],
    [ "CPedPlacement.cpp", "d7/dc5/plugin__sa_2game__sa_2_c_ped_placement_8cpp.html", "d7/dc5/plugin__sa_2game__sa_2_c_ped_placement_8cpp" ],
    [ "CPedPlacement.h", "d9/dde/plugin__sa_2game__sa_2_c_ped_placement_8h.html", [
      [ "CPedPlacement", "de/d1d/class_c_ped_placement.html", null ]
    ] ],
    [ "CPedTaskPair.cpp", "df/d01/_c_ped_task_pair_8cpp.html", "df/d01/_c_ped_task_pair_8cpp" ],
    [ "CPedTaskPair.h", "d2/dba/_c_ped_task_pair_8h.html", "d2/dba/_c_ped_task_pair_8h" ],
    [ "CPhysical.cpp", "d7/d08/plugin__sa_2game__sa_2_c_physical_8cpp.html", null ],
    [ "CPhysical.h", "d6/dd0/plugin__sa_2game__sa_2_c_physical_8h.html", "d6/dd0/plugin__sa_2game__sa_2_c_physical_8h" ],
    [ "CPickup.cpp", "d5/d23/_c_pickup_8cpp.html", null ],
    [ "CPickup.h", "d6/d6b/_c_pickup_8h.html", "d6/d6b/_c_pickup_8h" ],
    [ "CPickups.cpp", "de/d0b/plugin__sa_2game__sa_2_c_pickups_8cpp.html", "de/d0b/plugin__sa_2game__sa_2_c_pickups_8cpp" ],
    [ "CPickups.h", "d2/de0/plugin__sa_2game__sa_2_c_pickups_8h.html", "d2/de0/plugin__sa_2game__sa_2_c_pickups_8h" ],
    [ "CPlaceable.cpp", "d1/d3c/plugin__sa_2game__sa_2_c_placeable_8cpp.html", null ],
    [ "CPlaceable.h", "d0/ded/plugin__sa_2game__sa_2_c_placeable_8h.html", "d0/ded/plugin__sa_2game__sa_2_c_placeable_8h" ],
    [ "CPlane.cpp", "d3/dae/plugin__sa_2game__sa_2_c_plane_8cpp.html", "d3/dae/plugin__sa_2game__sa_2_c_plane_8cpp" ],
    [ "CPlane.h", "d0/ddd/plugin__sa_2game__sa_2_c_plane_8h.html", "d0/ddd/plugin__sa_2game__sa_2_c_plane_8h" ],
    [ "CPlaneTrail.cpp", "d7/dfd/_c_plane_trail_8cpp.html", null ],
    [ "CPlaneTrail.h", "dd/dbf/_c_plane_trail_8h.html", "dd/dbf/_c_plane_trail_8h" ],
    [ "CPlaneTrails.cpp", "d8/d5b/_c_plane_trails_8cpp.html", null ],
    [ "CPlaneTrails.h", "d3/dd6/_c_plane_trails_8h.html", "d3/dd6/_c_plane_trails_8h" ],
    [ "CPlayerData.h", "de/da1/_c_player_data_8h.html", "de/da1/_c_player_data_8h" ],
    [ "CPlayerInfo.cpp", "dd/d09/plugin__sa_2game__sa_2_c_player_info_8cpp.html", null ],
    [ "CPlayerInfo.h", "d1/d2b/plugin__sa_2game__sa_2_c_player_info_8h.html", "d1/d2b/plugin__sa_2game__sa_2_c_player_info_8h" ],
    [ "CPlayerPed.cpp", "d2/d9c/plugin__sa_2game__sa_2_c_player_ped_8cpp.html", "d2/d9c/plugin__sa_2game__sa_2_c_player_ped_8cpp" ],
    [ "CPlayerPed.h", "d9/dd5/plugin__sa_2game__sa_2_c_player_ped_8h.html", "d9/dd5/plugin__sa_2game__sa_2_c_player_ped_8h" ],
    [ "CPointLights.cpp", "da/d94/plugin__sa_2game__sa_2_c_point_lights_8cpp.html", "da/d94/plugin__sa_2game__sa_2_c_point_lights_8cpp" ],
    [ "CPointLights.h", "dc/d5e/plugin__sa_2game__sa_2_c_point_lights_8h.html", "dc/d5e/plugin__sa_2game__sa_2_c_point_lights_8h" ],
    [ "CPointList.cpp", "d1/d00/_c_point_list_8cpp.html", "d1/d00/_c_point_list_8cpp" ],
    [ "CPointList.h", "de/d77/_c_point_list_8h.html", "de/d77/_c_point_list_8h" ],
    [ "CPolyBunch.cpp", "d6/db9/_c_poly_bunch_8cpp.html", null ],
    [ "CPolyBunch.h", "dc/def/_c_poly_bunch_8h.html", "dc/def/_c_poly_bunch_8h" ],
    [ "CPool.h", "d9/de2/plugin__sa_2game__sa_2_c_pool_8h.html", "d9/de2/plugin__sa_2game__sa_2_c_pool_8h" ],
    [ "CPools.cpp", "dc/d10/plugin__sa_2game__sa_2_c_pools_8cpp.html", "dc/d10/plugin__sa_2game__sa_2_c_pools_8cpp" ],
    [ "CPools.h", "d9/dbf/plugin__sa_2game__sa_2_c_pools_8h.html", [
      [ "CPools", "d6/db0/class_c_pools.html", null ]
    ] ],
    [ "CPopCycle.cpp", "df/d94/_c_pop_cycle_8cpp.html", null ],
    [ "CPopCycle.h", "d6/d2c/_c_pop_cycle_8h.html", "d6/d2c/_c_pop_cycle_8h" ],
    [ "CPopulation.cpp", "d4/daa/plugin__sa_2game__sa_2_c_population_8cpp.html", null ],
    [ "CPopulation.h", "d2/d0f/plugin__sa_2game__sa_2_c_population_8h.html", "d2/d0f/plugin__sa_2game__sa_2_c_population_8h" ],
    [ "CProjectile.cpp", "d2/da2/plugin__sa_2game__sa_2_c_projectile_8cpp.html", null ],
    [ "CProjectile.h", "d0/d1e/plugin__sa_2game__sa_2_c_projectile_8h.html", "d0/d1e/plugin__sa_2game__sa_2_c_projectile_8h" ],
    [ "CProjectileInfo.cpp", "d4/d5d/plugin__sa_2game__sa_2_c_projectile_info_8cpp.html", "d4/d5d/plugin__sa_2game__sa_2_c_projectile_info_8cpp" ],
    [ "CProjectileInfo.h", "da/dad/plugin__sa_2game__sa_2_c_projectile_info_8h.html", "da/dad/plugin__sa_2game__sa_2_c_projectile_info_8h" ],
    [ "CPtrList.cpp", "df/d0c/plugin__sa_2game__sa_2_c_ptr_list_8cpp.html", null ],
    [ "CPtrList.h", "d1/d53/plugin__sa_2game__sa_2_c_ptr_list_8h.html", "d1/d53/plugin__sa_2game__sa_2_c_ptr_list_8h" ],
    [ "CPtrListDoubleLink.cpp", "db/d9b/_c_ptr_list_double_link_8cpp.html", null ],
    [ "CPtrListDoubleLink.h", "d2/db0/_c_ptr_list_double_link_8h.html", "d2/db0/_c_ptr_list_double_link_8h" ],
    [ "CPtrListSingleLink.cpp", "de/d93/_c_ptr_list_single_link_8cpp.html", null ],
    [ "CPtrListSingleLink.h", "dc/d42/_c_ptr_list_single_link_8h.html", "dc/d42/_c_ptr_list_single_link_8h" ],
    [ "CPtrNode.h", "d4/d7c/plugin__sa_2game__sa_2_c_ptr_node_8h.html", "d4/d7c/plugin__sa_2game__sa_2_c_ptr_node_8h" ],
    [ "CPtrNodeDoubleLink.cpp", "d3/d79/_c_ptr_node_double_link_8cpp.html", null ],
    [ "CPtrNodeDoubleLink.h", "de/d5e/_c_ptr_node_double_link_8h.html", "de/d5e/_c_ptr_node_double_link_8h" ],
    [ "CPtrNodeSingleLink.cpp", "d5/dea/_c_ptr_node_single_link_8cpp.html", null ],
    [ "CPtrNodeSingleLink.h", "de/dbe/_c_ptr_node_single_link_8h.html", "de/dbe/_c_ptr_node_single_link_8h" ],
    [ "CQuadBike.cpp", "d1/d43/_c_quad_bike_8cpp.html", "d1/d43/_c_quad_bike_8cpp" ],
    [ "CQuadBike.h", "d3/de1/_c_quad_bike_8h.html", "d3/de1/_c_quad_bike_8h" ],
    [ "CQuadTreeNode.cpp", "d3/d18/_c_quad_tree_node_8cpp.html", null ],
    [ "CQuadTreeNode.h", "da/db5/_c_quad_tree_node_8h.html", "da/db5/_c_quad_tree_node_8h" ],
    [ "CQuaternion.cpp", "d3/d81/plugin__sa_2game__sa_2_c_quaternion_8cpp.html", null ],
    [ "CQuaternion.h", "dc/d6f/plugin__sa_2game__sa_2_c_quaternion_8h.html", "dc/d6f/plugin__sa_2game__sa_2_c_quaternion_8h" ],
    [ "CQueuedMode.h", "db/d68/plugin__sa_2game__sa_2_c_queued_mode_8h.html", "db/d68/plugin__sa_2game__sa_2_c_queued_mode_8h" ],
    [ "CRadar.cpp", "d8/daa/_c_radar_8cpp.html", "d8/daa/_c_radar_8cpp" ],
    [ "CRadar.h", "d5/d9d/_c_radar_8h.html", "d5/d9d/_c_radar_8h" ],
    [ "CRealTimeShadow.cpp", "d0/d02/_c_real_time_shadow_8cpp.html", null ],
    [ "CRealTimeShadow.h", "d6/d8d/_c_real_time_shadow_8h.html", "d6/d8d/_c_real_time_shadow_8h" ],
    [ "CRect.cpp", "d8/df9/_c_rect_8cpp.html", null ],
    [ "CRect.h", "d6/d44/plugin__sa_2game__sa_2_c_rect_8h.html", "d6/d44/plugin__sa_2game__sa_2_c_rect_8h" ],
    [ "CReference.h", "d3/da3/plugin__sa_2game__sa_2_c_reference_8h.html", "d3/da3/plugin__sa_2game__sa_2_c_reference_8h" ],
    [ "CReferences.cpp", "d7/d5c/plugin__sa_2game__sa_2_c_references_8cpp.html", null ],
    [ "CReferences.h", "d2/dce/plugin__sa_2game__sa_2_c_references_8h.html", "d2/dce/plugin__sa_2game__sa_2_c_references_8h" ],
    [ "CRegisteredCorona.cpp", "d6/d42/plugin__sa_2game__sa_2_c_registered_corona_8cpp.html", null ],
    [ "CRegisteredCorona.h", "d0/d63/plugin__sa_2game__sa_2_c_registered_corona_8h.html", "d0/d63/plugin__sa_2game__sa_2_c_registered_corona_8h" ],
    [ "CRegisteredMotionBlurStreak.cpp", "d9/da4/plugin__sa_2game__sa_2_c_registered_motion_blur_streak_8cpp.html", null ],
    [ "CRegisteredMotionBlurStreak.h", "d0/dd4/plugin__sa_2game__sa_2_c_registered_motion_blur_streak_8h.html", "d0/dd4/plugin__sa_2game__sa_2_c_registered_motion_blur_streak_8h" ],
    [ "CRenderer.cpp", "d7/df4/_c_renderer_8cpp.html", "d7/df4/_c_renderer_8cpp" ],
    [ "CRenderer.h", "d9/d87/_c_renderer_8h.html", "d9/d87/_c_renderer_8h" ],
    [ "CRepeatSector.h", "d2/d01/_c_repeat_sector_8h.html", "d2/d01/_c_repeat_sector_8h" ],
    [ "CReplay.cpp", "d7/db8/plugin__sa_2game__sa_2_c_replay_8cpp.html", null ],
    [ "CReplay.h", "db/d74/plugin__sa_2game__sa_2_c_replay_8h.html", [
      [ "CReplay", "d8/d2c/class_c_replay.html", null ]
    ] ],
    [ "CRestart.cpp", "df/d60/plugin__sa_2game__sa_2_c_restart_8cpp.html", null ],
    [ "CRestart.h", "d2/dad/plugin__sa_2game__sa_2_c_restart_8h.html", [
      [ "CRestart", "d1/dc1/class_c_restart.html", null ]
    ] ],
    [ "CRideAnimData.h", "d2/da5/_c_ride_anim_data_8h.html", "d2/da5/_c_ride_anim_data_8h" ],
    [ "CRoadBlocks.cpp", "d0/d8d/_c_road_blocks_8cpp.html", "d0/d8d/_c_road_blocks_8cpp" ],
    [ "CRoadBlocks.h", "d9/d76/_c_road_blocks_8h.html", [
      [ "tScriptRoadBlocks", "d1/d60/structt_script_road_blocks.html", "d1/d60/structt_script_road_blocks" ],
      [ "tRoadbloxDat", "d8/d6a/structt_roadblox_dat.html", "d8/d6a/structt_roadblox_dat" ],
      [ "CRoadBlocks", "d1/d81/class_c_road_blocks.html", null ]
    ] ],
    [ "CRope.cpp", "d2/d89/_c_rope_8cpp.html", null ],
    [ "CRope.h", "db/d92/_c_rope_8h.html", "db/d92/_c_rope_8h" ],
    [ "CRopes.cpp", "d0/d0b/_c_ropes_8cpp.html", null ],
    [ "CRopes.h", "d4/d06/_c_ropes_8h.html", [
      [ "CRopes", "da/db7/class_c_ropes.html", null ]
    ] ],
    [ "CRunningScript.cpp", "dd/de9/plugin__sa_2game__sa_2_c_running_script_8cpp.html", "dd/de9/plugin__sa_2game__sa_2_c_running_script_8cpp" ],
    [ "CRunningScript.h", "dc/d4e/plugin__sa_2game__sa_2_c_running_script_8h.html", "dc/d4e/plugin__sa_2game__sa_2_c_running_script_8h" ],
    [ "CScene.cpp", "d2/db6/plugin__sa_2game__sa_2_c_scene_8cpp.html", "d2/db6/plugin__sa_2game__sa_2_c_scene_8cpp" ],
    [ "CScene.h", "d9/d7a/plugin__sa_2game__sa_2_c_scene_8h.html", "d9/d7a/plugin__sa_2game__sa_2_c_scene_8h" ],
    [ "CScriptResourceManager.cpp", "da/d39/_c_script_resource_manager_8cpp.html", "da/d39/_c_script_resource_manager_8cpp" ],
    [ "CScriptResourceManager.h", "d5/dd9/_c_script_resource_manager_8h.html", "d5/dd9/_c_script_resource_manager_8h" ],
    [ "CScriptsForBrains.cpp", "d7/daf/_c_scripts_for_brains_8cpp.html", "d7/daf/_c_scripts_for_brains_8cpp" ],
    [ "CScriptsForBrains.h", "d4/dfc/_c_scripts_for_brains_8h.html", [
      [ "CScriptsForBrains", "dc/dbc/class_c_scripts_for_brains.html", "dc/dbc/class_c_scripts_for_brains" ]
    ] ],
    [ "CSector.h", "d3/d2c/plugin__sa_2game__sa_2_c_sector_8h.html", "d3/d2c/plugin__sa_2game__sa_2_c_sector_8h" ],
    [ "CSetPiece.cpp", "de/d0f/_c_set_piece_8cpp.html", null ],
    [ "CSetPiece.h", "dd/d4b/_c_set_piece_8h.html", "dd/d4b/_c_set_piece_8h" ],
    [ "CSetPieces.cpp", "dd/d65/_c_set_pieces_8cpp.html", null ],
    [ "CSetPieces.h", "dd/d54/_c_set_pieces_8h.html", "dd/d54/_c_set_pieces_8h" ],
    [ "CShadowCamera.cpp", "da/dac/plugin__sa_2game__sa_2_c_shadow_camera_8cpp.html", null ],
    [ "CShadowCamera.h", "da/d13/plugin__sa_2game__sa_2_c_shadow_camera_8h.html", "da/d13/plugin__sa_2game__sa_2_c_shadow_camera_8h" ],
    [ "CShadows.cpp", "d7/d1a/plugin__sa_2game__sa_2_c_shadows_8cpp.html", "d7/d1a/plugin__sa_2game__sa_2_c_shadows_8cpp" ],
    [ "CShadows.h", "d6/d58/plugin__sa_2game__sa_2_c_shadows_8h.html", "d6/d58/plugin__sa_2game__sa_2_c_shadows_8h" ],
    [ "CShinyTexts.cpp", "d6/d3c/plugin__sa_2game__sa_2_c_shiny_texts_8cpp.html", "d6/d3c/plugin__sa_2game__sa_2_c_shiny_texts_8cpp" ],
    [ "CShinyTexts.h", "db/d11/plugin__sa_2game__sa_2_c_shiny_texts_8h.html", "db/d11/plugin__sa_2game__sa_2_c_shiny_texts_8h" ],
    [ "CShotInfo.cpp", "d7/d10/plugin__sa_2game__sa_2_c_shot_info_8cpp.html", "d7/d10/plugin__sa_2game__sa_2_c_shot_info_8cpp" ],
    [ "CShotInfo.h", "d1/df3/plugin__sa_2game__sa_2_c_shot_info_8h.html", "d1/df3/plugin__sa_2game__sa_2_c_shot_info_8h" ],
    [ "CSimpleTransform.cpp", "db/d02/_c_simple_transform_8cpp.html", null ],
    [ "CSimpleTransform.h", "d6/d18/_c_simple_transform_8h.html", "d6/d18/_c_simple_transform_8h" ],
    [ "CSpecialFX.cpp", "d9/db5/_c_special_f_x_8cpp.html", "d9/db5/_c_special_f_x_8cpp" ],
    [ "CSpecialFX.h", "d9/d58/_c_special_f_x_8h.html", "d9/d58/_c_special_f_x_8h" ],
    [ "CSpecialPlateHandler.cpp", "da/de4/_c_special_plate_handler_8cpp.html", null ],
    [ "CSpecialPlateHandler.h", "da/d48/_c_special_plate_handler_8h.html", "da/d48/_c_special_plate_handler_8h" ],
    [ "CSphere.cpp", "d8/d24/plugin__sa_2game__sa_2_c_sphere_8cpp.html", null ],
    [ "CSphere.h", "d5/dbf/plugin__sa_2game__sa_2_c_sphere_8h.html", "d5/dbf/plugin__sa_2game__sa_2_c_sphere_8h" ],
    [ "CSprite.cpp", "d0/d03/plugin__sa_2game__sa_2_c_sprite_8cpp.html", null ],
    [ "CSprite.h", "da/da7/plugin__sa_2game__sa_2_c_sprite_8h.html", [
      [ "CSprite", "d3/d0f/class_c_sprite.html", null ]
    ] ],
    [ "CSprite2d.cpp", "db/dfa/plugin__sa_2game__sa_2_c_sprite2d_8cpp.html", "db/dfa/plugin__sa_2game__sa_2_c_sprite2d_8cpp" ],
    [ "CSprite2d.h", "d0/d96/plugin__sa_2game__sa_2_c_sprite2d_8h.html", "d0/d96/plugin__sa_2game__sa_2_c_sprite2d_8h" ],
    [ "CStats.cpp", "dc/d81/plugin__sa_2game__sa_2_c_stats_8cpp.html", null ],
    [ "CStats.h", "d5/d85/plugin__sa_2game__sa_2_c_stats_8h.html", "d5/d85/plugin__sa_2game__sa_2_c_stats_8h" ],
    [ "CStore.h", "de/d1f/_c_store_8h.html", [
      [ "CStore", "dd/dcb/class_c_store.html", "dd/dcb/class_c_store" ]
    ] ],
    [ "CStoredCollPoly.h", "d3/d89/plugin__sa_2game__sa_2_c_stored_coll_poly_8h.html", "d3/d89/plugin__sa_2game__sa_2_c_stored_coll_poly_8h" ],
    [ "CStreamedScripts.cpp", "d6/d70/_c_streamed_scripts_8cpp.html", "d6/d70/_c_streamed_scripts_8cpp" ],
    [ "CStreamedScripts.h", "d1/db0/_c_streamed_scripts_8h.html", "d1/db0/_c_streamed_scripts_8h" ],
    [ "CStreaming.cpp", "dc/d73/plugin__sa_2game__sa_2_c_streaming_8cpp.html", "dc/d73/plugin__sa_2game__sa_2_c_streaming_8cpp" ],
    [ "CStreaming.h", "db/d34/plugin__sa_2game__sa_2_c_streaming_8h.html", "db/d34/plugin__sa_2game__sa_2_c_streaming_8h" ],
    [ "CStreamingInfo.cpp", "dd/d55/plugin__sa_2game__sa_2_c_streaming_info_8cpp.html", "dd/d55/plugin__sa_2game__sa_2_c_streaming_info_8cpp" ],
    [ "CStreamingInfo.h", "d7/d95/plugin__sa_2game__sa_2_c_streaming_info_8h.html", "d7/d95/plugin__sa_2game__sa_2_c_streaming_info_8h" ],
    [ "CStuckCarCheck.cpp", "db/d2b/_c_stuck_car_check_8cpp.html", "db/d2b/_c_stuck_car_check_8cpp" ],
    [ "CStuckCarCheck.h", "d7/da7/_c_stuck_car_check_8h.html", "d7/da7/_c_stuck_car_check_8h" ],
    [ "CTask.cpp", "de/d84/_c_task_8cpp.html", null ],
    [ "CTask.h", "d7/d3b/_c_task_8h.html", "d7/d3b/_c_task_8h" ],
    [ "CTaskComplex.cpp", "d4/d73/_c_task_complex_8cpp.html", null ],
    [ "CTaskComplex.h", "d8/d95/_c_task_complex_8h.html", "d8/d95/_c_task_complex_8h" ],
    [ "CTaskComplexClimb.cpp", "d2/dfe/_c_task_complex_climb_8cpp.html", null ],
    [ "CTaskComplexClimb.h", "d3/d93/_c_task_complex_climb_8h.html", "d3/d93/_c_task_complex_climb_8h" ],
    [ "CTaskComplexCopInCar.cpp", "d7/d46/_c_task_complex_cop_in_car_8cpp.html", null ],
    [ "CTaskComplexCopInCar.h", "d3/dc1/_c_task_complex_cop_in_car_8h.html", "d3/dc1/_c_task_complex_cop_in_car_8h" ],
    [ "CTaskComplexDie.cpp", "d0/d03/_c_task_complex_die_8cpp.html", null ],
    [ "CTaskComplexDie.h", "d4/d2b/_c_task_complex_die_8h.html", "d4/d2b/_c_task_complex_die_8h" ],
    [ "CTaskComplexEnterBoatAsDriver.cpp", "d2/d00/_c_task_complex_enter_boat_as_driver_8cpp.html", null ],
    [ "CTaskComplexEnterBoatAsDriver.h", "d9/dab/_c_task_complex_enter_boat_as_driver_8h.html", "d9/dab/_c_task_complex_enter_boat_as_driver_8h" ],
    [ "CTaskComplexEnterCar.cpp", "df/d26/_c_task_complex_enter_car_8cpp.html", null ],
    [ "CTaskComplexEnterCar.h", "d0/ded/_c_task_complex_enter_car_8h.html", "d0/ded/_c_task_complex_enter_car_8h" ],
    [ "CTaskComplexEnterCarAsDriver.cpp", "db/d80/_c_task_complex_enter_car_as_driver_8cpp.html", null ],
    [ "CTaskComplexEnterCarAsDriver.h", "d6/d34/_c_task_complex_enter_car_as_driver_8h.html", "d6/d34/_c_task_complex_enter_car_as_driver_8h" ],
    [ "CTaskComplexEnterCarAsPassenger.cpp", "d5/d13/_c_task_complex_enter_car_as_passenger_8cpp.html", null ],
    [ "CTaskComplexEnterCarAsPassenger.h", "d7/d72/_c_task_complex_enter_car_as_passenger_8h.html", "d7/d72/_c_task_complex_enter_car_as_passenger_8h" ],
    [ "CTaskComplexFacial.cpp", "d3/d39/_c_task_complex_facial_8cpp.html", null ],
    [ "CTaskComplexFacial.h", "d4/daf/_c_task_complex_facial_8h.html", "d4/daf/_c_task_complex_facial_8h" ],
    [ "CTaskComplexJump.cpp", "d1/dbe/_c_task_complex_jump_8cpp.html", null ],
    [ "CTaskComplexJump.h", "d9/dcf/_c_task_complex_jump_8h.html", "d9/dcf/_c_task_complex_jump_8h" ],
    [ "CTaskComplexKillPedFromBoat.cpp", "d0/df6/_c_task_complex_kill_ped_from_boat_8cpp.html", null ],
    [ "CTaskComplexKillPedFromBoat.h", "d9/d77/_c_task_complex_kill_ped_from_boat_8h.html", "d9/d77/_c_task_complex_kill_ped_from_boat_8h" ],
    [ "CTaskComplexKillPedOnFoot.cpp", "d4/d9a/_c_task_complex_kill_ped_on_foot_8cpp.html", null ],
    [ "CTaskComplexKillPedOnFoot.h", "d9/dfc/_c_task_complex_kill_ped_on_foot_8h.html", "d9/dfc/_c_task_complex_kill_ped_on_foot_8h" ],
    [ "CTaskComplexLeaveCar.cpp", "d3/dee/_c_task_complex_leave_car_8cpp.html", null ],
    [ "CTaskComplexLeaveCar.h", "da/d16/_c_task_complex_leave_car_8h.html", "da/d16/_c_task_complex_leave_car_8h" ],
    [ "CTaskComplexPlayHandSignalAnim.cpp", "d2/d78/_c_task_complex_play_hand_signal_anim_8cpp.html", null ],
    [ "CTaskComplexPlayHandSignalAnim.h", "de/df8/_c_task_complex_play_hand_signal_anim_8h.html", "de/df8/_c_task_complex_play_hand_signal_anim_8h" ],
    [ "CTaskComplexProstituteSolicit.cpp", "d3/d12/_c_task_complex_prostitute_solicit_8cpp.html", null ],
    [ "CTaskComplexProstituteSolicit.h", "d2/dad/_c_task_complex_prostitute_solicit_8h.html", "d2/dad/_c_task_complex_prostitute_solicit_8h" ],
    [ "CTaskComplexSequence.cpp", "da/de1/_c_task_complex_sequence_8cpp.html", null ],
    [ "CTaskComplexSequence.h", "d7/d73/_c_task_complex_sequence_8h.html", [
      [ "CTaskComplexSequence", "d1/d0b/class_c_task_complex_sequence.html", "d1/d0b/class_c_task_complex_sequence" ]
    ] ],
    [ "CTaskComplexStuckInAir.cpp", "d1/d61/_c_task_complex_stuck_in_air_8cpp.html", null ],
    [ "CTaskComplexStuckInAir.h", "d7/ddc/_c_task_complex_stuck_in_air_8h.html", "d7/ddc/_c_task_complex_stuck_in_air_8h" ],
    [ "CTaskComplexSunbathe.cpp", "dd/dd6/_c_task_complex_sunbathe_8cpp.html", null ],
    [ "CTaskComplexSunbathe.h", "d1/ddb/_c_task_complex_sunbathe_8h.html", "d1/ddb/_c_task_complex_sunbathe_8h" ],
    [ "CTaskComplexUseMobilePhone.cpp", "d6/de4/_c_task_complex_use_mobile_phone_8cpp.html", null ],
    [ "CTaskComplexUseMobilePhone.h", "d5/d45/_c_task_complex_use_mobile_phone_8h.html", "d5/d45/_c_task_complex_use_mobile_phone_8h" ],
    [ "CTaskComplexWander.cpp", "d9/d02/_c_task_complex_wander_8cpp.html", null ],
    [ "CTaskComplexWander.h", "d2/d8d/_c_task_complex_wander_8h.html", "d2/d8d/_c_task_complex_wander_8h" ],
    [ "CTaskComplexWanderStandard.cpp", "d2/d31/_c_task_complex_wander_standard_8cpp.html", null ],
    [ "CTaskComplexWanderStandard.h", "d2/dfe/_c_task_complex_wander_standard_8h.html", "d2/dfe/_c_task_complex_wander_standard_8h" ],
    [ "CTaskManager.cpp", "d3/d09/_c_task_manager_8cpp.html", null ],
    [ "CTaskManager.h", "df/dab/_c_task_manager_8h.html", "df/dab/_c_task_manager_8h" ],
    [ "CTaskSimple.cpp", "d2/d42/_c_task_simple_8cpp.html", null ],
    [ "CTaskSimple.h", "d8/d69/_c_task_simple_8h.html", "d8/d69/_c_task_simple_8h" ],
    [ "CTaskSimpleAnim.cpp", "df/d2f/_c_task_simple_anim_8cpp.html", null ],
    [ "CTaskSimpleAnim.h", "d0/d12/_c_task_simple_anim_8h.html", "d0/d12/_c_task_simple_anim_8h" ],
    [ "CTaskSimpleCarSetPedInAsDriver.cpp", "df/d69/_c_task_simple_car_set_ped_in_as_driver_8cpp.html", null ],
    [ "CTaskSimpleCarSetPedInAsDriver.h", "db/dec/_c_task_simple_car_set_ped_in_as_driver_8h.html", "db/dec/_c_task_simple_car_set_ped_in_as_driver_8h" ],
    [ "CTaskSimpleCarSetPedInAsPassenger.cpp", "d6/d19/_c_task_simple_car_set_ped_in_as_passenger_8cpp.html", null ],
    [ "CTaskSimpleCarSetPedInAsPassenger.h", "d6/d2a/_c_task_simple_car_set_ped_in_as_passenger_8h.html", "d6/d2a/_c_task_simple_car_set_ped_in_as_passenger_8h" ],
    [ "CTaskSimpleCarSetPedOut.cpp", "de/d42/_c_task_simple_car_set_ped_out_8cpp.html", null ],
    [ "CTaskSimpleCarSetPedOut.h", "df/dce/_c_task_simple_car_set_ped_out_8h.html", "df/dce/_c_task_simple_car_set_ped_out_8h" ],
    [ "CTaskSimpleChoking.cpp", "d3/d57/_c_task_simple_choking_8cpp.html", null ],
    [ "CTaskSimpleChoking.h", "da/d0d/_c_task_simple_choking_8h.html", "da/d0d/_c_task_simple_choking_8h" ],
    [ "CTaskSimpleClimb.cpp", "d7/d3b/_c_task_simple_climb_8cpp.html", null ],
    [ "CTaskSimpleClimb.h", "de/d3b/_c_task_simple_climb_8h.html", "de/d3b/_c_task_simple_climb_8h" ],
    [ "CTaskSimpleDuck.cpp", "d6/d95/_c_task_simple_duck_8cpp.html", null ],
    [ "CTaskSimpleDuck.h", "d3/d01/_c_task_simple_duck_8h.html", "d3/d01/_c_task_simple_duck_8h" ],
    [ "CTaskSimpleDuckToggle.cpp", "d5/d5d/_c_task_simple_duck_toggle_8cpp.html", null ],
    [ "CTaskSimpleDuckToggle.h", "d8/d0e/_c_task_simple_duck_toggle_8h.html", "d8/d0e/_c_task_simple_duck_toggle_8h" ],
    [ "CTaskSimpleFacial.cpp", "de/de0/_c_task_simple_facial_8cpp.html", null ],
    [ "CTaskSimpleFacial.h", "d1/d9f/_c_task_simple_facial_8h.html", "d1/d9f/_c_task_simple_facial_8h" ],
    [ "CTaskSimpleFight.cpp", "d8/db3/_c_task_simple_fight_8cpp.html", null ],
    [ "CTaskSimpleFight.h", "da/dee/_c_task_simple_fight_8h.html", "da/dee/_c_task_simple_fight_8h" ],
    [ "CTaskSimpleGangDriveBy.cpp", "dd/ddc/_c_task_simple_gang_drive_by_8cpp.html", null ],
    [ "CTaskSimpleGangDriveBy.h", "d7/dd6/_c_task_simple_gang_drive_by_8h.html", "d7/dd6/_c_task_simple_gang_drive_by_8h" ],
    [ "CTaskSimpleHoldEntity.cpp", "db/d38/_c_task_simple_hold_entity_8cpp.html", null ],
    [ "CTaskSimpleHoldEntity.h", "dc/dc4/_c_task_simple_hold_entity_8h.html", [
      [ "CTaskSimpleHoldEntity", "df/d39/class_c_task_simple_hold_entity.html", "df/d39/class_c_task_simple_hold_entity" ]
    ] ],
    [ "CTaskSimpleIKChain.cpp", "d0/d62/_c_task_simple_i_k_chain_8cpp.html", null ],
    [ "CTaskSimpleIKChain.h", "d2/d23/_c_task_simple_i_k_chain_8h.html", "d2/d23/_c_task_simple_i_k_chain_8h" ],
    [ "CTaskSimpleIKLookAt.cpp", "d2/d31/_c_task_simple_i_k_look_at_8cpp.html", null ],
    [ "CTaskSimpleIKLookAt.h", "d0/d5a/_c_task_simple_i_k_look_at_8h.html", "d0/d5a/_c_task_simple_i_k_look_at_8h" ],
    [ "CTaskSimpleIKManager.cpp", "d5/d02/_c_task_simple_i_k_manager_8cpp.html", null ],
    [ "CTaskSimpleIKManager.h", "d4/dc0/_c_task_simple_i_k_manager_8h.html", "d4/dc0/_c_task_simple_i_k_manager_8h" ],
    [ "CTaskSimpleInAir.cpp", "d1/d97/_c_task_simple_in_air_8cpp.html", null ],
    [ "CTaskSimpleInAir.h", "dd/d0f/_c_task_simple_in_air_8h.html", "dd/d0f/_c_task_simple_in_air_8h" ],
    [ "CTaskSimpleJetPack.cpp", "d7/dfb/_c_task_simple_jet_pack_8cpp.html", "d7/dfb/_c_task_simple_jet_pack_8cpp" ],
    [ "CTaskSimpleJetpack.h", "d6/dfc/_c_task_simple_jetpack_8h.html", "d6/dfc/_c_task_simple_jetpack_8h" ],
    [ "CTaskSimpleJump.cpp", "dc/d76/_c_task_simple_jump_8cpp.html", null ],
    [ "CTaskSimpleJump.h", "d7/de0/_c_task_simple_jump_8h.html", "d7/de0/_c_task_simple_jump_8h" ],
    [ "CTaskSimplePlayerOnFoot.cpp", "d3/dc7/_c_task_simple_player_on_foot_8cpp.html", null ],
    [ "CTaskSimplePlayerOnFoot.h", "da/ddb/_c_task_simple_player_on_foot_8h.html", "da/ddb/_c_task_simple_player_on_foot_8h" ],
    [ "CTaskSimpleRunAnim.cpp", "d4/dc5/_c_task_simple_run_anim_8cpp.html", null ],
    [ "CTaskSimpleRunAnim.h", "d7/d60/_c_task_simple_run_anim_8h.html", "d7/d60/_c_task_simple_run_anim_8h" ],
    [ "CTaskSimpleRunNamedAnim.cpp", "db/dbb/_c_task_simple_run_named_anim_8cpp.html", null ],
    [ "CTaskSimpleRunNamedAnim.h", "df/de0/_c_task_simple_run_named_anim_8h.html", "df/de0/_c_task_simple_run_named_anim_8h" ],
    [ "CTaskSimpleStandStill.cpp", "dd/d5d/_c_task_simple_stand_still_8cpp.html", null ],
    [ "CTaskSimpleStandStill.h", "dd/dfe/_c_task_simple_stand_still_8h.html", "dd/dfe/_c_task_simple_stand_still_8h" ],
    [ "CTaskSimpleStealthKill.cpp", "d1/db9/_c_task_simple_stealth_kill_8cpp.html", null ],
    [ "CTaskSimpleStealthKill.h", "d3/d3e/_c_task_simple_stealth_kill_8h.html", "d3/d3e/_c_task_simple_stealth_kill_8h" ],
    [ "CTaskSimpleSwim.cpp", "d5/dab/_c_task_simple_swim_8cpp.html", null ],
    [ "CTaskSimpleSwim.h", "d9/d5b/_c_task_simple_swim_8h.html", "d9/d5b/_c_task_simple_swim_8h" ],
    [ "CTaskSimpleThrowProjectile.cpp", "d1/dea/_c_task_simple_throw_projectile_8cpp.html", null ],
    [ "CTaskSimpleThrowProjectile.h", "db/d0f/_c_task_simple_throw_projectile_8h.html", "db/d0f/_c_task_simple_throw_projectile_8h" ],
    [ "CTaskSimpleTriggerLookAt.cpp", "d6/d4d/_c_task_simple_trigger_look_at_8cpp.html", null ],
    [ "CTaskSimpleTriggerLookAt.h", "d0/d10/_c_task_simple_trigger_look_at_8h.html", "d0/d10/_c_task_simple_trigger_look_at_8h" ],
    [ "CTaskSimpleUseGun.cpp", "dc/d1a/_c_task_simple_use_gun_8cpp.html", null ],
    [ "CTaskSimpleUseGun.h", "df/d7b/_c_task_simple_use_gun_8h.html", "df/d7b/_c_task_simple_use_gun_8h" ],
    [ "CTaskTimer.cpp", "d1/dfe/_c_task_timer_8cpp.html", null ],
    [ "CTaskTimer.h", "d8/d9f/_c_task_timer_8h.html", "d8/d9f/_c_task_timer_8h" ],
    [ "CTaskUtilityLineUpPedWithCar.cpp", "da/d22/_c_task_utility_line_up_ped_with_car_8cpp.html", null ],
    [ "CTaskUtilityLineUpPedWithCar.h", "d9/dfb/_c_task_utility_line_up_ped_with_car_8h.html", "d9/dfb/_c_task_utility_line_up_ped_with_car_8h" ],
    [ "CText.cpp", "db/ddb/_c_text_8cpp.html", "db/ddb/_c_text_8cpp" ],
    [ "CText.h", "dc/d10/_c_text_8h.html", "dc/d10/_c_text_8h" ],
    [ "CTheCarGenerators.cpp", "d1/dce/plugin__sa_2game__sa_2_c_the_car_generators_8cpp.html", "d1/dce/plugin__sa_2game__sa_2_c_the_car_generators_8cpp" ],
    [ "CTheCarGenerators.h", "d5/df2/plugin__sa_2game__sa_2_c_the_car_generators_8h.html", [
      [ "CTheCarGenerators", "d0/d78/class_c_the_car_generators.html", "d0/d78/class_c_the_car_generators" ]
    ] ],
    [ "CTheScripts.cpp", "db/d6d/plugin__sa_2game__sa_2_c_the_scripts_8cpp.html", "db/d6d/plugin__sa_2game__sa_2_c_the_scripts_8cpp" ],
    [ "CTheScripts.h", "df/dda/plugin__sa_2game__sa_2_c_the_scripts_8h.html", [
      [ "tBuildingSwap", "d1/d07/structt_building_swap.html", "d1/d07/structt_building_swap" ],
      [ "tScriptSwitchCase", "db/d90/structt_script_switch_case.html", "db/d90/structt_script_switch_case" ],
      [ "tScriptCheckpoint", "de/d28/structt_script_checkpoint.html", "de/d28/structt_script_checkpoint" ],
      [ "tScriptEffectSystem", "d6/dab/structt_script_effect_system.html", "d6/dab/structt_script_effect_system" ],
      [ "tScriptSequence", "d7/d3f/structt_script_sequence.html", "d7/d3f/structt_script_sequence" ],
      [ "tScriptText", "d7/d73/structt_script_text.html", "d7/d73/structt_script_text" ],
      [ "tScriptRectangle", "d2/d1f/structt_script_rectangle.html", "d2/d1f/structt_script_rectangle" ],
      [ "tScriptAttachedAnimGroup", "d0/d66/structt_script_attached_anim_group.html", "d0/d66/structt_script_attached_anim_group" ],
      [ "tScriptSearchlight", "df/dfb/structt_script_searchlight.html", "df/dfb/structt_script_searchlight" ],
      [ "tUsedObject", "d7/d4f/structt_used_object.html", "d7/d4f/structt_used_object" ],
      [ "tScriptSphere", "dd/d34/structt_script_sphere.html", "dd/d34/structt_script_sphere" ],
      [ "CTheScripts", "db/def/class_c_the_scripts.html", null ]
    ] ],
    [ "CTheZones.cpp", "d9/ded/plugin__sa_2game__sa_2_c_the_zones_8cpp.html", "d9/ded/plugin__sa_2game__sa_2_c_the_zones_8cpp" ],
    [ "CTheZones.h", "d8/d67/plugin__sa_2game__sa_2_c_the_zones_8h.html", [
      [ "CTheZones", "d4/d88/class_c_the_zones.html", null ]
    ] ],
    [ "CTimeCycle.cpp", "d8/de8/plugin__sa_2game__sa_2_c_time_cycle_8cpp.html", null ],
    [ "CTimeCycle.h", "da/df3/plugin__sa_2game__sa_2_c_time_cycle_8h.html", [
      [ "CTimeCycle", "dd/d04/class_c_time_cycle.html", null ]
    ] ],
    [ "CTimeCycleBox.h", "d3/d03/_c_time_cycle_box_8h.html", [
      [ "CTimeCycleBox", "da/dce/class_c_time_cycle_box.html", "da/dce/class_c_time_cycle_box" ]
    ] ],
    [ "CTimeModelInfo.cpp", "d1/d6f/plugin__sa_2game__sa_2_c_time_model_info_8cpp.html", null ],
    [ "CTimeModelInfo.h", "d1/db9/plugin__sa_2game__sa_2_c_time_model_info_8h.html", "d1/db9/plugin__sa_2game__sa_2_c_time_model_info_8h" ],
    [ "CTimer.cpp", "d2/d5b/plugin__sa_2game__sa_2_c_timer_8cpp.html", null ],
    [ "CTimer.h", "d3/d35/plugin__sa_2game__sa_2_c_timer_8h.html", [
      [ "CTimer", "db/de1/class_c_timer.html", null ]
    ] ],
    [ "CTrailer.cpp", "df/de9/_c_trailer_8cpp.html", "df/de9/_c_trailer_8cpp" ],
    [ "CTrailer.h", "d4/d3e/_c_trailer_8h.html", "d4/d3e/_c_trailer_8h" ],
    [ "CTrain.cpp", "d7/d66/plugin__sa_2game__sa_2_c_train_8cpp.html", "d7/d66/plugin__sa_2game__sa_2_c_train_8cpp" ],
    [ "CTrain.h", "d2/dfa/plugin__sa_2game__sa_2_c_train_8h.html", "d2/dfa/plugin__sa_2game__sa_2_c_train_8h" ],
    [ "CTrainNode.cpp", "d0/d52/plugin__sa_2game__sa_2_c_train_node_8cpp.html", null ],
    [ "CTrainNode.h", "de/d62/plugin__sa_2game__sa_2_c_train_node_8h.html", "de/d62/plugin__sa_2game__sa_2_c_train_node_8h" ],
    [ "cTransmission.cpp", "dc/dad/plugin__sa_2game__sa_2c_transmission_8cpp.html", null ],
    [ "cTransmission.h", "d1/d1d/plugin__sa_2game__sa_2c_transmission_8h.html", "d1/d1d/plugin__sa_2game__sa_2c_transmission_8h" ],
    [ "CTxdStore.cpp", "dd/da5/plugin__sa_2game__sa_2_c_txd_store_8cpp.html", null ],
    [ "CTxdStore.h", "de/d33/plugin__sa_2game__sa_2_c_txd_store_8h.html", [
      [ "CTxdStore", "d9/d17/class_c_txd_store.html", null ]
    ] ],
    [ "CUpsideDownCarCheck.cpp", "d7/d3e/_c_upside_down_car_check_8cpp.html", "d7/d3e/_c_upside_down_car_check_8cpp" ],
    [ "CUpsideDownCarCheck.h", "dd/d91/_c_upside_down_car_check_8h.html", "dd/d91/_c_upside_down_car_check_8h" ],
    [ "CUserDisplay.cpp", "d1/da0/plugin__sa_2game__sa_2_c_user_display_8cpp.html", null ],
    [ "CUserDisplay.h", "d3/d35/plugin__sa_2game__sa_2_c_user_display_8h.html", [
      [ "CUserDisplay", "dc/da0/class_c_user_display.html", null ]
    ] ],
    [ "CVector.cpp", "de/d61/plugin__sa_2game__sa_2_c_vector_8cpp.html", null ],
    [ "CVector.h", "d6/dbb/plugin__sa_2game__sa_2_c_vector_8h.html", "d6/dbb/plugin__sa_2game__sa_2_c_vector_8h" ],
    [ "CVector2D.cpp", "d9/dc5/_c_vector2_d_8cpp.html", null ],
    [ "CVector2D.h", "d9/df7/plugin__sa_2game__sa_2_c_vector2_d_8h.html", "d9/df7/plugin__sa_2game__sa_2_c_vector2_d_8h" ],
    [ "CVehicle.cpp", "d1/dbd/plugin__sa_2game__sa_2_c_vehicle_8cpp.html", "d1/dbd/plugin__sa_2game__sa_2_c_vehicle_8cpp" ],
    [ "CVehicle.h", "d0/d24/plugin__sa_2game__sa_2_c_vehicle_8h.html", "d0/d24/plugin__sa_2game__sa_2_c_vehicle_8h" ],
    [ "CVehicleModelInfo.cpp", "dc/d72/plugin__sa_2game__sa_2_c_vehicle_model_info_8cpp.html", null ],
    [ "CVehicleModelInfo.h", "d2/db6/plugin__sa_2game__sa_2_c_vehicle_model_info_8h.html", "d2/db6/plugin__sa_2game__sa_2_c_vehicle_model_info_8h" ],
    [ "CVisibilityPlugins.cpp", "d0/d87/_c_visibility_plugins_8cpp.html", "d0/d87/_c_visibility_plugins_8cpp" ],
    [ "CVisibilityPlugins.h", "db/d91/_c_visibility_plugins_8h.html", [
      [ "tAtomicVisibilityPlugin", "d4/d4e/structt_atomic_visibility_plugin.html", "d4/d4e/structt_atomic_visibility_plugin" ],
      [ "CVisibilityPlugins", "dc/d56/class_c_visibility_plugins.html", "dc/d56/class_c_visibility_plugins" ],
      [ "AlphaObjectInfo", "d6/ddb/struct_c_visibility_plugins_1_1_alpha_object_info.html", "d6/ddb/struct_c_visibility_plugins_1_1_alpha_object_info" ]
    ] ],
    [ "CWanted.cpp", "db/d76/plugin__sa_2game__sa_2_c_wanted_8cpp.html", null ],
    [ "CWanted.h", "de/d35/plugin__sa_2game__sa_2_c_wanted_8h.html", "de/d35/plugin__sa_2game__sa_2_c_wanted_8h" ],
    [ "CWeapon.cpp", "d5/d09/plugin__sa_2game__sa_2_c_weapon_8cpp.html", "d5/d09/plugin__sa_2game__sa_2_c_weapon_8cpp" ],
    [ "CWeapon.h", "d7/d17/plugin__sa_2game__sa_2_c_weapon_8h.html", "d7/d17/plugin__sa_2game__sa_2_c_weapon_8h" ],
    [ "CWeaponEffects.cpp", "dd/d15/plugin__sa_2game__sa_2_c_weapon_effects_8cpp.html", "dd/d15/plugin__sa_2game__sa_2_c_weapon_effects_8cpp" ],
    [ "CWeaponEffects.h", "d1/dd8/plugin__sa_2game__sa_2_c_weapon_effects_8h.html", "d1/dd8/plugin__sa_2game__sa_2_c_weapon_effects_8h" ],
    [ "CWeaponInfo.cpp", "de/dda/plugin__sa_2game__sa_2_c_weapon_info_8cpp.html", "de/dda/plugin__sa_2game__sa_2_c_weapon_info_8cpp" ],
    [ "CWeaponInfo.h", "d5/db5/plugin__sa_2game__sa_2_c_weapon_info_8h.html", "d5/db5/plugin__sa_2game__sa_2_c_weapon_info_8h" ],
    [ "CWeaponModelInfo.cpp", "d8/de1/plugin__sa_2game__sa_2_c_weapon_model_info_8cpp.html", null ],
    [ "CWeaponModelInfo.h", "d9/dbb/plugin__sa_2game__sa_2_c_weapon_model_info_8h.html", "d9/dbb/plugin__sa_2game__sa_2_c_weapon_model_info_8h" ],
    [ "CWeather.cpp", "d1/df6/plugin__sa_2game__sa_2_c_weather_8cpp.html", null ],
    [ "CWeather.h", "dc/d7c/plugin__sa_2game__sa_2_c_weather_8h.html", "dc/d7c/plugin__sa_2game__sa_2_c_weather_8h" ],
    [ "CWorld.cpp", "d5/dba/plugin__sa_2game__sa_2_c_world_8cpp.html", "d5/dba/plugin__sa_2game__sa_2_c_world_8cpp" ],
    [ "CWorld.h", "d8/d20/plugin__sa_2game__sa_2_c_world_8h.html", "d8/d20/plugin__sa_2game__sa_2_c_world_8h" ],
    [ "CZone.cpp", "df/dd4/plugin__sa_2game__sa_2_c_zone_8cpp.html", "df/dd4/plugin__sa_2game__sa_2_c_zone_8cpp" ],
    [ "CZone.h", "da/dd9/plugin__sa_2game__sa_2_c_zone_8h.html", "da/dd9/plugin__sa_2game__sa_2_c_zone_8h" ],
    [ "CZoneInfo.h", "da/d47/plugin__sa_2game__sa_2_c_zone_info_8h.html", "da/d47/plugin__sa_2game__sa_2_c_zone_info_8h" ],
    [ "D3DIndexDataBuffer.cpp", "d6/d40/_d3_d_index_data_buffer_8cpp.html", null ],
    [ "D3DIndexDataBuffer.h", "d8/db9/_d3_d_index_data_buffer_8h.html", "d8/db9/_d3_d_index_data_buffer_8h" ],
    [ "D3DResourceSystem.cpp", "da/d9a/_d3_d_resource_system_8cpp.html", null ],
    [ "D3DResourceSystem.h", "da/d3d/_d3_d_resource_system_8h.html", [
      [ "D3DResourceSystem", "de/dad/class_d3_d_resource_system.html", null ]
    ] ],
    [ "D3DTextureBuffer.cpp", "d6/dd0/_d3_d_texture_buffer_8cpp.html", null ],
    [ "D3DTextureBuffer.h", "dd/d01/_d3_d_texture_buffer_8h.html", "dd/d01/_d3_d_texture_buffer_8h" ],
    [ "eAnimations.h", "d1/dbd/plugin__sa_2game__sa_2e_animations_8h.html", "d1/dbd/plugin__sa_2game__sa_2e_animations_8h" ],
    [ "eAnimBlendCallbackType.h", "da/d3e/plugin__sa_2game__sa_2e_anim_blend_callback_type_8h.html", "da/d3e/plugin__sa_2game__sa_2e_anim_blend_callback_type_8h" ],
    [ "eAudioEvents.h", "d1/d79/e_audio_events_8h.html", "d1/d79/e_audio_events_8h" ],
    [ "eCamMode.h", "d7/d73/e_cam_mode_8h.html", "d7/d73/e_cam_mode_8h" ],
    [ "eCarMission.h", "d2/dc5/plugin__sa_2game__sa_2e_car_mission_8h.html", "d2/dc5/plugin__sa_2game__sa_2e_car_mission_8h" ],
    [ "eClothesModelPart.h", "d3/db6/e_clothes_model_part_8h.html", "d3/db6/e_clothes_model_part_8h" ],
    [ "eClothesTexturePart.h", "d5/d00/e_clothes_texture_part_8h.html", "d5/d00/e_clothes_texture_part_8h" ],
    [ "eCopType.h", "da/d41/plugin__sa_2game__sa_2e_cop_type_8h.html", "da/d41/plugin__sa_2game__sa_2e_cop_type_8h" ],
    [ "eCrimeType.h", "d3/d8c/plugin__sa_2game__sa_2e_crime_type_8h.html", "d3/d8c/plugin__sa_2game__sa_2e_crime_type_8h" ],
    [ "eDecisionMakerEvents.h", "db/d50/e_decision_maker_events_8h.html", "db/d50/e_decision_maker_events_8h" ],
    [ "eEmergencyPedVoices.h", "d9/d48/e_emergency_ped_voices_8h.html", "d9/d48/e_emergency_ped_voices_8h" ],
    [ "eEntityStatus.h", "d2/db7/plugin__sa_2game__sa_2e_entity_status_8h.html", "d2/db7/plugin__sa_2game__sa_2e_entity_status_8h" ],
    [ "eEntityType.h", "d7/de6/e_entity_type_8h.html", "d7/de6/e_entity_type_8h" ],
    [ "eEventType.h", "d5/dc1/plugin__sa_2game__sa_2e_event_type_8h.html", "d5/dc1/plugin__sa_2game__sa_2e_event_type_8h" ],
    [ "eGangID.h", "d9/d1d/e_gang_i_d_8h.html", "d9/d1d/e_gang_i_d_8h" ],
    [ "eModelID.h", "d0/d74/e_model_i_d_8h.html", "d0/d74/e_model_i_d_8h" ],
    [ "ePadButtons.h", "d9/dff/e_pad_buttons_8h.html", "d9/dff/e_pad_buttons_8h" ],
    [ "ePedAnims.h", "da/d00/e_ped_anims_8h.html", "da/d00/e_ped_anims_8h" ],
    [ "ePedBones.h", "d4/d81/e_ped_bones_8h.html", "d4/d81/e_ped_bones_8h" ],
    [ "ePedModel.h", "d9/d1e/plugin__sa_2game__sa_2e_ped_model_8h.html", "d9/d1e/plugin__sa_2game__sa_2e_ped_model_8h" ],
    [ "ePedPieceTypes.h", "df/db1/plugin__sa_2game__sa_2e_ped_piece_types_8h.html", "df/db1/plugin__sa_2game__sa_2e_ped_piece_types_8h" ],
    [ "ePedState.h", "d1/db6/e_ped_state_8h.html", "d1/db6/e_ped_state_8h" ],
    [ "ePedType.h", "db/dcc/plugin__sa_2game__sa_2e_ped_type_8h.html", "db/dcc/plugin__sa_2game__sa_2e_ped_type_8h" ],
    [ "eRadioID.h", "d9/de6/e_radio_i_d_8h.html", "d9/de6/e_radio_i_d_8h" ],
    [ "eScriptCommands.h", "d8/d15/plugin__sa_2game__sa_2e_script_commands_8h.html", "d8/d15/plugin__sa_2game__sa_2e_script_commands_8h" ],
    [ "eSoundID.h", "de/dda/e_sound_i_d_8h.html", "de/dda/e_sound_i_d_8h" ],
    [ "eSprintType.h", "d9/d12/e_sprint_type_8h.html", "d9/d12/e_sprint_type_8h" ],
    [ "eStatModAbilities.h", "d5/d8b/e_stat_mod_abilities_8h.html", "d5/d8b/e_stat_mod_abilities_8h" ],
    [ "eStats.h", "d4/d72/e_stats_8h.html", "d4/d72/e_stats_8h" ],
    [ "eStatsReactions.h", "db/de9/e_stats_reactions_8h.html", "db/de9/e_stats_reactions_8h" ],
    [ "eSurfaceType.h", "d7/d36/e_surface_type_8h.html", "d7/d36/e_surface_type_8h" ],
    [ "eTaskType.h", "d3/d25/e_task_type_8h.html", "d3/d25/e_task_type_8h" ],
    [ "eVehicleClass.h", "d2/d2c/e_vehicle_class_8h.html", "d2/d2c/e_vehicle_class_8h" ],
    [ "eVehicleHandlingFlags.h", "d0/d3a/e_vehicle_handling_flags_8h.html", "d0/d3a/e_vehicle_handling_flags_8h" ],
    [ "eVehicleHandlingModelFlags.h", "df/dd6/plugin__sa_2game__sa_2e_vehicle_handling_model_flags_8h.html", "df/dd6/plugin__sa_2game__sa_2e_vehicle_handling_model_flags_8h" ],
    [ "eWeaponFire.h", "d1/dd4/plugin__sa_2game__sa_2e_weapon_fire_8h.html", "d1/dd4/plugin__sa_2game__sa_2e_weapon_fire_8h" ],
    [ "eWeaponFlags.h", "d4/d75/e_weapon_flags_8h.html", "d4/d75/e_weapon_flags_8h" ],
    [ "eWeaponModel.h", "de/d0d/plugin__sa_2game__sa_2e_weapon_model_8h.html", "de/d0d/plugin__sa_2game__sa_2e_weapon_model_8h" ],
    [ "eWeaponType.h", "dc/dcf/plugin__sa_2game__sa_2e_weapon_type_8h.html", "dc/dcf/plugin__sa_2game__sa_2e_weapon_type_8h" ],
    [ "eWinchType.h", "d4/d9c/e_winch_type_8h.html", "d4/d9c/e_winch_type_8h" ],
    [ "Fx_c.cpp", "d1/d10/_fx__c_8cpp.html", "d1/d10/_fx__c_8cpp" ],
    [ "Fx_c.h", "d6/d13/_fx__c_8h.html", "d6/d13/_fx__c_8h" ],
    [ "FxBox_c.cpp", "d5/dea/_fx_box__c_8cpp.html", null ],
    [ "FxBox_c.h", "d1/dba/_fx_box__c_8h.html", "d1/dba/_fx_box__c_8h" ],
    [ "FxEmitterBP_c.h", "db/dcf/_fx_emitter_b_p__c_8h.html", "db/dcf/_fx_emitter_b_p__c_8h" ],
    [ "FxFrustumInfo_c.cpp", "d5/dc7/_fx_frustum_info__c_8cpp.html", null ],
    [ "FxFrustumInfo_c.h", "d6/da0/_fx_frustum_info__c_8h.html", "d6/da0/_fx_frustum_info__c_8h" ],
    [ "FxInfoManager_c.h", "d9/d2f/_fx_info_manager__c_8h.html", "d9/d2f/_fx_info_manager__c_8h" ],
    [ "FxManager_c.cpp", "d4/db3/_fx_manager__c_8cpp.html", "d4/db3/_fx_manager__c_8cpp" ],
    [ "FxManager_c.h", "df/da4/_fx_manager__c_8h.html", "df/da4/_fx_manager__c_8h" ],
    [ "FxMemoryPool_c.cpp", "df/dfa/_fx_memory_pool__c_8cpp.html", null ],
    [ "FxMemoryPool_c.h", "d3/d94/_fx_memory_pool__c_8h.html", "d3/d94/_fx_memory_pool__c_8h" ],
    [ "FxPlane_c.cpp", "d7/d00/_fx_plane__c_8cpp.html", null ],
    [ "FxPlane_c.h", "d6/d61/_fx_plane__c_8h.html", "d6/d61/_fx_plane__c_8h" ],
    [ "FxPrimBP_c.h", "d6/da6/_fx_prim_b_p__c_8h.html", "d6/da6/_fx_prim_b_p__c_8h" ],
    [ "FxPrtMult_c.cpp", "dc/daa/_fx_prt_mult__c_8cpp.html", null ],
    [ "FxPrtMult_c.h", "df/d9d/_fx_prt_mult__c_8h.html", "df/d9d/_fx_prt_mult__c_8h" ],
    [ "FxSphere_c.cpp", "d9/d0d/_fx_sphere__c_8cpp.html", null ],
    [ "FxSphere_c.h", "d6/de2/_fx_sphere__c_8h.html", "d6/de2/_fx_sphere__c_8h" ],
    [ "FxSystem_c.cpp", "dd/de7/_fx_system__c_8cpp.html", null ],
    [ "FxSystem_c.h", "d6/d4b/_fx_system__c_8h.html", "d6/d4b/_fx_system__c_8h" ],
    [ "FxSystemBP_c.cpp", "d4/d74/_fx_system_b_p__c_8cpp.html", null ],
    [ "FxSystemBP_c.h", "df/def/_fx_system_b_p__c_8h.html", "df/def/_fx_system_b_p__c_8h" ],
    [ "IplDef.h", "dc/d4e/_ipl_def_8h.html", "dc/d4e/_ipl_def_8h" ],
    [ "JPegCompress.cpp", "d7/ded/_j_peg_compress_8cpp.html", "d7/ded/_j_peg_compress_8cpp" ],
    [ "JPegCompress.h", "d8/db1/_j_peg_compress_8h.html", "d8/db1/_j_peg_compress_8h" ],
    [ "List_c.cpp", "d8/d75/_list__c_8cpp.html", null ],
    [ "List_c.h", "de/d34/_list__c_8h.html", "de/d34/_list__c_8h" ],
    [ "ListItem_c.cpp", "db/d79/_list_item__c_8cpp.html", null ],
    [ "ListItem_c.h", "d4/d5b/_list_item__c_8h.html", [
      [ "ListItem_c", "d3/d3f/class_list_item__c.html", "d3/d3f/class_list_item__c" ]
    ] ],
    [ "NodeName.cpp", "df/ddb/plugin__sa_2game__sa_2_node_name_8cpp.html", "df/ddb/plugin__sa_2game__sa_2_node_name_8cpp" ],
    [ "NodeName.h", "dd/d17/plugin__sa_2game__sa_2_node_name_8h.html", "dd/d17/plugin__sa_2game__sa_2_node_name_8h" ],
    [ "PipelinePlugin.cpp", "d5/d34/_pipeline_plugin_8cpp.html", "d5/d34/_pipeline_plugin_8cpp" ],
    [ "PipelinePlugin.h", "d1/d59/_pipeline_plugin_8h.html", "d1/d59/_pipeline_plugin_8h" ],
    [ "RenderWare.cpp", "d7/d8b/plugin__sa_2game__sa_2_render_ware_8cpp.html", "d7/d8b/plugin__sa_2game__sa_2_render_ware_8cpp" ],
    [ "RenderWare.h", "de/d9e/plugin__sa_2game__sa_2_render_ware_8h.html", "de/d9e/plugin__sa_2game__sa_2_render_ware_8h" ],
    [ "RpHAnimBlendInterpFrame.h", "db/d28/_rp_h_anim_blend_interp_frame_8h.html", "db/d28/_rp_h_anim_blend_interp_frame_8h" ],
    [ "RwObjectNameIdAssocation.h", "df/d94/plugin__sa_2game__sa_2_rw_object_name_id_assocation_8h.html", "df/d94/plugin__sa_2game__sa_2_rw_object_name_id_assocation_8h" ],
    [ "SArray.h", "de/d96/_s_array_8h.html", "de/d96/_s_array_8h" ],
    [ "tBikeHandlingData.h", "db/d5f/plugin__sa_2game__sa_2t_bike_handling_data_8h.html", "db/d5f/plugin__sa_2game__sa_2t_bike_handling_data_8h" ],
    [ "tBinaryIplFile.h", "d7/df8/t_binary_ipl_file_8h.html", "d7/df8/t_binary_ipl_file_8h" ],
    [ "tBoatHandlingData.h", "d6/d78/plugin__sa_2game__sa_2t_boat_handling_data_8h.html", "d6/d78/plugin__sa_2game__sa_2t_boat_handling_data_8h" ],
    [ "tFlyingHandlingData.h", "d9/d7d/plugin__sa_2game__sa_2t_flying_handling_data_8h.html", "d9/d7d/plugin__sa_2game__sa_2t_flying_handling_data_8h" ],
    [ "tHandlingData.h", "de/dea/plugin__sa_2game__sa_2t_handling_data_8h.html", "de/dea/plugin__sa_2game__sa_2t_handling_data_8h" ],
    [ "tPickupMessage.h", "de/d4d/t_pickup_message_8h.html", "de/d4d/t_pickup_message_8h" ],
    [ "tTransmissionGear.h", "da/d50/plugin__sa_2game__sa_2t_transmission_gear_8h.html", "da/d50/plugin__sa_2game__sa_2t_transmission_gear_8h" ],
    [ "TxdDef.cpp", "d2/d96/_txd_def_8cpp.html", null ],
    [ "TxdDef.h", "dc/dfb/plugin__sa_2game__sa_2_txd_def_8h.html", "dc/dfb/plugin__sa_2game__sa_2_txd_def_8h" ]
];