var hierarchy =
[
    [ "_ProjectionParam", "d7/d5c/struct___projection_param.html", null ],
    [ "_rpD3D9VertexShaderDescriptor", "df/d21/struct__rp_d3_d9_vertex_shader_descriptor.html", null ],
    [ "_rpD3D9VertexShaderDispatchDescriptor", "d6/df0/struct__rp_d3_d9_vertex_shader_dispatch_descriptor.html", null ],
    [ "_rpUVAnimCustomData", "df/d20/struct__rp_u_v_anim_custom_data.html", null ],
    [ "_rwIEEEFloatShapeType", "d0/dcb/union__rw_i_e_e_e_float_shape_type.html", null ],
    [ "_rwIm3DPoolStash", "d1/ded/struct__rw_im3_d_pool_stash.html", null ],
    [ "_RwInt128", "dc/d73/struct___rw_int128.html", null ],
    [ "_RwInt64", "df/d18/struct___rw_int64.html", null ],
    [ "_rwPalQuantBranchNode", "d0/d5d/struct__rw_pal_quant_branch_node.html", null ],
    [ "_rwPalQuantLeafNode", "d5/d93/struct__rw_pal_quant_leaf_node.html", null ],
    [ "_rwPalQuantOctNode", "dd/dc8/struct__rw_pal_quant_oct_node.html", null ],
    [ "_rwPalQuantRGBABox", "d0/da0/struct__rw_pal_quant_r_g_b_a_box.html", null ],
    [ "_RwUInt128", "d5/d5d/struct___rw_u_int128.html", null ],
    [ "_RwUInt64", "de/db6/struct___rw_u_int64.html", null ],
    [ "injector::address_translator", "d7/d4c/classinjector_1_1address__translator.html", null ],
    [ "injector::address_translator_manager", "d7/d7f/classinjector_1_1address__translator__manager.html", null ],
    [ "airstrip_info", "d0/d6b/structairstrip__info.html", null ],
    [ "CVisibilityPlugins::AlphaObjectInfo", "d6/ddb/struct_c_visibility_plugins_1_1_alpha_object_info.html", null ],
    [ "AnimAssociationData", "d9/d8b/class_anim_association_data.html", null ],
    [ "AnimBlendFrameData", "db/dec/struct_anim_blend_frame_data.html", null ],
    [ "plugin::ArgPick< TypesList, Indices >", "d0/d78/structplugin_1_1_arg_pick.html", null ],
    [ "plugin::ArgPick< ArgTypes< Types... >, Indices... >", "d6/dd6/structplugin_1_1_arg_pick_3_01_arg_types_3_01_types_8_8_8_01_4_00_01_indices_8_8_8_01_4.html", null ],
    [ "plugin::ArgTypes< Types >", "d0/dec/structplugin_1_1_arg_types.html", null ],
    [ "injector::auto_pointer", "d5/d8e/unioninjector_1_1auto__pointer.html", null ],
    [ "plugin::BaseEvent< Injector, RList, Priority, ArgPicker, Prototype >", "dc/d03/classplugin_1_1_base_event.html", null ],
    [ "plugin::BaseEvent< Injector, RList, Priority, ArgPicker, Ret(Args...)>", "d8/db8/classplugin_1_1_base_event_3_01_injector_00_01_r_list_00_01_priority_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "plugin::BaseEventI< Injector, RList, ArgPicker, Prototype >", "d8/d5b/classplugin_1_1_base_event_i.html", null ],
    [ "plugin::BaseEventI< Injector, RList, ArgPicker, Ret(Args...)>", "dd/d30/classplugin_1_1_base_event_i_3_01_injector_00_01_r_list_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "injector::basic_memory_pointer< MemTranslator >", "db/d5a/unioninjector_1_1basic__memory__pointer.html", null ],
    [ "injector::basic_memory_pointer< address_manager::fn_mem_translator_nop >", "db/d5a/unioninjector_1_1basic__memory__pointer.html", null ],
    [ "C2dEffect", "d7/d22/class_c2d_effect.html", null ],
    [ "C3dMarker", "d4/d71/class_c3d_marker.html", null ],
    [ "C3dMarkers", "d2/d54/class_c3d_markers.html", null ],
    [ "CAEAudioEntity", "d7/dba/class_c_a_e_audio_entity.html", [
      [ "CAEExplosionAudioEntity", "da/d73/class_c_a_e_explosion_audio_entity.html", null ],
      [ "CAEFireAudioEntity", "d1/dd8/class_c_a_e_fire_audio_entity.html", null ],
      [ "CAEPedAudioEntity", "d2/d69/class_c_a_e_ped_audio_entity.html", null ],
      [ "CAEPedSpeechAudioEntity", "d3/d5f/class_c_a_e_ped_speech_audio_entity.html", null ],
      [ "CAEPoliceScannerAudioEntity", "db/d35/class_c_a_e_police_scanner_audio_entity.html", null ],
      [ "CAETwinLoopSoundEntity", "de/d5f/class_c_a_e_twin_loop_sound_entity.html", null ],
      [ "CAEVehicleAudioEntity", "da/d54/class_c_a_e_vehicle_audio_entity.html", null ],
      [ "CAEWeaponAudioEntity", "da/d63/class_c_a_e_weapon_audio_entity.html", null ],
      [ "CAEWeatherAudioEntity", "d9/d79/class_c_a_e_weather_audio_entity.html", null ]
    ] ],
    [ "CAERadioTrackManager", "dc/d95/class_c_a_e_radio_track_manager.html", null ],
    [ "CAESound", "d8/d06/class_c_a_e_sound.html", null ],
    [ "plugin::CallingConventions", "d4/d1b/structplugin_1_1_calling_conventions.html", null ],
    [ "CAnimationStyleDescriptor", "d2/d4d/class_c_animation_style_descriptor.html", null ],
    [ "CAnimBlendAssocGroup", "db/d96/class_c_anim_blend_assoc_group.html", null ],
    [ "CAnimBlendAssociation", "d1/d19/class_c_anim_blend_association.html", null ],
    [ "CAnimBlendClumpData", "d5/de0/class_c_anim_blend_clump_data.html", null ],
    [ "CAnimBlendHierarchy", "d9/ddf/class_c_anim_blend_hierarchy.html", null ],
    [ "CAnimBlendNode", "da/d69/class_c_anim_blend_node.html", null ],
    [ "CAnimBlendSequence", "da/d91/class_c_anim_blend_sequence.html", null ],
    [ "CAnimBlendStaticAssociation", "d2/d6a/class_c_anim_blend_static_association.html", null ],
    [ "CAnimBlock", "d9/d31/class_c_anim_block.html", null ],
    [ "CAnimManager", "db/d93/class_c_anim_manager.html", null ],
    [ "CAttractorScanner", "df/d85/class_c_attractor_scanner.html", null ],
    [ "CAudioHydrant", "d8/d82/class_c_audio_hydrant.html", null ],
    [ "cAudioManager", "da/d67/classc_audio_manager.html", null ],
    [ "cAudioScriptObject", "d0/d0d/classc_audio_script_object.html", null ],
    [ "CAutoPilot", "df/d82/class_c_auto_pilot.html", null ],
    [ "CBaseModelInfo", "de/d97/class_c_base_model_info.html", [
      [ "CAtomicModelInfo", "d2/dca/class_c_atomic_model_info.html", null ],
      [ "CClumpModelInfo", "dc/df8/class_c_clump_model_info.html", [
        [ "C2deffectsModelInfo", "db/de9/class_c2deffects_model_info.html", null ],
        [ "CMloModelInfo", "d9/d82/class_c_mlo_model_info.html", null ],
        [ "CPedModelInfo", "d2/dd6/class_c_ped_model_info.html", null ],
        [ "CVehicleModelInfo", "db/da8/class_c_vehicle_model_info.html", null ],
        [ "CWeaponModelInfo", "d9/d60/class_c_weapon_model_info.html", null ],
        [ "CXtraCompsModelInfo", "d8/d8d/class_c_xtra_comps_model_info.html", null ]
      ] ],
      [ "CSimpleModelInfo", "d1/d2b/class_c_simple_model_info.html", [
        [ "CTimeModelInfo", "da/d32/class_c_time_model_info.html", null ]
      ] ]
    ] ],
    [ "CBird", "d7/d56/class_c_bird.html", null ],
    [ "CBirds", "da/d69/class_c_birds.html", null ],
    [ "CBouncingPanel", "db/d1f/class_c_bouncing_panel.html", null ],
    [ "CBox", "d3/d7d/class_c_box.html", [
      [ "CBoundingBox", "de/dc8/class_c_bounding_box.html", null ],
      [ "CColBox", "d7/def/class_c_col_box.html", null ]
    ] ],
    [ "CBridge", "d7/dcf/class_c_bridge.html", null ],
    [ "CBrightLight", "de/d6d/class_c_bright_light.html", null ],
    [ "CBrightLights", "d2/d17/class_c_bright_lights.html", null ],
    [ "CBulletInfo", "d9/dfa/class_c_bullet_info.html", null ],
    [ "CBulletTrace", "db/d07/class_c_bullet_trace.html", null ],
    [ "CBulletTraces", "d1/d5d/class_c_bullet_traces.html", null ],
    [ "CCam", "d9/de3/class_c_cam.html", null ],
    [ "CCamPathSplines", "d8/dd9/class_c_cam_path_splines.html", null ],
    [ "CCarAI", "df/dc9/class_c_car_a_i.html", null ],
    [ "CCarCtrl", "d3/d05/class_c_car_ctrl.html", null ],
    [ "CCarEnterExit", "df/da9/class_c_car_enter_exit.html", null ],
    [ "CCarGenerator", "d1/de2/class_c_car_generator.html", null ],
    [ "CCarPathLink", "dd/d2a/class_c_car_path_link.html", null ],
    [ "CCarPathLinkAddress", "da/df6/class_c_car_path_link_address.html", null ],
    [ "CCheat", "d1/d35/class_c_cheat.html", null ],
    [ "CCheckpoint", "d2/d75/class_c_checkpoint.html", null ],
    [ "CCheckpoints", "da/d92/class_c_checkpoints.html", null ],
    [ "CClock", "d6/d3e/class_c_clock.html", null ],
    [ "CClothes", "de/db2/class_c_clothes.html", null ],
    [ "CClothesBuilder", "d5/ddb/class_c_clothes_builder.html", null ],
    [ "CClouds", "d4/dcc/class_c_clouds.html", null ],
    [ "CColDisk", "d6/d85/class_c_col_disk.html", null ],
    [ "CColLine", "d9/d81/class_c_col_line.html", null ],
    [ "CCollision", "dc/dc5/class_c_collision.html", null ],
    [ "CCollisionData", "d6/d63/class_c_collision_data.html", null ],
    [ "CColModel", "d4/de8/class_c_col_model.html", null ],
    [ "CColourSet", "dc/dd6/class_c_colour_set.html", null ],
    [ "CColPoint", "d0/d98/class_c_col_point.html", null ],
    [ "CColTriangle", "d0/d13/class_c_col_triangle.html", null ],
    [ "CColTrianglePlane", "d5/d7e/class_c_col_triangle_plane.html", null ],
    [ "CControllerAction", "d5/dcf/class_c_controller_action.html", null ],
    [ "CControllerConfigManager", "dd/d51/class_c_controller_config_manager.html", null ],
    [ "CControllerKey", "d9/d43/class_c_controller_key.html", null ],
    [ "CControllerState", "dd/da2/class_c_controller_state.html", null ],
    [ "CCoronas", "d8/d3d/class_c_coronas.html", null ],
    [ "CCover", "dc/d2d/class_c_cover.html", null ],
    [ "CCoverPoint", "d2/d3e/class_c_cover_point.html", null ],
    [ "CCrane", "d1/dfa/class_c_crane.html", null ],
    [ "CCranes", "df/dc9/class_c_cranes.html", null ],
    [ "CCredits", "d2/d38/class_c_credits.html", null ],
    [ "CCreepingFire", "d0/dcf/class_c_creeping_fire.html", null ],
    [ "CCrimeBeingQd", "db/dc2/class_c_crime_being_qd.html", null ],
    [ "CCurrentVehicle", "d2/d22/class_c_current_vehicle.html", null ],
    [ "CCustomCarEnvMapPipeline", "dd/de2/class_c_custom_car_env_map_pipeline.html", null ],
    [ "CCustomCarPlateMgr", "df/df2/class_c_custom_car_plate_mgr.html", null ],
    [ "CCutsceneMgr", "d3/dbb/class_c_cutscene_mgr.html", null ],
    [ "CCutsceneShadow", "dc/d1f/class_c_cutscene_shadow.html", null ],
    [ "CDamageManager", "d3/d94/class_c_damage_manager.html", null ],
    [ "CDarkel", "d3/dcc/class_c_darkel.html", null ],
    [ "CDate", "d9/d78/class_c_date.html", null ],
    [ "CDecision", "d3/d39/class_c_decision.html", null ],
    [ "CDecisionMaker", "dc/df7/class_c_decision_maker.html", null ],
    [ "CDecisionSimple", "d7/dd5/class_c_decision_simple.html", null ],
    [ "plugin::CallingConventions::Cdecl", "de/dce/structplugin_1_1_calling_conventions_1_1_cdecl.html", null ],
    [ "CDirectory", "d4/d0d/class_c_directory.html", null ],
    [ "CDoor", "db/d83/class_c_door.html", null ],
    [ "CDraw", "d8/d22/class_c_draw.html", null ],
    [ "CEntityScanner", "db/d02/class_c_entity_scanner.html", null ],
    [ "CEntryExit", "d6/d4c/class_c_entry_exit.html", null ],
    [ "CEntryExitManager", "db/d56/class_c_entry_exit_manager.html", null ],
    [ "CEntryInfoList", "d6/d1e/class_c_entry_info_list.html", null ],
    [ "CEntryInfoNode", "d9/d71/class_c_entry_info_node.html", null ],
    [ "CEscalators", "de/d25/class_c_escalators.html", null ],
    [ "CEvent", "dc/d8f/class_c_event.html", null ],
    [ "CEventGroup", "df/dd0/class_c_event_group.html", null ],
    [ "CEventHandler", "d5/d08/class_c_event_handler.html", null ],
    [ "CEventList", "dc/d1a/class_c_event_list.html", null ],
    [ "CEventScanner", "df/daa/class_c_event_scanner.html", null ],
    [ "CExplosion", "d5/ddd/class_c_explosion.html", null ],
    [ "CFileCarGenerator", "db/d64/class_c_file_car_generator.html", null ],
    [ "CFileLoader", "db/d75/class_c_file_loader.html", null ],
    [ "CFileMgr", "df/d51/class_c_file_mgr.html", null ],
    [ "CFileObjectInstance", "db/d9a/class_c_file_object_instance.html", null ],
    [ "CFire", "d3/d7a/class_c_fire.html", null ],
    [ "CFireManager", "d7/d55/class_c_fire_manager.html", null ],
    [ "CFont", "dc/dd4/class_c_font.html", null ],
    [ "CFontDetails", "db/df1/class_c_font_details.html", null ],
    [ "CForbiddenArea", "dd/dbf/class_c_forbidden_area.html", null ],
    [ "CFormation", "d6/d81/class_c_formation.html", null ],
    [ "CGame", "d2/de6/class_c_game.html", null ],
    [ "CGameLogic", "d6/db2/class_c_game_logic.html", null ],
    [ "CGamma", "d7/d62/class_c_gamma.html", null ],
    [ "CGangInfo", "dc/d7a/class_c_gang_info.html", null ],
    [ "CGangs", "de/d13/class_c_gangs.html", null ],
    [ "CGangWars", "d0/d9b/class_c_gang_wars.html", null ],
    [ "CGangWarsSaveStructure", "da/d3a/class_c_gang_wars_save_structure.html", null ],
    [ "CGarage", "d1/d17/class_c_garage.html", null ],
    [ "CGarages", "d6/d1c/class_c_garages.html", null ],
    [ "CGeneral", "db/d2a/class_c_general.html", null ],
    [ "CGenericGameStorage", "d2/d8e/class_c_generic_game_storage.html", null ],
    [ "CGridRef", "de/dbc/class_c_grid_ref.html", null ],
    [ "cHandlingDataMgr", "d3/ddd/classc_handling_data_mgr.html", null ],
    [ "CHud", "db/d4f/class_c_hud.html", null ],
    [ "CHudColour", "d7/dfd/class_c_hud_colour.html", null ],
    [ "CHudColours", "d1/dff/class_c_hud_colours.html", null ],
    [ "CIniFile", "d4/d65/class_c_ini_file.html", null ],
    [ "CIplStore", "d8/d89/class_c_ipl_store.html", null ],
    [ "CKeyboardState", "d5/da2/class_c_keyboard_state.html", null ],
    [ "CKeyGen", "da/d1b/class_c_key_gen.html", null ],
    [ "CLines", "d3/d44/class_c_lines.html", null ],
    [ "CLink< T >", "d4/d28/class_c_link.html", null ],
    [ "CLink< CAnimBlendHierarchy * >", "d4/d28/class_c_link.html", null ],
    [ "CLink< CEntity * >", "d4/d28/class_c_link.html", null ],
    [ "CLinkList< T >", "d8/d4d/class_c_link_list.html", null ],
    [ "CLinkList< CAnimBlendHierarchy * >", "d8/d4d/class_c_link_list.html", null ],
    [ "CLinkList< CEntity * >", "d8/d4d/class_c_link_list.html", null ],
    [ "CLoadedCarGroup", "db/ded/class_c_loaded_car_group.html", null ],
    [ "CLoadingScreen", "da/d0c/class_c_loading_screen.html", null ],
    [ "CLocalisation", "d2/d2e/class_c_localisation.html", null ],
    [ "ClumpModelStore", "db/d7c/struct_clump_model_store.html", null ],
    [ "CMatrix", "d2/dcb/class_c_matrix.html", [
      [ "CMatrixLink", "d2/d57/class_c_matrix_link.html", null ]
    ] ],
    [ "CMenuScreen::CMenuEntry", "de/d96/struct_c_menu_screen_1_1_c_menu_entry.html", null ],
    [ "CMenuManager", "dd/d4d/class_c_menu_manager.html", null ],
    [ "CMenuPage", "d2/d80/struct_c_menu_page.html", null ],
    [ "CMenuPageButton", "d5/db7/struct_c_menu_page_button.html", null ],
    [ "CMenuScreen", "da/d58/struct_c_menu_screen.html", null ],
    [ "CMenuSystem", "d6/d5c/class_c_menu_system.html", null ],
    [ "CMessages", "d9/d0e/class_c_messages.html", null ],
    [ "CMirrors", "d9/d4b/class_c_mirrors.html", null ],
    [ "CMissionCleanup", "d4/d6a/class_c_mission_cleanup.html", null ],
    [ "CModelInfo", "dd/df3/class_c_model_info.html", null ],
    [ "CModelInfoAccelerator", "dd/d03/class_c_model_info_accelerator.html", null ],
    [ "CMotionBlurStreaks", "d4/d5e/class_c_motion_blur_streaks.html", null ],
    [ "CMouseControllerState", "d2/d53/class_c_mouse_controller_state.html", null ],
    [ "CMousePointerStateHelper", "d7/d1b/class_c_mouse_pointer_state_helper.html", null ],
    [ "CMovie", "d0/d7c/class_c_movie.html", null ],
    [ "cMusicManager", "d9/de4/classc_music_manager.html", null ],
    [ "CNodeAddress", "de/dd2/class_c_node_address.html", null ],
    [ "CObjectData", "dc/dfe/class_c_object_data.html", null ],
    [ "CObjectInfo", "d8/d99/class_c_object_info.html", null ],
    [ "COctTree", "da/d96/class_c_oct_tree.html", [
      [ "COctTreeBase", "d9/dae/class_c_oct_tree_base.html", null ]
    ] ],
    [ "CompressedVector", "dc/d2d/class_compressed_vector.html", null ],
    [ "CompressedVector2D", "d7/d7f/class_compressed_vector2_d.html", null ],
    [ "COneSheet", "d8/def/class_c_one_sheet.html", null ],
    [ "plugin::config_file", "d8/d7f/classplugin_1_1config__file.html", null ],
    [ "plugin::config_helper", "d7/d0b/classplugin_1_1config__helper.html", null ],
    [ "plugin::config_parameter", "d3/d2f/classplugin_1_1config__parameter.html", [
      [ "plugin::config_param_line", "de/dd5/classplugin_1_1config__param__line.html", null ]
    ] ],
    [ "COnscreenCounterEntry", "d1/d06/class_c_onscreen_counter_entry.html", null ],
    [ "COnscreenTimer", "d5/d7d/class_c_onscreen_timer.html", null ],
    [ "COnscreenTimerEntry", "db/d73/class_c_onscreen_timer_entry.html", null ],
    [ "CPad", "df/d71/class_c_pad.html", null ],
    [ "CPager", "d8/dd1/class_c_pager.html", null ],
    [ "CParticle", "da/dfa/class_c_particle.html", null ],
    [ "cParticleSystemMgr", "d0/dab/classc_particle_system_mgr.html", null ],
    [ "CPathFind", "d0/d4c/class_c_path_find.html", null ],
    [ "CPathIntersectionInfo", "df/dbd/class_c_path_intersection_info.html", null ],
    [ "CPathNode", "d3/d8d/class_c_path_node.html", null ],
    [ "CPathSpline", "d0/d90/struct_c_path_spline.html", null ],
    [ "CPathSplines", "df/d6b/struct_c_path_splines.html", null ],
    [ "CPedAcquaintance", "d3/dfa/class_c_ped_acquaintance.html", null ],
    [ "CPedClothesDesc", "d9/dc2/class_c_ped_clothes_desc.html", null ],
    [ "CPedGroup", "da/d1b/class_c_ped_group.html", null ],
    [ "CPedGroupIntelligence", "d6/df1/class_c_ped_group_intelligence.html", null ],
    [ "CPedGroupMembership", "d3/da2/class_c_ped_group_membership.html", null ],
    [ "CPedGroupPlacer", "dc/dac/class_c_ped_group_placer.html", null ],
    [ "CPedGroups", "df/dba/class_c_ped_groups.html", null ],
    [ "CPedIK", "d8/d67/class_c_ped_i_k.html", null ],
    [ "CPedIntelligence", "d0/d01/class_c_ped_intelligence.html", null ],
    [ "CPedList", "d2/d5a/class_c_ped_list.html", null ],
    [ "CPedPlacement", "de/d1d/class_c_ped_placement.html", null ],
    [ "CPedStats", "de/d3b/class_c_ped_stats.html", null ],
    [ "CPedTaskPair", "d7/d23/class_c_ped_task_pair.html", null ],
    [ "CPedType", "d6/d7f/class_c_ped_type.html", null ],
    [ "CPermanentShadow", "d4/dc8/class_c_permanent_shadow.html", null ],
    [ "CPhone", "d6/d32/class_c_phone.html", null ],
    [ "CPhoneInfo", "dc/d01/class_c_phone_info.html", null ],
    [ "CPickup", "d3/d77/class_c_pickup.html", null ],
    [ "CPickups", "d5/d8c/class_c_pickups.html", null ],
    [ "CPlaceable", "dc/db4/class_c_placeable.html", [
      [ "CCamera", "da/d7c/class_c_camera.html", null ],
      [ "CEntity", "dc/d7b/class_c_entity.html", [
        [ "CBuilding", "d1/d8a/class_c_building.html", [
          [ "CAnimatedBuilding", "d1/dcf/class_c_animated_building.html", null ],
          [ "CTreadable", "d5/dd3/class_c_treadable.html", null ]
        ] ],
        [ "CDummy", "d0/d2a/class_c_dummy.html", [
          [ "CDummyObject", "d5/d57/class_c_dummy_object.html", null ],
          [ "CDummyPed", "d9/dd1/class_c_dummy_ped.html", null ]
        ] ],
        [ "CPhysical", "d5/da5/class_c_physical.html", [
          [ "CObject", "dc/dac/class_c_object.html", [
            [ "CCutsceneObject", "d3/dd4/class_c_cutscene_object.html", [
              [ "CCutsceneHead", "d4/d10/class_c_cutscene_head.html", null ]
            ] ],
            [ "CHandObject", "da/d3d/class_c_hand_object.html", null ],
            [ "CProjectile", "d6/d30/class_c_projectile.html", null ]
          ] ],
          [ "CPed", "dd/d6b/class_c_ped.html", [
            [ "CCivilianPed", "d1/d2f/class_c_civilian_ped.html", null ],
            [ "CCopPed", "d8/dab/class_c_cop_ped.html", null ],
            [ "CEmergencyPed", "d8/def/class_c_emergency_ped.html", null ],
            [ "CPlayerPed", "d7/de6/class_c_player_ped.html", null ]
          ] ],
          [ "CVehicle", "d8/df2/class_c_vehicle.html", [
            [ "CAutomobile", "d5/d4d/class_c_automobile.html", [
              [ "CMonsterTruck", "df/db9/class_c_monster_truck.html", null ],
              [ "CQuadBike", "dc/dcc/class_c_quad_bike.html", null ],
              [ "CTrailer", "d4/ddd/class_c_trailer.html", null ]
            ] ],
            [ "CBike", "dd/d55/class_c_bike.html", [
              [ "CBmx", "d6/d0d/class_c_bmx.html", null ]
            ] ],
            [ "CBoat", "d0/d87/class_c_boat.html", null ],
            [ "CHeli", "d5/d92/class_c_heli.html", null ],
            [ "CPlane", "dc/d3c/class_c_plane.html", null ],
            [ "CTrain", "dc/d68/class_c_train.html", null ]
          ] ]
        ] ]
      ] ],
      [ "CInstance", "d5/dfa/class_c_instance.html", null ]
    ] ],
    [ "CPlaceName", "df/dc0/class_c_place_name.html", null ],
    [ "CPlaneTrail", "db/d5a/class_c_plane_trail.html", null ],
    [ "CPlaneTrails", "d3/d70/class_c_plane_trails.html", null ],
    [ "CPlayerData", "d6/d8d/class_c_player_data.html", null ],
    [ "CPlayerInfo", "d8/d11/class_c_player_info.html", null ],
    [ "CPlayerSkin", "d9/d90/class_c_player_skin.html", null ],
    [ "CPlayerSkinData", "dd/d3b/class_c_player_skin_data.html", null ],
    [ "CPointLight", "db/dcc/class_c_point_light.html", null ],
    [ "CPointLights", "de/d70/class_c_point_lights.html", null ],
    [ "CPointList", "d6/d7c/class_c_point_list.html", null ],
    [ "CPolyBunch", "d7/d63/class_c_poly_bunch.html", null ],
    [ "CPool< A, B >", "da/d22/class_c_pool.html", null ],
    [ "CPool< cAudioScriptObject >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CBuilding >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CColModel >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CDummy >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CDummy, CDummyObject >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CEntryExit >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CEntryInfoNode >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CObject, CCutsceneHead >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CObject, CCutsceneObject >", "da/d22/class_c_pool.html", null ],
    [ "CPool< COctTree >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPed, CCopPed >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPed, CPlayerPed >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPedIntelligence >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPtrNode >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPtrNodeDoubleLink >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CPtrNodeSingleLink >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CQuadTreeNode >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CTask, char[128]>", "da/d22/class_c_pool.html", null ],
    [ "CPool< CTreadable >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CustomEnvMapPipeAtomicData >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CustomEnvMapPipeMaterialData >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CustomSpecMapPipeMaterialData >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CVehicle, CAutomobile >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CVehicle, CHeli >", "da/d22/class_c_pool.html", null ],
    [ "CPool< CVehicleModelInfo >", "da/d22/class_c_pool.html", null ],
    [ "CPool< IplDef >", "da/d22/class_c_pool.html", null ],
    [ "CPool< T1, T2 >", "da/d22/class_c_pool.html", null ],
    [ "CPool< TxdDef >", "da/d22/class_c_pool.html", null ],
    [ "CPools", "d6/db0/class_c_pools.html", null ],
    [ "CPopCycle", "de/de3/class_c_pop_cycle.html", null ],
    [ "CPopulation", "d8/d4f/class_c_population.html", null ],
    [ "CProjectileInfo", "d5/d7d/class_c_projectile_info.html", null ],
    [ "CPtrList", "d4/d31/class_c_ptr_list.html", [
      [ "CPtrListDoubleLink", "d2/d82/class_c_ptr_list_double_link.html", null ],
      [ "CPtrListSingleLink", "d7/d00/class_c_ptr_list_single_link.html", null ]
    ] ],
    [ "CPtrNode", "df/df7/class_c_ptr_node.html", null ],
    [ "CPtrNodeDoubleLink", "d1/d12/class_c_ptr_node_double_link.html", null ],
    [ "CPtrNodeSingleLink", "db/d53/class_c_ptr_node_single_link.html", null ],
    [ "CQuadTreeNode", "d2/d39/class_c_quad_tree_node.html", null ],
    [ "CQuaternion", "d8/d4b/class_c_quaternion.html", null ],
    [ "CQueuedMode", "db/dfa/struct_c_queued_mode.html", null ],
    [ "CRadar", "d4/d2f/class_c_radar.html", null ],
    [ "CRealTimeShadow", "d2/d35/class_c_real_time_shadow.html", null ],
    [ "CRect", "d6/d97/class_c_rect.html", null ],
    [ "CReference", "da/d12/class_c_reference.html", null ],
    [ "CReferences", "db/db1/class_c_references.html", null ],
    [ "CRegisteredCorona", "d5/d18/class_c_registered_corona.html", null ],
    [ "CRegisteredMotionBlurStreak", "d5/de1/class_c_registered_motion_blur_streak.html", null ],
    [ "CRegisteredShadow", "d9/dc5/class_c_registered_shadow.html", null ],
    [ "CRegisteredShinyText", "dd/d0d/class_c_registered_shiny_text.html", null ],
    [ "CRemote", "d7/d24/class_c_remote.html", null ],
    [ "CRenderer", "da/d28/class_c_renderer.html", null ],
    [ "CRepeatSector", "de/d05/class_c_repeat_sector.html", null ],
    [ "CReplay", "d8/d2c/class_c_replay.html", null ],
    [ "CRestart", "d1/dc1/class_c_restart.html", null ],
    [ "CRGBA", "d7/ded/class_c_r_g_b_a.html", null ],
    [ "CRideAnimData", "d5/d6f/class_c_ride_anim_data.html", null ],
    [ "CRoadBlocks", "d1/d81/class_c_road_blocks.html", null ],
    [ "CRope", "d2/d52/class_c_rope.html", null ],
    [ "CRopes", "da/db7/class_c_ropes.html", null ],
    [ "CRubbish", "d4/d1a/class_c_rubbish.html", null ],
    [ "CRunningScript", "da/d50/class_c_running_script.html", null ],
    [ "CScene", "d8/d03/class_c_scene.html", null ],
    [ "CSceneEdit", "d8/d5e/class_c_scene_edit.html", null ],
    [ "CScriptResourceManager", "dd/df2/class_c_script_resource_manager.html", null ],
    [ "CScriptsForBrains", "dc/dbc/class_c_scripts_for_brains.html", null ],
    [ "CSector", "d6/ddf/class_c_sector.html", null ],
    [ "CSetPiece", "d7/d93/class_c_set_piece.html", null ],
    [ "CSetPieces", "d0/d49/class_c_set_pieces.html", null ],
    [ "CShadowCamera", "d1/d8c/class_c_shadow_camera.html", null ],
    [ "CShadows", "d0/dfb/class_c_shadows.html", null ],
    [ "CShinyTexts", "d2/d26/class_c_shiny_texts.html", null ],
    [ "CShotInfo", "d6/d7f/class_c_shot_info.html", null ],
    [ "CSimpleTransform", "de/d01/class_c_simple_transform.html", null ],
    [ "CSpecialFX", "de/d8b/class_c_special_f_x.html", null ],
    [ "CSpecialParticleStuff", "d9/da8/class_c_special_particle_stuff.html", null ],
    [ "CSpecialPlateHandler", "d4/d9e/class_c_special_plate_handler.html", null ],
    [ "CSphere", "df/d8b/class_c_sphere.html", [
      [ "CColSphere", "d1/d8b/class_c_col_sphere.html", null ]
    ] ],
    [ "CSprite", "d3/d0f/class_c_sprite.html", null ],
    [ "CSprite2d", "d9/d9d/class_c_sprite2d.html", null ],
    [ "CStaticShadow", "da/d1d/class_c_static_shadow.html", null ],
    [ "CStats", "df/dd0/class_c_stats.html", null ],
    [ "injector::cstd< Prototype >", "d5/d85/structinjector_1_1cstd.html", null ],
    [ "injector::cstd< Ret(Args...)>", "d0/dd8/structinjector_1_1cstd_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "CStinger", "d3/d26/class_c_stinger.html", null ],
    [ "CStore< ObjectType, Capacity >", "dd/dcb/class_c_store.html", null ],
    [ "CStoredCar", "dc/dd3/class_c_stored_car.html", null ],
    [ "CStoredCollPoly", "dd/dfc/class_c_stored_coll_poly.html", null ],
    [ "CStreamedScripts", "df/d65/class_c_streamed_scripts.html", null ],
    [ "CStreaming", "dc/dd3/class_c_streaming.html", null ],
    [ "CStreamingInfo", "d5/d40/class_c_streaming_info.html", null ],
    [ "CStuckCarCheck", "da/dbf/class_c_stuck_car_check.html", null ],
    [ "CTask", "de/df1/class_c_task.html", [
      [ "CTaskComplex", "d6/d5c/class_c_task_complex.html", [
        [ "CTaskComplexCopInCar", "de/dff/class_c_task_complex_cop_in_car.html", null ],
        [ "CTaskComplexDie", "d4/d08/class_c_task_complex_die.html", null ],
        [ "CTaskComplexEnterBoatAsDriver", "d0/dbe/class_c_task_complex_enter_boat_as_driver.html", null ],
        [ "CTaskComplexEnterCar", "db/dee/class_c_task_complex_enter_car.html", [
          [ "CTaskComplexEnterCarAsDriver", "d8/d41/class_c_task_complex_enter_car_as_driver.html", null ],
          [ "CTaskComplexEnterCarAsPassenger", "df/d57/class_c_task_complex_enter_car_as_passenger.html", null ]
        ] ],
        [ "CTaskComplexFacial", "de/ddd/class_c_task_complex_facial.html", null ],
        [ "CTaskComplexJump", "da/d20/class_c_task_complex_jump.html", [
          [ "CTaskComplexClimb", "d7/d12/class_c_task_complex_climb.html", null ]
        ] ],
        [ "CTaskComplexKillPedFromBoat", "d5/d1c/class_c_task_complex_kill_ped_from_boat.html", null ],
        [ "CTaskComplexKillPedOnFoot", "d7/de1/class_c_task_complex_kill_ped_on_foot.html", null ],
        [ "CTaskComplexLeaveCar", "d5/daa/class_c_task_complex_leave_car.html", null ],
        [ "CTaskComplexPlayHandSignalAnim", "dd/dc4/class_c_task_complex_play_hand_signal_anim.html", null ],
        [ "CTaskComplexProstituteSolicit", "d9/d5b/class_c_task_complex_prostitute_solicit.html", null ],
        [ "CTaskComplexSequence", "d1/d0b/class_c_task_complex_sequence.html", null ],
        [ "CTaskComplexStuckInAir", "d9/d1a/class_c_task_complex_stuck_in_air.html", null ],
        [ "CTaskComplexSunbathe", "d6/d72/class_c_task_complex_sunbathe.html", null ],
        [ "CTaskComplexUseMobilePhone", "db/d85/class_c_task_complex_use_mobile_phone.html", null ],
        [ "CTaskComplexWander", "d8/d9d/class_c_task_complex_wander.html", [
          [ "CTaskComplexWanderStandard", "d8/d03/class_c_task_complex_wander_standard.html", null ]
        ] ]
      ] ],
      [ "CTaskSimple", "d4/da6/class_c_task_simple.html", [
        [ "CTaskSimpleAnim", "d7/dba/class_c_task_simple_anim.html", [
          [ "CTaskSimpleRunAnim", "da/dd3/class_c_task_simple_run_anim.html", null ],
          [ "CTaskSimpleRunNamedAnim", "d8/da8/class_c_task_simple_run_named_anim.html", null ]
        ] ],
        [ "CTaskSimpleCarSetPedInAsDriver", "da/d25/class_c_task_simple_car_set_ped_in_as_driver.html", null ],
        [ "CTaskSimpleCarSetPedInAsPassenger", "d2/d76/class_c_task_simple_car_set_ped_in_as_passenger.html", null ],
        [ "CTaskSimpleCarSetPedOut", "d1/dc0/class_c_task_simple_car_set_ped_out.html", null ],
        [ "CTaskSimpleChoking", "de/d76/class_c_task_simple_choking.html", null ],
        [ "CTaskSimpleClimb", "d7/d4d/class_c_task_simple_climb.html", null ],
        [ "CTaskSimpleDuck", "d4/d8e/class_c_task_simple_duck.html", null ],
        [ "CTaskSimpleDuckToggle", "db/d6e/class_c_task_simple_duck_toggle.html", null ],
        [ "CTaskSimpleFacial", "de/d9d/class_c_task_simple_facial.html", null ],
        [ "CTaskSimpleFight", "d8/d88/class_c_task_simple_fight.html", null ],
        [ "CTaskSimpleGangDriveBy", "db/d57/class_c_task_simple_gang_drive_by.html", null ],
        [ "CTaskSimpleHoldEntity", "df/d39/class_c_task_simple_hold_entity.html", null ],
        [ "CTaskSimpleIKChain", "d1/d9c/class_c_task_simple_i_k_chain.html", [
          [ "CTaskSimpleIKLookAt", "d9/d73/class_c_task_simple_i_k_look_at.html", null ]
        ] ],
        [ "CTaskSimpleIKManager", "de/d9d/class_c_task_simple_i_k_manager.html", null ],
        [ "CTaskSimpleInAir", "d0/de1/class_c_task_simple_in_air.html", null ],
        [ "CTaskSimpleJetPack", "da/d01/class_c_task_simple_jet_pack.html", null ],
        [ "CTaskSimpleJump", "d2/dd6/class_c_task_simple_jump.html", null ],
        [ "CTaskSimplePlayerOnFoot", "db/ddf/class_c_task_simple_player_on_foot.html", null ],
        [ "CTaskSimpleStandStill", "de/d66/class_c_task_simple_stand_still.html", null ],
        [ "CTaskSimpleStealthKill", "d2/d62/class_c_task_simple_stealth_kill.html", null ],
        [ "CTaskSimpleSwim", "db/d34/class_c_task_simple_swim.html", null ],
        [ "CTaskSimpleThrowProjectile", "d7/d1b/class_c_task_simple_throw_projectile.html", null ],
        [ "CTaskSimpleTriggerLookAt", "d6/d36/class_c_task_simple_trigger_look_at.html", null ],
        [ "CTaskSimpleUseGun", "d4/db9/class_c_task_simple_use_gun.html", null ]
      ] ]
    ] ],
    [ "CTaskManager", "d5/d92/class_c_task_manager.html", null ],
    [ "CTaskTimer", "d8/d99/class_c_task_timer.html", null ],
    [ "CTaskUtilityLineUpPedWithCar", "d2/d00/class_c_task_utility_line_up_ped_with_car.html", null ],
    [ "CText", "d9/dc9/class_c_text.html", null ],
    [ "CText__Tabl", "df/dd0/struct_c_text_____tabl.html", null ],
    [ "CText__TablEntry", "d6/d40/struct_c_text_____tabl_entry.html", null ],
    [ "CText__TDat", "dc/d95/struct_c_text_____t_dat.html", null ],
    [ "CText__TKey", "d1/d20/struct_c_text_____t_key.html", null ],
    [ "CTheCarGenerators", "d0/d78/class_c_the_car_generators.html", null ],
    [ "CTheScripts", "db/def/class_c_the_scripts.html", null ],
    [ "CTheZones", "d4/d88/class_c_the_zones.html", null ],
    [ "CTimeCycle", "dd/d04/class_c_time_cycle.html", null ],
    [ "CTimeCycleBox", "da/dce/class_c_time_cycle_box.html", null ],
    [ "CTimer", "db/de1/class_c_timer.html", null ],
    [ "plugin::ctor_meta< ClassType, OverloadedDecl >", "dd/df3/structplugin_1_1ctor__meta.html", null ],
    [ "CTrafficLights", "de/d36/class_c_traffic_lights.html", null ],
    [ "CTrainCamNode", "d1/dea/struct_c_train_cam_node.html", null ],
    [ "CTrainDoor", "d5/d67/class_c_train_door.html", null ],
    [ "CTrainNode", "d3/d34/class_c_train_node.html", null ],
    [ "cTransmission", "dc/d5f/classc_transmission.html", null ],
    [ "CTxdStore", "d9/d17/class_c_txd_store.html", null ],
    [ "CUpsideDownCarCheck", "d1/d36/class_c_upside_down_car_check.html", null ],
    [ "CUserDisplay", "dc/da0/class_c_user_display.html", null ],
    [ "CustomEnvMapPipeAtomicData", "d2/d93/struct_custom_env_map_pipe_atomic_data.html", null ],
    [ "CustomEnvMapPipeMaterialData", "de/dfc/struct_custom_env_map_pipe_material_data.html", null ],
    [ "CustomSpecMapPipeMaterialData", "dc/df7/struct_custom_spec_map_pipe_material_data.html", null ],
    [ "CVector", "df/d99/class_c_vector.html", null ],
    [ "CVector2D", "d8/db1/class_c_vector2_d.html", null ],
    [ "cVehicleParams", "da/d66/classc_vehicle_params.html", null ],
    [ "CVehicleModelInfo::CVehicleStructure", "d7/d3f/class_c_vehicle_model_info_1_1_c_vehicle_structure.html", null ],
    [ "CVisibilityPlugins", "dc/d56/class_c_visibility_plugins.html", null ],
    [ "CWanted", "d6/dd8/class_c_wanted.html", null ],
    [ "CWaterCannon", "db/dcf/class_c_water_cannon.html", null ],
    [ "CWaterCannons", "d1/dad/class_c_water_cannons.html", null ],
    [ "CWeapon", "d4/dd8/class_c_weapon.html", null ],
    [ "CWeaponEffects", "d9/dd5/class_c_weapon_effects.html", null ],
    [ "CWeaponInfo", "dc/d7a/class_c_weapon_info.html", null ],
    [ "CWeather", "d5/db2/class_c_weather.html", null ],
    [ "CWheel", "d6/d85/class_c_wheel.html", null ],
    [ "CWorld", "d0/da9/class_c_world.html", null ],
    [ "CZone", "da/dbe/class_c_zone.html", null ],
    [ "CZoneExtraInfo", "d2/d42/struct_c_zone_extra_info.html", null ],
    [ "CZoneInfo", "d0/d15/struct_c_zone_info.html", null ],
    [ "D3DIndexDataBuffer", "d1/d7f/class_d3_d_index_data_buffer.html", null ],
    [ "D3DResourceSystem", "de/dad/class_d3_d_resource_system.html", null ],
    [ "D3DTextureBuffer", "de/d3e/class_d3_d_texture_buffer.html", null ],
    [ "plugin::DefaultArgPicker< Types >", "dd/daf/structplugin_1_1_default_arg_picker.html", null ],
    [ "plugin::DefaultArgs", "dd/def/structplugin_1_1_default_args.html", null ],
    [ "plugin::del_dtor_meta< ClassType >", "da/d66/structplugin_1_1del__dtor__meta.html", null ],
    [ "DIJOYSTATE2", "d9/deb/struct_d_i_j_o_y_s_t_a_t_e2.html", null ],
    [ "CDirectory::DirectoryInfo", "d7/dde/struct_c_directory_1_1_directory_info.html", null ],
    [ "plugin::dtor_meta< ClassType >", "d3/d71/structplugin_1_1dtor__meta.html", null ],
    [ "plugin::dummy_func_t", "d1/daf/structplugin_1_1dummy__func__t.html", null ],
    [ "plugin::DynamicResource", "da/d26/classplugin_1_1_dynamic_resource.html", null ],
    [ "EffectStore", "db/d49/struct_effect_store.html", null ],
    [ "plugin::BaseEvent< Injector, RList, Priority, ArgPicker, Ret(Args...)>::EventAfter", "df/d1e/classplugin_1_1_base_event_3_01_injector_00_01_r_list_00_01_priority_00_01_arg_picker_00_01_ret_f89faa80cba3bb7f5bac6bb26e772d8b.html", null ],
    [ "plugin::BaseEvent< Injector, RList, Priority, ArgPicker, Ret(Args...)>::EventBefore", "de/db8/classplugin_1_1_base_event_3_01_injector_00_01_r_list_00_01_priority_00_01_arg_picker_00_01_ret_726b0824cd0abb66e8023cff42d75fba.html", null ],
    [ "plugin::ExtenderInterface< T >", "d9/dc8/classplugin_1_1_extender_interface.html", null ],
    [ "plugin::ExtenderInterface< CObject >", "d9/dc8/classplugin_1_1_extender_interface.html", [
      [ "plugin::ObjectExtendedData< T >", "da/d9d/classplugin_1_1_object_extended_data.html", null ]
    ] ],
    [ "plugin::ExtenderInterface< CPed >", "d9/dc8/classplugin_1_1_extender_interface.html", [
      [ "plugin::PedExtendedData< T >", "d1/d38/classplugin_1_1_ped_extended_data.html", null ]
    ] ],
    [ "plugin::ExtenderInterface< CVehicle >", "d9/dc8/classplugin_1_1_extender_interface.html", [
      [ "plugin::VehicleExtendedData< T >", "d2/dd1/classplugin_1_1_vehicle_extended_data.html", null ]
    ] ],
    [ "plugin::ExtendersHandler< T >", "dc/ddd/classplugin_1_1_extenders_handler.html", null ],
    [ "plugin::ExtendersHandler< CObject >", "dc/ddd/classplugin_1_1_extenders_handler.html", [
      [ "plugin::ObjectExtendersHandler", "d0/dfb/classplugin_1_1_object_extenders_handler.html", null ]
    ] ],
    [ "plugin::ExtendersHandler< CPed >", "dc/ddd/classplugin_1_1_extenders_handler.html", [
      [ "plugin::PedExtendersHandler", "d5/ddf/classplugin_1_1_ped_extenders_handler.html", null ]
    ] ],
    [ "plugin::ExtendersHandler< CVehicle >", "dc/ddd/classplugin_1_1_extenders_handler.html", [
      [ "plugin::VehicleExtendersHandler", "d4/d5e/classplugin_1_1_vehicle_extenders_handler.html", null ]
    ] ],
    [ "injector::fastcall< Prototype >", "d7/dcb/structinjector_1_1fastcall.html", null ],
    [ "injector::fastcall< Ret(Args...)>", "d6/de8/structinjector_1_1fastcall_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "injector::address_manager::fn_mem_translator", "d7/d50/structinjector_1_1address__manager_1_1fn__mem__translator.html", null ],
    [ "injector::address_manager::fn_mem_translator_aslr", "da/d86/structinjector_1_1address__manager_1_1fn__mem__translator__aslr.html", null ],
    [ "injector::address_manager::fn_mem_translator_nop", "d7/d19/structinjector_1_1address__manager_1_1fn__mem__translator__nop.html", null ],
    [ "plugin::FormattingUtils", "d3/df1/classplugin_1_1_formatting_utils.html", null ],
    [ "FrameSearchData", "dd/d59/struct_frame_search_data.html", null ],
    [ "Fx_c", "da/d70/class_fx__c.html", null ],
    [ "FxBox_c", "d1/d99/class_fx_box__c.html", null ],
    [ "FxFrustumInfo_c", "df/deb/class_fx_frustum_info__c.html", null ],
    [ "FxInfoManager_c", "df/d9d/class_fx_info_manager__c.html", null ],
    [ "FxManager_c", "d5/d4e/class_fx_manager__c.html", null ],
    [ "FxMemoryPool_c", "d2/d28/class_fx_memory_pool__c.html", null ],
    [ "FxPlane_c", "d8/d9b/class_fx_plane__c.html", null ],
    [ "FxPrimBP_c", "d2/d06/class_fx_prim_b_p__c.html", [
      [ "FxEmitterBP_c", "d6/d8f/class_fx_emitter_b_p__c.html", null ]
    ] ],
    [ "FxPrtMult_c", "db/d03/class_fx_prt_mult__c.html", null ],
    [ "FxSphere_c", "dd/dd0/class_fx_sphere__c.html", null ],
    [ "injector::game_version_manager", "d3/d72/classinjector_1_1game__version__manager.html", [
      [ "injector::address_manager", "d8/d4c/classinjector_1_1address__manager.html", null ]
    ] ],
    [ "plugin::gamefont", "d6/d11/classplugin_1_1gamefont.html", null ],
    [ "GamePathA", "db/db2/struct_game_path_a.html", null ],
    [ "GamePathW", "d3/d32/struct_game_path_w.html", null ],
    [ "injector::hook_back< FuncType >", "de/d7f/structinjector_1_1hook__back.html", null ],
    [ "IFrame", "d6/d82/struct_i_frame.html", null ],
    [ "IplDef", "d6/d03/class_ipl_def.html", null ],
    [ "KeyCheck", "dd/d93/class_key_check.html", null ],
    [ "injector::lazy_object< addr, T >", "d8/d06/structinjector_1_1lazy__object.html", null ],
    [ "injector::lazy_pointer< addr >", "d9/d16/structinjector_1_1lazy__pointer.html", null ],
    [ "LimbMovementInfo", "d2/dbf/struct_limb_movement_info.html", null ],
    [ "LimbOrientation", "d4/df0/struct_limb_orientation.html", null ],
    [ "List_c", "dc/da8/class_list__c.html", [
      [ "TList_c< ItemType >", "de/deb/class_t_list__c.html", null ],
      [ "TList_c< FxEmitterPrt_c >", "de/deb/class_t_list__c.html", null ],
      [ "TList_c< FxSystem_c >", "de/deb/class_t_list__c.html", null ],
      [ "TList_c< FxSystemBP_c >", "de/deb/class_t_list__c.html", null ],
      [ "TList_c< ListItem_c >", "de/deb/class_t_list__c.html", null ]
    ] ],
    [ "ListItem_c", "d3/d3f/class_list_item__c.html", [
      [ "FxSystem_c", "d3/d0b/class_fx_system__c.html", null ],
      [ "FxSystemBP_c", "da/de6/class_fx_system_b_p__c.html", null ]
    ] ],
    [ "plugin::MakeRefListFromAddressList< Refs, Values >", "d2/dba/structplugin_1_1_make_ref_list_from_address_list.html", null ],
    [ "plugin::MakeRefListFromAddressList< RefList< RefValues... > >", "da/d42/structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4.html", null ],
    [ "plugin::MakeRefListFromAddressList< RefList< RefValues... >, Addr, HookType, Values... >", "dc/dc3/structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_00_01_b850d66456cb814c8ec4c5507f2ac8a4.html", null ],
    [ "plugin::MakeRefListFromAddressListMulti< Refs, Values >", "d5/dbc/structplugin_1_1_make_ref_list_from_address_list_multi.html", null ],
    [ "plugin::MakeRefListFromAddressListMulti< RefList< RefValues... > >", "da/d52/structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4.html", null ],
    [ "plugin::MakeRefListFromAddressListMulti< RefList< RefValues... >, Addr, GameVersion, HookType, Values... >", "d7/d67/structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_bbf42cf144678fd2f4618455b8334a7d.html", null ],
    [ "injector::memory_pointer_tr", "d1/d8d/unioninjector_1_1memory__pointer__tr.html", null ],
    [ "plugin::message_gen", "db/da6/structplugin_1_1message__gen.html", null ],
    [ "MloInstanceStore", "d9/d92/struct_mlo_instance_store.html", null ],
    [ "MloModelStore", "d9/d6d/struct_mlo_model_store.html", null ],
    [ "plugin::MvAddresses< Addresses >", "d9/dfa/structplugin_1_1_mv_addresses.html", null ],
    [ "plugin::op_delete_array_meta< ClassType, OverloadedDecl >", "d9/d9e/structplugin_1_1op__delete__array__meta.html", null ],
    [ "plugin::op_delete_meta< ClassType, OverloadedDecl >", "d6/d0c/structplugin_1_1op__delete__meta.html", null ],
    [ "plugin::op_new_array_meta< ClassType, OverloadedDecl >", "d8/d11/structplugin_1_1op__new__array__meta.html", null ],
    [ "plugin::op_new_meta< ClassType, OverloadedDecl >", "d2/dbf/structplugin_1_1op__new__meta.html", null ],
    [ "PagerMessage", "d3/d36/struct_pager_message.html", null ],
    [ "plugin::patch", "dc/d0a/classplugin_1_1patch.html", null ],
    [ "plugin::paths", "d6/d07/classplugin_1_1paths.html", null ],
    [ "PedModelStore", "d7/d7b/struct_ped_model_store.html", null ],
    [ "PluginPathA", "d3/d97/struct_plugin_path_a.html", null ],
    [ "PluginPathW", "d7/df3/struct_plugin_path_w.html", null ],
    [ "PluginSupport", "d3/d93/class_plugin_support.html", [
      [ "Fastman92LimitAdjusterSupport", "d0/d2f/class_fastman92_limit_adjuster_support.html", null ]
    ] ],
    [ "plugin::PoolIterator< T1, T2 >", "dc/d4b/classplugin_1_1_pool_iterator.html", null ],
    [ "psGlobalType", "d6/dd1/structps_global_type.html", null ],
    [ "plugin::RefList< Values >", "d1/de7/structplugin_1_1_ref_list.html", null ],
    [ "plugin::RefListUtils< Refs >", "d1/dae/structplugin_1_1_ref_list_utils.html", null ],
    [ "plugin::RefListUtils< RefList< Values... > >", "d5/ddd/structplugin_1_1_ref_list_utils_3_01_ref_list_3_01_values_8_8_8_01_4_01_4.html", null ],
    [ "plugin::RefListUtils< RefList<> >", "d5/dd8/structplugin_1_1_ref_list_utils_3_01_ref_list_3_4_01_4.html", null ],
    [ "injector::reg_pack", "dc/dc0/structinjector_1_1reg__pack.html", null ],
    [ "RenderBuffer", "dd/d51/class_render_buffer.html", null ],
    [ "RpAtomic", "d0/dbe/struct_rp_atomic.html", null ],
    [ "RpBuildMesh", "d8/d23/struct_rp_build_mesh.html", null ],
    [ "RpBuildMeshTriangle", "d4/d1c/struct_rp_build_mesh_triangle.html", null ],
    [ "RpClump", "d8/df0/struct_rp_clump.html", null ],
    [ "RpClumpChunkInfo", "d7/d5a/struct_rp_clump_chunk_info.html", null ],
    [ "RpClumpChunkInfo33000", "d1/d18/struct_rp_clump_chunk_info33000.html", null ],
    [ "RpD3D8AttenuationParams", "d5/d56/struct_rp_d3_d8_attenuation_params.html", null ],
    [ "RpD3D9AttenuationParams", "d5/de1/struct_rp_d3_d9_attenuation_params.html", null ],
    [ "RpGeometry", "de/d9c/struct_rp_geometry.html", null ],
    [ "RpGeometryChunkInfo", "d6/d68/struct_rp_geometry_chunk_info.html", null ],
    [ "rpGeometryGlobals", "de/d1b/structrp_geometry_globals.html", null ],
    [ "RpHAnimAtomicGlobalVars", "da/d53/struct_rp_h_anim_atomic_global_vars.html", null ],
    [ "RpHAnimBlendInterpFrame", "d2/dff/struct_rp_h_anim_blend_interp_frame.html", null ],
    [ "RpHAnimFrameExtension", "d2/d41/struct_rp_h_anim_frame_extension.html", null ],
    [ "RpHAnimHierarchy", "d6/d40/struct_rp_h_anim_hierarchy.html", null ],
    [ "RpHAnimInterpFrame", "db/dab/struct_rp_h_anim_interp_frame.html", null ],
    [ "RpHAnimKeyFrame", "d0/da7/struct_rp_h_anim_key_frame.html", null ],
    [ "RpHAnimNodeInfo", "d9/df0/struct_rp_h_anim_node_info.html", null ],
    [ "RpInterpolator", "d5/d97/struct_rp_interpolator.html", null ],
    [ "RpLight", "dc/ded/struct_rp_light.html", null ],
    [ "RpLightChunkInfo", "de/dbf/struct_rp_light_chunk_info.html", null ],
    [ "RpLightTie", "db/d50/struct_rp_light_tie.html", null ],
    [ "RpMaterial", "d2/d26/struct_rp_material.html", null ],
    [ "RpMaterialChunkInfo", "da/dc8/struct_rp_material_chunk_info.html", null ],
    [ "RpMaterialList", "d2/d83/struct_rp_material_list.html", null ],
    [ "RpMesh", "db/d0b/struct_rp_mesh.html", null ],
    [ "rpMeshGlobals", "dc/d99/structrp_mesh_globals.html", null ],
    [ "RpMeshHeader", "d3/d52/struct_rp_mesh_header.html", null ],
    [ "RpMorphTarget", "d2/d61/struct_rp_morph_target.html", null ],
    [ "RpPlaneSector", "d8/d58/struct_rp_plane_sector.html", null ],
    [ "RpPlaneSectorChunkInfo", "d7/d50/struct_rp_plane_sector_chunk_info.html", null ],
    [ "RpPolygon", "db/d35/struct_rp_polygon.html", null ],
    [ "RpSector", "d7/db5/struct_rp_sector.html", null ],
    [ "RpSkin", "dd/dad/struct_rp_skin.html", null ],
    [ "rpTextureChunkInfo", "db/dfc/structrp_texture_chunk_info.html", null ],
    [ "RpTie", "d1/dad/struct_rp_tie.html", null ],
    [ "RpTriangle", "d8/d79/struct_rp_triangle.html", null ],
    [ "RpTriStripData", "da/d20/struct_rp_tri_strip_data.html", null ],
    [ "RpTriStripEdge", "de/dff/struct_rp_tri_strip_edge.html", null ],
    [ "RpTriStripMesh", "d4/da4/struct_rp_tri_strip_mesh.html", null ],
    [ "RpTriStripPolygon", "d8/dfa/struct_rp_tri_strip_polygon.html", null ],
    [ "RpTriStripTunnelData", "dd/d94/struct_rp_tri_strip_tunnel_data.html", null ],
    [ "RpUVAnimInterpFrame", "d8/d3d/struct_rp_u_v_anim_interp_frame.html", null ],
    [ "RpUVAnimKeyFrame", "d9/d04/struct_rp_u_v_anim_key_frame.html", null ],
    [ "RpUVAnimKeyFrameData", "d8/de7/union_rp_u_v_anim_key_frame_data.html", null ],
    [ "RpUVAnimLinearKeyFrameData", "d7/d90/struct_rp_u_v_anim_linear_key_frame_data.html", null ],
    [ "RpUVAnimMaterialExtension", "dd/daa/struct_rp_u_v_anim_material_extension.html", null ],
    [ "RpUVAnimMaterialGlobalVars", "dc/d86/struct_rp_u_v_anim_material_global_vars.html", null ],
    [ "RpUVAnimParamKeyFrameData", "d7/da9/struct_rp_u_v_anim_param_key_frame_data.html", null ],
    [ "RpVertexNormal", "d2/d5d/struct_rp_vertex_normal.html", null ],
    [ "RpWorld", "d3/db5/struct_rp_world.html", null ],
    [ "RpWorldChunkInfo", "df/d78/struct_rp_world_chunk_info.html", null ],
    [ "rpWorldChunkInfo34000", "da/d65/structrp_world_chunk_info34000.html", null ],
    [ "RpWorldChunkInfoSector", "d0/de6/struct_rp_world_chunk_info_sector.html", null ],
    [ "RpWorldSector", "d8/d5c/struct_rp_world_sector.html", null ],
    [ "RsGlobalType", "d6/de7/struct_rs_global_type.html", null ],
    [ "RsInputDevice", "d3/d38/struct_rs_input_device.html", null ],
    [ "RsKeyStatus", "d6/d9f/struct_rs_key_status.html", null ],
    [ "RsMouseStatus", "d8/d7b/struct_rs_mouse_status.html", null ],
    [ "RsPadButtonStatus", "dd/de5/struct_rs_pad_button_status.html", null ],
    [ "RtAnimAnimation", "de/d03/struct_rt_anim_animation.html", null ],
    [ "RtAnimInterpFrameHeader", "dd/d37/struct_rt_anim_interp_frame_header.html", null ],
    [ "RtAnimInterpolator", "d6/d58/struct_rt_anim_interpolator.html", null ],
    [ "RtAnimInterpolatorInfo", "d9/d4c/struct_rt_anim_interpolator_info.html", null ],
    [ "RtAnimKeyFrameHeader", "d8/d17/struct_rt_anim_key_frame_header.html", null ],
    [ "RtDict", "d8/df6/struct_rt_dict.html", null ],
    [ "RtDictSchema", "d6/da1/struct_rt_dict_schema.html", null ],
    [ "RtQuat", "db/d7d/struct_rt_quat.html", null ],
    [ "RwBBox", "df/da2/struct_rw_b_box.html", null ],
    [ "RwCamera", "d1/d4c/struct_rw_camera.html", null ],
    [ "RwChunkGroup", "d8/d0d/struct_rw_chunk_group.html", null ],
    [ "RwChunkHeaderInfo", "d5/d61/struct_rw_chunk_header_info.html", null ],
    [ "RwD3D8Metrics", "d8/dcd/struct_rw_d3_d8_metrics.html", null ],
    [ "RwD3D8Vertex", "d5/d98/struct_rw_d3_d8_vertex.html", null ],
    [ "RwD3D9Metrics", "df/db2/struct_rw_d3_d9_metrics.html", null ],
    [ "RwD3D9Vertex", "da/d2a/struct_rw_d3_d9_vertex.html", null ],
    [ "RwDevice", "dc/d5a/struct_rw_device.html", null ],
    [ "RwEngineOpenParams", "d6/d81/struct_rw_engine_open_params.html", null ],
    [ "RwError", "d9/d78/struct_rw_error.html", null ],
    [ "RwFileFunctions", "da/d0d/struct_rw_file_functions.html", null ],
    [ "RwFrame", "de/d74/struct_rw_frame.html", null ],
    [ "rwFrameList", "df/dd8/structrw_frame_list.html", null ],
    [ "RwFreeList", "d4/d6a/struct_rw_free_list.html", null ],
    [ "RwFrustumPlane", "df/da3/struct_rw_frustum_plane.html", null ],
    [ "RwGlobals", "df/db1/struct_rw_globals.html", null ],
    [ "rwIm3DPool", "d1/d8d/structrw_im3_d_pool.html", null ],
    [ "rwIm3DRenderPipelines", "d7/dd3/structrw_im3_d_render_pipelines.html", null ],
    [ "RwImage", "d8/d55/struct_rw_image.html", null ],
    [ "rwImmediGlobals", "dc/dd2/structrw_immedi_globals.html", null ],
    [ "RwLine", "de/d1f/struct_rw_line.html", null ],
    [ "RwLinkList", "db/ddd/struct_rw_link_list.html", null ],
    [ "RwLLLink", "d2/d89/struct_rw_l_l_link.html", null ],
    [ "RwMatrixTag", "d8/de3/struct_rw_matrix_tag.html", null ],
    [ "RwMatrixTolerance", "df/dc3/struct_rw_matrix_tolerance.html", null ],
    [ "RwMatrixWeights", "de/d30/struct_rw_matrix_weights.html", null ],
    [ "RwMemory", "d5/d7d/struct_rw_memory.html", null ],
    [ "RwMemoryFunctions", "d8/dd7/struct_rw_memory_functions.html", null ],
    [ "RwMetrics", "d5/d64/struct_rw_metrics.html", null ],
    [ "RwModuleInfo", "de/d2c/struct_rw_module_info.html", null ],
    [ "RwObject", "d3/dd5/struct_rw_object.html", null ],
    [ "RwObjectHasFrame", "d0/d32/struct_rw_object_has_frame.html", null ],
    [ "RwObjectNameIdAssocation", "d8/ddd/struct_rw_object_name_id_assocation.html", null ],
    [ "RwPalQuant", "d1/dac/struct_rw_pal_quant.html", null ],
    [ "rwPipeGlobals", "da/d47/structrw_pipe_globals.html", null ],
    [ "RwPlane", "d6/d7e/struct_rw_plane.html", null ],
    [ "RwPluginRegEntry", "d2/d5b/struct_rw_plugin_reg_entry.html", null ],
    [ "RwPluginRegistry", "d2/dc3/struct_rw_plugin_registry.html", null ],
    [ "RwRaster", "dd/d2f/struct_rw_raster.html", null ],
    [ "RwRect", "d9/de3/struct_rw_rect.html", null ],
    [ "RwResEntry", "d6/d8e/struct_rw_res_entry.html", null ],
    [ "rwResources", "dd/de2/structrw_resources.html", null ],
    [ "rwResourcesGlobals", "d5/d3a/structrw_resources_globals.html", null ],
    [ "RwRGBA", "dd/d45/struct_rw_r_g_b_a.html", null ],
    [ "RwRGBAReal", "de/d64/struct_rw_r_g_b_a_real.html", null ],
    [ "RwSingleList", "dc/d71/struct_rw_single_list.html", null ],
    [ "RwSList", "d9/db9/struct_rw_s_list.html", null ],
    [ "RwSLLink", "da/d15/struct_rw_s_l_link.html", null ],
    [ "RwSphere", "dc/d23/struct_rw_sphere.html", null ],
    [ "RwSplitBits", "d4/df6/union_rw_split_bits.html", null ],
    [ "RwSplitFixed", "d7/d2b/struct_rw_split_fixed.html", null ],
    [ "RwStream", "d4/dc7/struct_rw_stream.html", null ],
    [ "rwStreamCamera", "da/d6c/structrw_stream_camera.html", null ],
    [ "RwStreamCustom", "d6/d6a/struct_rw_stream_custom.html", null ],
    [ "RwStreamFile", "d6/d63/union_rw_stream_file.html", null ],
    [ "rwStreamMatrix", "d4/d3e/structrw_stream_matrix.html", null ],
    [ "RwStreamMemory", "de/dce/struct_rw_stream_memory.html", null ],
    [ "RwStreamUnion", "df/dc5/union_rw_stream_union.html", null ],
    [ "RwStringFunctions", "d1/dd2/struct_rw_string_functions.html", null ],
    [ "RwSubSystemInfo", "db/d5e/struct_rw_sub_system_info.html", null ],
    [ "RwSurfaceProperties", "dd/df0/struct_rw_surface_properties.html", null ],
    [ "RwTexCoords", "d2/d7f/struct_rw_tex_coords.html", null ],
    [ "RwTexDictionary", "d6/de6/struct_rw_tex_dictionary.html", null ],
    [ "RwTexture", "d4/d5b/struct_rw_texture.html", null ],
    [ "RwUnionReal", "de/dd0/union_rw_union_real.html", null ],
    [ "RwV2d", "d5/d77/struct_rw_v2d.html", null ],
    [ "RwV3d", "dc/de1/struct_rw_v3d.html", null ],
    [ "RwV4d", "da/dea/struct_rw_v4d.html", null ],
    [ "RwV4dTag", "d0/d01/struct_rw_v4d_tag.html", null ],
    [ "RwVideoMode", "d7/d8d/struct_rw_video_mode.html", null ],
    [ "RxCamSpace3DVertex", "d8/d54/struct_rx_cam_space3_d_vertex.html", null ],
    [ "RxCluster", "dd/d8a/struct_rx_cluster.html", null ],
    [ "RxClusterDefinition", "dc/d0d/struct_rx_cluster_definition.html", null ],
    [ "RxClusterRef", "de/d42/struct_rx_cluster_ref.html", null ],
    [ "RxD3D8InstanceData", "dd/d92/struct_rx_d3_d8_instance_data.html", null ],
    [ "RxD3D8ResEntryHeader", "db/d2c/struct_rx_d3_d8_res_entry_header.html", null ],
    [ "RxD3D9InstanceData", "d6/d47/struct_rx_d3_d9_instance_data.html", null ],
    [ "RxD3D9ResEntryHeader", "db/dc9/struct_rx_d3_d9_res_entry_header.html", null ],
    [ "RxD3D9VertexStream", "d0/d9f/struct_rx_d3_d9_vertex_stream.html", null ],
    [ "RxExecutionContext", "d9/d09/struct_rx_execution_context.html", null ],
    [ "RxHeap", "d3/d2f/struct_rx_heap.html", null ],
    [ "rxHeapBlockHeader", "db/db7/structrx_heap_block_header.html", null ],
    [ "rxHeapFreeBlock", "dd/dd0/structrx_heap_free_block.html", null ],
    [ "rxHeapSuperBlockDescriptor", "d0/daa/structrx_heap_super_block_descriptor.html", null ],
    [ "RxInterp", "d9/d5d/struct_rx_interp.html", null ],
    [ "RxIoSpec", "d7/d82/struct_rx_io_spec.html", null ],
    [ "RxMeshStateVector", "d2/dfc/struct_rx_mesh_state_vector.html", null ],
    [ "RxNodeDefinition", "dc/dee/struct_rx_node_definition.html", null ],
    [ "RxNodeMethods", "d6/df3/struct_rx_node_methods.html", null ],
    [ "RxObjSpace3DVertex", "db/de9/struct_rx_obj_space3_d_vertex.html", null ],
    [ "RxOutputSpec", "d7/d1f/struct_rx_output_spec.html", null ],
    [ "RxPacket", "d5/dd4/struct_rx_packet.html", null ],
    [ "RxPipeline", "d4/de2/struct_rx_pipeline.html", null ],
    [ "RxPipelineCluster", "d9/d2e/struct_rx_pipeline_cluster.html", null ],
    [ "RxPipelineNode", "d0/d6b/struct_rx_pipeline_node.html", null ],
    [ "RxPipelineNodeParam", "d7/d0d/struct_rx_pipeline_node_param.html", null ],
    [ "RxPipelineNodeTopSortData", "de/df3/struct_rx_pipeline_node_top_sort_data.html", null ],
    [ "RxPipelineRequiresCluster", "d0/dbf/struct_rx_pipeline_requires_cluster.html", null ],
    [ "RxRenderStateVector", "db/d46/struct_rx_render_state_vector.html", null ],
    [ "RxScatter", "db/d2c/struct_rx_scatter.html", null ],
    [ "RxTriPlane", "d6/db2/struct_rx_tri_plane.html", null ],
    [ "RxUV", "db/dac/struct_rx_u_v.html", null ],
    [ "RxVStep", "d0/d81/struct_rx_v_step.html", null ],
    [ "SArray< T >", "d4/d48/struct_s_array.html", null ],
    [ "injector::scoped_base", "df/d58/classinjector_1_1scoped__base.html", [
      [ "injector::scoped_basic< bufsize >", "df/d36/classinjector_1_1scoped__basic.html", null ],
      [ "injector::scoped_basic< 10 >", "df/d36/classinjector_1_1scoped__basic.html", [
        [ "injector::scoped_write< bufsize_ >", "de/de8/classinjector_1_1scoped__write.html", null ]
      ] ],
      [ "injector::scoped_basic< 4 >", "df/d36/classinjector_1_1scoped__basic.html", [
        [ "injector::scoped_callback", "d6/d3a/classinjector_1_1scoped__callback.html", null ]
      ] ],
      [ "injector::scoped_basic< 5 >", "df/d36/classinjector_1_1scoped__basic.html", [
        [ "injector::scoped_call", "d3/db5/classinjector_1_1scoped__call.html", null ],
        [ "injector::scoped_fill< bufsize_ >", "dc/daf/classinjector_1_1scoped__fill.html", null ],
        [ "injector::scoped_jmp", "da/dc4/classinjector_1_1scoped__jmp.html", null ]
      ] ],
      [ "injector::scoped_basic< bufsize_ >", "df/d36/classinjector_1_1scoped__basic.html", [
        [ "injector::scoped_nop< bufsize_ >", "d7/da1/classinjector_1_1scoped__nop.html", null ]
      ] ]
    ] ],
    [ "injector::scoped_unprotect", "df/d2c/structinjector_1_1scoped__unprotect.html", null ],
    [ "plugin::screen", "d6/d9d/classplugin_1_1screen.html", null ],
    [ "plugin::scripting", "dd/d22/classplugin_1_1scripting.html", null ],
    [ "SimpleModelStore", "d6/d07/struct_simple_model_store.html", null ],
    [ "plugin::stack_object< T >", "dd/d8e/structplugin_1_1stack__object.html", null ],
    [ "plugin::stack_object_no_default< T >", "db/d74/structplugin_1_1stack__object__no__default.html", null ],
    [ "plugin::stack_object_no_default< C3dMarker >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< C3dMarker >", "d6/def/structplugin_1_1stack__object_3_01_c3d_marker_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CAnimBlendAssociation >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CAnimBlendAssociation >", "de/da8/structplugin_1_1stack__object_3_01_c_anim_blend_association_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CAnimBlendStaticAssociation >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CAnimBlendStaticAssociation >", "d9/df7/structplugin_1_1stack__object_3_01_c_anim_blend_static_association_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CAudioHydrant >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CAudioHydrant >", "de/dd6/structplugin_1_1stack__object_3_01_c_audio_hydrant_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< cAudioScriptObject >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< cAudioScriptObject >", "dd/da7/structplugin_1_1stack__object_3_01c_audio_script_object_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CBrightLight >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CBrightLight >", "d7/d13/structplugin_1_1stack__object_3_01_c_bright_light_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CBulletInfo >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CBulletInfo >", "d9/d24/structplugin_1_1stack__object_3_01_c_bullet_info_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CBulletTrace >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CBulletTrace >", "dc/da8/structplugin_1_1stack__object_3_01_c_bullet_trace_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CCamera >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CCamera >", "d4/df7/structplugin_1_1stack__object_3_01_c_camera_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CColLine >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CColLine >", "dc/d91/structplugin_1_1stack__object_3_01_c_col_line_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CDirectory >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CDirectory >", "db/df2/structplugin_1_1stack__object_3_01_c_directory_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CEntryExit >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CEntryExit >", "d0/df0/structplugin_1_1stack__object_3_01_c_entry_exit_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CGangInfo >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CGangInfo >", "de/d4e/structplugin_1_1stack__object_3_01_c_gang_info_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CMatrixLink >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CMatrixLink >", "d5/d64/structplugin_1_1stack__object_3_01_c_matrix_link_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPad >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPad >", "d1/d33/structplugin_1_1stack__object_3_01_c_pad_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CParticle >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CParticle >", "dd/de8/structplugin_1_1stack__object_3_01_c_particle_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPedGroup >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPedGroup >", "d5/ded/structplugin_1_1stack__object_3_01_c_ped_group_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPedGroupIntelligence >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPedGroupIntelligence >", "d8/dcc/structplugin_1_1stack__object_3_01_c_ped_group_intelligence_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPedGroupMembership >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPedGroupMembership >", "d0/dab/structplugin_1_1stack__object_3_01_c_ped_group_membership_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPhone >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPhone >", "d5/d24/structplugin_1_1stack__object_3_01_c_phone_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPhoneInfo >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPhoneInfo >", "dd/d95/structplugin_1_1stack__object_3_01_c_phone_info_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CPointLight >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CPointLight >", "d7/d3b/structplugin_1_1stack__object_3_01_c_point_light_01_4.html", null ]
    ] ],
    [ "plugin::stack_object_no_default< CRegisteredMotionBlurStreak >", "db/d74/structplugin_1_1stack__object__no__default.html", [
      [ "plugin::stack_object< CRegisteredMotionBlurStreak >", "d4/d33/structplugin_1_1stack__object_3_01_c_registered_motion_blur_streak_01_4.html", null ]
    ] ],
    [ "plugin::ExtendersHandler< T >::static_data", "d2/d90/structplugin_1_1_extenders_handler_1_1static__data.html", null ],
    [ "injector::stdcall< Prototype >", "dd/da7/structinjector_1_1stdcall.html", null ],
    [ "injector::stdcall< Ret(Args...)>", "d2/d57/structinjector_1_1stdcall_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "tAtomicVisibilityPlugin", "d4/d4e/structt_atomic_visibility_plugin.html", null ],
    [ "tBigMessage", "db/d7b/structt_big_message.html", null ],
    [ "tBikeHandlingData", "d8/d5c/structt_bike_handling_data.html", null ],
    [ "tBinaryIplFile", "dd/d49/structt_binary_ipl_file.html", null ],
    [ "tBlipHandle", "db/d38/structt_blip_handle.html", null ],
    [ "tBoatHandlingData", "d7/d66/structt_boat_handling_data.html", null ],
    [ "tBrightLight", "d3/d3a/structt_bright_light.html", null ],
    [ "tBuildingSwap", "d1/d07/structt_building_swap.html", null ],
    [ "tCamPathSplines", "d8/d76/structt_cam_path_splines.html", null ],
    [ "tCarGenPlateText", "d0/d11/structt_car_gen_plate_text.html", null ],
    [ "tColLighting", "dd/d8b/structt_col_lighting.html", null ],
    [ "tColSurface", "d9/db3/structt_col_surface.html", null ],
    [ "tCutsceneAttachment", "da/d78/structt_cutscene_attachment.html", null ],
    [ "tCutsceneParticleEffect", "d8/d20/structt_cutscene_particle_effect.html", null ],
    [ "tCutsceneRemoval", "d9/d3f/structt_cutscene_removal.html", null ],
    [ "tDirectionArrow", "dc/d2d/structt_direction_arrow.html", null ],
    [ "tEffectCoverPoint", "dd/da7/structt_effect_cover_point.html", null ],
    [ "tEffectEnEx", "d7/d74/structt_effect_en_ex.html", null ],
    [ "tEffectEscalator", "d0/d6a/structt_effect_escalator.html", null ],
    [ "tEffectLight", "dc/d5e/structt_effect_light.html", null ],
    [ "tEffectParticle", "d2/d01/structt_effect_particle.html", null ],
    [ "tEffectPedAttractor", "d8/d23/structt_effect_ped_attractor.html", null ],
    [ "tEffectRoadsign", "df/d1b/structt_effect_roadsign.html", null ],
    [ "tEngineDummySlot", "de/d7a/structt_engine_dummy_slot.html", null ],
    [ "tFlyingHandlingData", "d7/d40/structt_flying_handling_data.html", null ],
    [ "tFontData", "d3/ddc/structt_font_data.html", null ],
    [ "tGXT_VERSION_2_TKEY_item", "d4/df2/structt_g_x_t___v_e_r_s_i_o_n__2___t_k_e_y__item.html", null ],
    [ "tHandlingData", "d0/dcb/structt_handling_data.html", null ],
    [ "tHeliLight", "d1/d14/structt_heli_light.html", null ],
    [ "injector::thiscall< Prototype >", "d3/d11/structinjector_1_1thiscall.html", null ],
    [ "plugin::CallingConventions::Thiscall", "d3/dff/structplugin_1_1_calling_conventions_1_1_thiscall.html", null ],
    [ "injector::thiscall< Ret(Args...)>", "d0/d57/structinjector_1_1thiscall_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "TimeModelStore", "d3/d28/struct_time_model_store.html", null ],
    [ "tIntroText", "d7/d28/structt_intro_text.html", null ],
    [ "tMenuPage", "dd/d73/structt_menu_page.html", null ],
    [ "tMenuPanel", "db/d7c/classt_menu_panel.html", null ],
    [ "tMenuProp", "df/de9/structt_menu_prop.html", null ],
    [ "tMessage", "db/d52/structt_message.html", null ],
    [ "tMissionCleanupEntity", "d7/d55/structt_mission_cleanup_entity.html", null ],
    [ "tModelRequest", "de/d1d/structt_model_request.html", null ],
    [ "tMovingFog", "da/d03/structt_moving_fog.html", null ],
    [ "tMP3Sample", "d9/d80/structt_m_p3_sample.html", null ],
    [ "tMusicTrackHistory", "d5/d0c/structt_music_track_history.html", null ],
    [ "tParticleSystemData", "d7/d0d/structt_particle_system_data.html", null ],
    [ "tPedGroupTranslationData", "dc/d43/structt_ped_group_translation_data.html", null ],
    [ "CPedType::tPedTypeFlags", "d6/deb/union_c_ped_type_1_1t_ped_type_flags.html", null ],
    [ "tPickupMessage", "d5/d0e/structt_pickup_message.html", null ],
    [ "tPoolObjectFlags", "d5/d40/uniont_pool_object_flags.html", null ],
    [ "tPreviousBrief", "db/de9/structt_previous_brief.html", null ],
    [ "tQueuedMode", "de/da9/structt_queued_mode.html", null ],
    [ "tRadarTrace", "d2/dea/structt_radar_trace.html", null ],
    [ "tRenderListEntry", "d7/d83/structt_render_list_entry.html", null ],
    [ "tRoadbloxDat", "d8/d6a/structt_roadblox_dat.html", null ],
    [ "tScanLists", "d2/d00/structt_scan_lists.html", null ],
    [ "tScriptAttachedAnimGroup", "d0/d66/structt_script_attached_anim_group.html", null ],
    [ "tScriptCheckpoint", "de/d28/structt_script_checkpoint.html", null ],
    [ "tScriptEffectSystem", "d6/dab/structt_script_effect_system.html", null ],
    [ "tScriptParam", "d1/d35/uniont_script_param.html", null ],
    [ "tScriptRectangle", "d2/d1f/structt_script_rectangle.html", null ],
    [ "tScriptRoadBlocks", "d1/d60/structt_script_road_blocks.html", null ],
    [ "tScriptSearchlight", "df/dfb/structt_script_searchlight.html", null ],
    [ "tScriptSequence", "d7/d3f/structt_script_sequence.html", null ],
    [ "tScriptSphere", "dd/d34/structt_script_sphere.html", null ],
    [ "tScriptSwitchCase", "db/d90/structt_script_switch_case.html", null ],
    [ "tScriptText", "d7/d73/structt_script_text.html", null ],
    [ "tScriptVariable", "d8/d62/uniont_script_variable.html", null ],
    [ "tSlotFileName", "df/da0/structt_slot_file_name.html", null ],
    [ "tSlotSaveDate", "d0/d1b/structt_slot_save_date.html", null ],
    [ "tStatMessage", "d0/d18/structt_stat_message.html", null ],
    [ "tStreamingChannel", "d1/d2c/structt_streaming_channel.html", null ],
    [ "tStreamingFileDesc", "d2/daf/structt_streaming_file_desc.html", null ],
    [ "tTimeInfo", "d3/de6/structt_time_info.html", null ],
    [ "tTransmissionGear", "d7/daa/structt_transmission_gear.html", null ],
    [ "tUsedObject", "d7/d4f/structt_used_object.html", null ],
    [ "tUser3dMarker", "db/d7e/structt_user3d_marker.html", null ],
    [ "tVehicleAudioSettings", "d3/dd9/structt_vehicle_audio_settings.html", null ],
    [ "tVehicleSound", "d6/d6d/structt_vehicle_sound.html", null ],
    [ "tVolumetricClouds", "d9/d44/structt_volumetric_clouds.html", null ],
    [ "TxdDef", "d5/dc6/class_txd_def.html", null ],
    [ "UpgradePosnDesc", "da/dd4/struct_upgrade_posn_desc.html", null ],
    [ "VehicleModelStore", "d4/de7/struct_vehicle_model_store.html", null ],
    [ "plugin::vtable_meta< ClassType >", "d0/d7a/structplugin_1_1vtable__meta.html", null ],
    [ "WeaponModelStore", "d8/d0d/struct_weapon_model_store.html", null ],
    [ "injector::injector_asm::wrapper< T >", "dd/d2b/structinjector_1_1injector__asm_1_1wrapper.html", null ],
    [ "XtraCompsModelStore", "dc/d2d/struct_xtra_comps_model_store.html", null ]
];