var namespaceplugin =
[
    [ "ArgPick", "structplugin_1_1_arg_pick.html", null ],
    [ "ArgPick< ArgTypes< Types... >, Indices... >", "structplugin_1_1_arg_pick_3_01_arg_types_3_01_types_8_8_8_01_4_00_01_indices_8_8_8_01_4.html", "structplugin_1_1_arg_pick_3_01_arg_types_3_01_types_8_8_8_01_4_00_01_indices_8_8_8_01_4" ],
    [ "ArgTypes", "structplugin_1_1_arg_types.html", null ],
    [ "BaseEvent", "classplugin_1_1_base_event.html", null ],
    [ "BaseEvent< Injector, RList, Priority, ArgPicker, Ret(Args...)>", "classplugin_1_1_base_event_3_01_injector_00_01_r_list_00_01_priority_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4.html", "classplugin_1_1_base_event_3_01_injector_00_01_r_list_00_01_priority_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4" ],
    [ "BaseEventI", "classplugin_1_1_base_event_i.html", null ],
    [ "BaseEventI< Injector, RList, ArgPicker, Ret(Args...)>", "classplugin_1_1_base_event_i_3_01_injector_00_01_r_list_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4.html", "classplugin_1_1_base_event_i_3_01_injector_00_01_r_list_00_01_arg_picker_00_01_ret_07_args_8_8_8_08_4" ],
    [ "CallingConventions", "structplugin_1_1_calling_conventions.html", [
      [ "Cdecl", "structplugin_1_1_calling_conventions_1_1_cdecl.html", null ],
      [ "Thiscall", "structplugin_1_1_calling_conventions_1_1_thiscall.html", null ]
    ] ],
    [ "ctor_meta", "structplugin_1_1ctor__meta.html", null ],
    [ "DefaultArgPicker", "structplugin_1_1_default_arg_picker.html", "structplugin_1_1_default_arg_picker" ],
    [ "DefaultArgs", "structplugin_1_1_default_args.html", null ],
    [ "del_dtor_meta", "structplugin_1_1del__dtor__meta.html", null ],
    [ "dtor_meta", "structplugin_1_1dtor__meta.html", null ],
    [ "dummy_func_t", "structplugin_1_1dummy__func__t.html", null ],
    [ "ExtenderInterface", "classplugin_1_1_extender_interface.html", "classplugin_1_1_extender_interface" ],
    [ "ExtendersHandler", "classplugin_1_1_extenders_handler.html", "classplugin_1_1_extenders_handler" ],
    [ "FormattingUtils", "classplugin_1_1_formatting_utils.html", null ],
    [ "MakeRefListFromAddressList", "structplugin_1_1_make_ref_list_from_address_list.html", null ],
    [ "MakeRefListFromAddressList< RefList< RefValues... > >", "structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4.html", "structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4" ],
    [ "MakeRefListFromAddressList< RefList< RefValues... >, Addr, HookType, Values... >", "structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_00_01_b850d66456cb814c8ec4c5507f2ac8a4.html", "structplugin_1_1_make_ref_list_from_address_list_3_01_ref_list_3_01_ref_values_8_8_8_01_4_00_01_b850d66456cb814c8ec4c5507f2ac8a4" ],
    [ "MakeRefListFromAddressListMulti", "structplugin_1_1_make_ref_list_from_address_list_multi.html", null ],
    [ "MakeRefListFromAddressListMulti< RefList< RefValues... > >", "structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4.html", "structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_01_4" ],
    [ "MakeRefListFromAddressListMulti< RefList< RefValues... >, Addr, GameVersion, HookType, Values... >", "structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_bbf42cf144678fd2f4618455b8334a7d.html", "structplugin_1_1_make_ref_list_from_address_list_multi_3_01_ref_list_3_01_ref_values_8_8_8_01_4_bbf42cf144678fd2f4618455b8334a7d" ],
    [ "message_gen", "structplugin_1_1message__gen.html", null ],
    [ "MvAddresses", "structplugin_1_1_mv_addresses.html", null ],
    [ "op_delete_array_meta", "structplugin_1_1op__delete__array__meta.html", null ],
    [ "op_delete_meta", "structplugin_1_1op__delete__meta.html", null ],
    [ "op_new_array_meta", "structplugin_1_1op__new__array__meta.html", null ],
    [ "op_new_meta", "structplugin_1_1op__new__meta.html", null ],
    [ "patch", "classplugin_1_1patch.html", null ],
    [ "RefList", "structplugin_1_1_ref_list.html", "structplugin_1_1_ref_list" ],
    [ "RefListUtils", "structplugin_1_1_ref_list_utils.html", null ],
    [ "RefListUtils< RefList< Values... > >", "structplugin_1_1_ref_list_utils_3_01_ref_list_3_01_values_8_8_8_01_4_01_4.html", null ],
    [ "RefListUtils< RefList<> >", "structplugin_1_1_ref_list_utils_3_01_ref_list_3_4_01_4.html", null ],
    [ "stack_object", "structplugin_1_1stack__object.html", "structplugin_1_1stack__object" ],
    [ "stack_object_no_default", "structplugin_1_1stack__object__no__default.html", "structplugin_1_1stack__object__no__default" ],
    [ "vtable_meta", "structplugin_1_1vtable__meta.html", null ]
];