var namespaceinjector =
[
    [ "injector_asm", "d8/d78/namespaceinjector_1_1injector__asm.html", "d8/d78/namespaceinjector_1_1injector__asm" ],
    [ "address_manager", "d8/d4c/classinjector_1_1address__manager.html", "d8/d4c/classinjector_1_1address__manager" ],
    [ "address_translator", "d7/d4c/classinjector_1_1address__translator.html", "d7/d4c/classinjector_1_1address__translator" ],
    [ "address_translator_manager", "d7/d7f/classinjector_1_1address__translator__manager.html", "d7/d7f/classinjector_1_1address__translator__manager" ],
    [ "auto_pointer", "d5/d8e/unioninjector_1_1auto__pointer.html", "d5/d8e/unioninjector_1_1auto__pointer" ],
    [ "basic_memory_pointer", "db/d5a/unioninjector_1_1basic__memory__pointer.html", "db/d5a/unioninjector_1_1basic__memory__pointer" ],
    [ "cstd", "d5/d85/structinjector_1_1cstd.html", null ],
    [ "cstd< Ret(Args...)>", "d0/dd8/structinjector_1_1cstd_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "fastcall", "d7/dcb/structinjector_1_1fastcall.html", null ],
    [ "fastcall< Ret(Args...)>", "d6/de8/structinjector_1_1fastcall_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "game_version_manager", "d3/d72/classinjector_1_1game__version__manager.html", "d3/d72/classinjector_1_1game__version__manager" ],
    [ "hook_back", "de/d7f/structinjector_1_1hook__back.html", "de/d7f/structinjector_1_1hook__back" ],
    [ "lazy_object", "d8/d06/structinjector_1_1lazy__object.html", null ],
    [ "lazy_pointer", "d9/d16/structinjector_1_1lazy__pointer.html", null ],
    [ "memory_pointer_tr", "d1/d8d/unioninjector_1_1memory__pointer__tr.html", "d1/d8d/unioninjector_1_1memory__pointer__tr" ],
    [ "reg_pack", "dc/dc0/structinjector_1_1reg__pack.html", "dc/dc0/structinjector_1_1reg__pack" ],
    [ "scoped_base", "df/d58/classinjector_1_1scoped__base.html", "df/d58/classinjector_1_1scoped__base" ],
    [ "scoped_basic", "df/d36/classinjector_1_1scoped__basic.html", "df/d36/classinjector_1_1scoped__basic" ],
    [ "scoped_call", "d3/db5/classinjector_1_1scoped__call.html", "d3/db5/classinjector_1_1scoped__call" ],
    [ "scoped_callback", "d6/d3a/classinjector_1_1scoped__callback.html", "d6/d3a/classinjector_1_1scoped__callback" ],
    [ "scoped_fill", "dc/daf/classinjector_1_1scoped__fill.html", "dc/daf/classinjector_1_1scoped__fill" ],
    [ "scoped_jmp", "da/dc4/classinjector_1_1scoped__jmp.html", "da/dc4/classinjector_1_1scoped__jmp" ],
    [ "scoped_nop", "d7/da1/classinjector_1_1scoped__nop.html", "d7/da1/classinjector_1_1scoped__nop" ],
    [ "scoped_unprotect", "df/d2c/structinjector_1_1scoped__unprotect.html", "df/d2c/structinjector_1_1scoped__unprotect" ],
    [ "scoped_write", "de/de8/classinjector_1_1scoped__write.html", "de/de8/classinjector_1_1scoped__write" ],
    [ "stdcall", "dd/da7/structinjector_1_1stdcall.html", null ],
    [ "stdcall< Ret(Args...)>", "d2/d57/structinjector_1_1stdcall_3_01_ret_07_args_8_8_8_08_4.html", null ],
    [ "thiscall", "d3/d11/structinjector_1_1thiscall.html", null ],
    [ "thiscall< Ret(Args...)>", "d0/d57/structinjector_1_1thiscall_3_01_ret_07_args_8_8_8_08_4.html", null ]
];